//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::VersionByte;
use crate::types::CanonicalBump;
use crate::types::StatusBits;
use crate::types::ArciumX25519PublicKey;
use crate::types::ArciumX25519Nonce;
use crate::types::ReservedByte;
use crate::types::RescueCiphertext;
use crate::types::RandomGenerationSeed;
use crate::types::NonceGenerationIndex;
use crate::types::Amount;
use crate::types::QueuedComputationCount;
use crate::types::SlotNumber;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct EncryptedTokenAccount {
pub discriminator: [u8; 8],
pub version_byte: VersionByte,
pub canonical_bump: CanonicalBump,
pub status_bits: StatusBits,
pub x25519_public_key: ArciumX25519PublicKey,
pub nonce: ArciumX25519Nonce,
pub mpc_nonce_padding: [ReservedByte; 16],
pub balance: RescueCiphertext,
/// Hidden lottery point score for the shorter-window epoch. Per
/// (user, token); accumulates the MPC-decrypted ticket count from
/// every confidential create/claim that targets this account.
/// Initialised to encrypted-zero by the dedicated init MPC instruction
/// (`is_points_initialised` flag tracks whether this has been done).
/// Epoch-rollover/decay logic is out of scope for this commit.
pub points_short_epoch: RescueCiphertext,
/// Hidden lottery point score for the longer-window epoch. Same
/// accumulation semantics as `points_short_epoch` — both fields are
/// updated with the same ticket-count addition by every confidential
/// create/claim. The short-vs-long distinction will be applied later
/// via separate reset/rollover instructions.
pub points_long_epoch: RescueCiphertext,
pub random_generation_seed: RandomGenerationSeed,
pub generation_index: NonceGenerationIndex,
pub staging_sol_amount: Amount,
pub staging_spl_amount: Amount,
pub queued_computation_count: QueuedComputationCount,
pub oldest_pending_slot: SlotNumber,
#[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
pub reserved_byte: [ReservedByte; 128],
}


pub const ENCRYPTED_TOKEN_ACCOUNT_DISCRIMINATOR: [u8; 8] = [238, 123, 84, 113, 137, 77, 62, 75];

impl EncryptedTokenAccount {
      pub const LEN: usize = 388;
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for EncryptedTokenAccount {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_encrypted_token_account(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::DecodedAccount<EncryptedTokenAccount>, std::io::Error> {
  let accounts = fetch_all_encrypted_token_account(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_encrypted_token_account(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::DecodedAccount<EncryptedTokenAccount>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<EncryptedTokenAccount>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::new(std::io::ErrorKind::Other, format!("Account not found: {}", address)))?;
      let data = EncryptedTokenAccount::from_bytes(&account.data)?;
      decoded_accounts.push(crate::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_encrypted_token_account(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::MaybeAccount<EncryptedTokenAccount>, std::io::Error> {
    let accounts = fetch_all_maybe_encrypted_token_account(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_encrypted_token_account(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::MaybeAccount<EncryptedTokenAccount>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<EncryptedTokenAccount>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = EncryptedTokenAccount::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::MaybeAccount::Exists(crate::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for EncryptedTokenAccount {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for EncryptedTokenAccount {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for EncryptedTokenAccount {
      fn owner() -> Pubkey {
        crate::UMBRA_ID
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for EncryptedTokenAccount {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for EncryptedTokenAccount {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

