//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::VersionByte;
use crate::types::CanonicalBump;
use crate::types::ArciumX25519PublicKey;
use crate::types::ArciumX25519Nonce;
use crate::types::RescueCiphertext;
use crate::types::PoseidonHash;
use crate::types::FieldElement25519;
use crate::types::Groth16ProofA;
use crate::types::Groth16ProofB;
use crate::types::Groth16ProofC;
use crate::types::UnixEpochTimestamp;
use crate::types::OptionalData;
use crate::types::Amount;
use crate::types::BasisPoints;
use crate::types::SmallMerkleTreeIndex;
use crate::types::ReservedByte;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PublicClaimInputBuffer {
pub discriminator: [u8; 8],
pub version_byte: VersionByte,
pub canonical_bump: CanonicalBump,
/// The X25519 public key used for Rescue encryption
pub rescue_encryption_public_key: ArciumX25519PublicKey,
/// Nonce used for the Rescue encryption scheme
pub rescue_encryption_nonce: ArciumX25519Nonce,
/// Encrypted master viewing key (single 256-bit Curve25519 field
/// element, rescue-encrypted into one 32-byte ciphertext).
pub rescue_encrypted_master_viewing_key: RescueCiphertext,
/// Encrypted blinding factor (single 256-bit Curve25519 field
/// element) for commitment.
pub rescue_encrypted_random_factor_for_polynomial: RescueCiphertext,
/// Poseidon hash commitment binding the encryption to the ZK proof
pub rescue_encryption_commitment: PoseidonHash,
/// Polynomial evaluation for Fiat-Shamir encryption validation
pub encryption_validation_polynomial: FieldElement25519,
/// Groth16 proof element A (G1 point, 64 bytes)
pub groth16_proof_a: Groth16ProofA,
/// Groth16 proof element B (G2 point, 128 bytes)
pub groth16_proof_b: Groth16ProofB,
/// Groth16 proof element C (G1 point, 64 bytes)
pub groth16_proof_c: Groth16ProofC,
/// The Merkle root of the commitment tree at time of proof generation
pub merkle_root: PoseidonHash,
/// Unix epoch timestamp for Transaction Viewing Key (transaction viewing key)
/// Used in the aggregated hash for ZK proof verification.
/// Must be validated against current clock time within maximum allowed difference.
pub transaction_viewing_key_timestamp: UnixEpochTimestamp,
/// Optional data field for application-specific metadata
pub optional_data: OptionalData,
/// Lower bound of the protocol fee slab (inclusive)
pub protocol_fees_amount_lower_bound: Amount,
/// Upper bound of the protocol fee slab (inclusive)
pub protocol_fees_amount_upper_bound: Amount,
/// Base fee in SPL tokens for the protocol fee slab
pub protocol_fees_base_fees_in_spl: Amount,
/// Commission fee in basis points for the protocol fee slab
pub protocol_fees_commission_fee_in_spl: BasisPoints,
/// Merkle path for the protocol fee slab (depth 4)
pub protocol_fees_merkle_path: [PoseidonHash; 4],
/// Leaf index in the protocol fees Merkle tree
pub protocol_fees_leaf_index: SmallMerkleTreeIndex,
/// Lower bound of the relayer fee slab (inclusive)
pub relayer_fees_amount_lower_bound: Amount,
/// Upper bound of the relayer fee slab (inclusive)
pub relayer_fees_amount_upper_bound: Amount,
/// Base fee in SPL tokens for the relayer fee slab
pub relayer_fees_base_fees_in_spl: Amount,
/// Commission fee in basis points for the relayer fee slab
pub relayer_fees_commission_fee_in_spl: BasisPoints,
/// Merkle path for the relayer fee slab (depth 4)
pub relayer_fees_merkle_path: [PoseidonHash; 4],
/// Leaf index in the relayer fees Merkle tree
pub relayer_fees_leaf_index: SmallMerkleTreeIndex,
pub reserved_byte: [ReservedByte; 0],
}


pub const PUBLIC_CLAIM_INPUT_BUFFER_DISCRIMINATOR: [u8; 8] = [227, 59, 113, 126, 158, 160, 88, 176];

impl PublicClaimInputBuffer {
      pub const LEN: usize = 825;
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for PublicClaimInputBuffer {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_public_claim_input_buffer(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::DecodedAccount<PublicClaimInputBuffer>, std::io::Error> {
  let accounts = fetch_all_public_claim_input_buffer(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_public_claim_input_buffer(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::DecodedAccount<PublicClaimInputBuffer>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<PublicClaimInputBuffer>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::new(std::io::ErrorKind::Other, format!("Account not found: {}", address)))?;
      let data = PublicClaimInputBuffer::from_bytes(&account.data)?;
      decoded_accounts.push(crate::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_public_claim_input_buffer(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::MaybeAccount<PublicClaimInputBuffer>, std::io::Error> {
    let accounts = fetch_all_maybe_public_claim_input_buffer(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_public_claim_input_buffer(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::MaybeAccount<PublicClaimInputBuffer>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<PublicClaimInputBuffer>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = PublicClaimInputBuffer::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::MaybeAccount::Exists(crate::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for PublicClaimInputBuffer {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for PublicClaimInputBuffer {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for PublicClaimInputBuffer {
      fn owner() -> Pubkey {
        crate::UMBRA_ID
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for PublicClaimInputBuffer {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for PublicClaimInputBuffer {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

