//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::LocalCircuitSource;
use crate::types::OnChainCircuitSource;
use crate::types::OffChainCircuitSource;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum CircuitSource {
Local(LocalCircuitSource),
OnChain(OnChainCircuitSource),
OffChain(OffChainCircuitSource),
}


