//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::CanonicalBump;
use crate::types::ArciumX25519PublicKey;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitialiseNetworkX25519KeyEventV1 {
pub network_key: [u8; 32],
pub admin_wallet: [u8; 32],
pub signer: [u8; 32],
pub canonical_bump: CanonicalBump,
pub network_x25519_public_key: ArciumX25519PublicKey,
pub optional_data: OptionalData,
}


