//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::RescueCiphertext;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReencryptUserGrantV13ExtractedOutput {
pub output_ciphertext0: RescueCiphertext,
pub output_ciphertext1: RescueCiphertext,
pub output_ciphertext2: RescueCiphertext,
pub output_ciphertext3: RescueCiphertext,
pub output_ciphertext4: RescueCiphertext,
pub output_ciphertext5: RescueCiphertext,
}


