//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::RescueCiphertext;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ResetFeeVaultQueueV13ExtractedOutput {
pub relayer_encrypted_fees_balance: RescueCiphertext,
pub protocol_encrypted_fees_balance: RescueCiphertext,
pub encrypted_transaction_count: RescueCiphertext,
}


