//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::StatusBits;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdatePoolEventV1 {
pub token_pool: [u8; 32],
pub protocol_config: [u8; 32],
pub admin_wallet: [u8; 32],
pub signer: [u8; 32],
pub mint: [u8; 32],
pub status_bits: StatusBits,
pub optional_data: OptionalData,
}


