//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::RandomGenerationSeed;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateTokenAccountRandomGenerationSeedEventV1 {
pub user: [u8; 32],
pub token_account: [u8; 32],
pub old_seed: RandomGenerationSeed,
pub new_seed: RandomGenerationSeed,
pub optional_data: OptionalData,
}


