//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimIntoExistingNetworkBalanceV17OutputStruct0 {
pub field0: ClaimIntoExistingNetworkBalanceV17OutputStruct0Field0,
pub field1: ClaimIntoExistingNetworkBalanceV17OutputStruct0Field1,
pub field2: bool,
pub field3: ClaimIntoExistingNetworkBalanceV17OutputStruct0Field3,
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimIntoExistingNetworkBalanceV17OutputStruct0Field0 {
pub ciphertexts: [[u8; 32]; 3],
}
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimIntoExistingNetworkBalanceV17OutputStruct0Field1 {
pub ciphertexts: [[u8; 32]; 4],
}
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimIntoExistingNetworkBalanceV17OutputStruct0Field3 {
pub ciphertexts: [[u8; 32]; 1],
}

