//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use crate::types::Amount;
use crate::types::OptionalData;
use crate::types::AccountOffset;
use crate::types::ArciumX25519PublicKey;
use crate::types::ArciumX25519Nonce;
use crate::types::RescueCiphertext;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Event emitted when the callback successfully completes.
/// 
/// This event captures all information about the completed claim transaction,
/// including the MPC computation outputs for indexing and auditing purposes.
/// 
/// # Use Cases
/// 
/// - **Indexing**: Track all claims for analytics and compliance
/// - **Debugging**: Verify computation outputs match expectations
/// - **Auditing**: Verify fee calculations and transfer amounts
/// - **User Notification**: Confirm claim completion to user interfaces
/// 
/// # Fields
/// 
/// ## Account Identifiers
/// Used to identify which accounts were involved in the transaction.
/// 
/// ## Amounts
/// All monetary values involved in the transaction.
/// 
/// ## MPC Outputs
/// The outputs from the Arcium MPC computation, useful for verifying
/// the encrypted master viewing key state.
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimIntoPublicBalanceToMxeV17CallbackEventV1 {
/// The receiver's wallet address
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub receiver_address: Pubkey,
/// The account that received the funds — for wrapped SOL this is the receiver's
/// wallet address, for other tokens this is the receiver's ATA.
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub receiver_account: Pubkey,
/// The SPL token mint for the claimed tokens
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub mint: Pubkey,
/// The fee vault that accumulated both relayer and protocol fees
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub fee_vault: Pubkey,
/// The pool account that the funds were withdrawn from
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub token_pool: Pubkey,
/// The Arcium computation account for this MPC job
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub computation_account: Pubkey,
/// Total claim amount (before fee deduction)
pub transfer_amount: Amount,
/// Protocol fees deducted (SPL tokens)
pub protocol_fees_spl: Amount,
/// Relayer fees deducted (SPL tokens)
pub relayer_fees_spl: Amount,
/// Relayer SOL compensation for gas
pub relayer_fees_sol: Amount,
/// Whether the MPC validation passed (should always be true if event emitted)
pub is_valid_transaction: bool,
/// Optional metadata attached to the transaction
pub optional_data: OptionalData,
pub audit_tree_offset: AccountOffset,
pub audit_tree_insertion_index: u128,
pub audit_tree_leaf: [u8; 32],
pub audit_tree_root_after_insert: [u8; 32],
pub rescue_encryption_public_key: ArciumX25519PublicKey,
pub rescue_encryption_nonce: ArciumX25519Nonce,
pub session_encrypted_master_viewing_key: RescueCiphertext,
/// Relayer public SOL fees before this transaction
pub pre_fee_vault_relayer_public_fees_sol: Amount,
/// Protocol public SPL fees before this transaction
pub pre_fee_vault_protocol_public_fees_spl: Amount,
}


