//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::ArciumX25519Nonce;
use crate::types::ArciumX25519PublicKey;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateNetworkGrantForNetworkBalanceEventV1 {
pub admin_wallet: [u8; 32],
pub signer: [u8; 32],
pub viewing_grant: [u8; 32],
pub nonce: ArciumX25519Nonce,
pub receiver_x25519: ArciumX25519PublicKey,
pub optional_data: OptionalData,
}


