//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::ArciumX25519Nonce;
use crate::types::RescueCiphertext;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitialiseTotalVolumeForProtocolFeeVaultV17CallbackEventV1 {
pub fee_vault: [u8; 32],
pub computation_account: [u8; 32],
pub nonce: ArciumX25519Nonce,
pub relayer_fees: RescueCiphertext,
pub protocol_fees: RescueCiphertext,
pub transaction_count: RescueCiphertext,
pub total_volume_transferred: RescueCiphertext,
pub optional_data: OptionalData,
pub pre_fee_vault_nonce: ArciumX25519Nonce,
pub pre_relayer_fees: RescueCiphertext,
pub pre_protocol_fees: RescueCiphertext,
pub pre_transaction_count: RescueCiphertext,
}


