//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::AccountOffset;
use crate::types::CanonicalBump;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitialiseClaimerMvkAuditTreeEventV1 {
pub claimer_mvk_audit_tree: [u8; 32],
pub protocol_config: [u8; 32],
pub admin_wallet: [u8; 32],
pub signer: [u8; 32],
pub audit_tree_offset: AccountOffset,
pub canonical_bump: CanonicalBump,
pub optional_data: OptionalData,
}


