//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use crate::types::UtilityPubkeys;
use crate::types::MxeStatus;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// A MPC Execution Environment.
#[derive(Clone, Debug, Eq, PartialEq, borsh::BorshSerialize, borsh::BorshDeserialize)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum MXEAccountUtilityPubkeys {
Set(UtilityPubkeys),
Unset(UtilityPubkeys, Vec<bool>),
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct MXEAccount {
pub padding: u8,
pub cluster: u32,
pub keygen_offset: u64,
pub key_recovery_init_offset: u64,
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub mxe_program_id: Pubkey,
pub authority: Option<Pubkey>,
pub utility_pubkeys: MXEAccountUtilityPubkeys,
pub lut_offset_slot: u64,
pub computation_definitions: Vec<u32>,
pub status: MxeStatus,
pub bump: u8,
}


