//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::AccountOffset;
use crate::types::CanonicalBump;
use crate::types::ArciumX25519PublicKey;
use crate::types::ArciumX25519Nonce;
use crate::types::RescueCiphertext;
use crate::types::PoseidonHash;
use crate::types::FieldElement25519;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PopulatePublicClaimInputBufferEventV1 {
pub offset: AccountOffset,
pub canonical_bump: CanonicalBump,
pub relayer: [u8; 32],
pub public_claim_input_buffer: [u8; 32],
pub rescue_encryption_public_key: ArciumX25519PublicKey,
pub rescue_encryption_nonce: ArciumX25519Nonce,
pub rescue_encrypted_master_viewing_key: RescueCiphertext,
pub rescue_encrypted_random_factor_for_polynomial: RescueCiphertext,
pub rescue_encryption_commitment: PoseidonHash,
pub encryption_validation_polynomial: FieldElement25519,
pub merkle_root: PoseidonHash,
pub optional_data: OptionalData,
}


