//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::ComputationOffset;
use crate::types::AccountOffset;
use crate::types::Amount;
use crate::types::PriorityFees;
use crate::types::ArciumX25519PublicKey;
use crate::types::ArciumX25519Nonce;
use crate::types::RescueCiphertext;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct WithdrawFromSharedBalanceIntoPublicBalanceV17EventV1 {
pub user_address: [u8; 32],
pub user_token_account: [u8; 32],
pub token_pool: [u8; 32],
pub mint: [u8; 32],
pub computation_account: [u8; 32],
pub computation_offset: ComputationOffset,
pub mpc_callback_data_offset: AccountOffset,
pub withdrawal_amount: Amount,
pub priority_fees: PriorityFees,
pub pre_user_x25519_public_key: ArciumX25519PublicKey,
pub pre_user_nonce: ArciumX25519Nonce,
pub pre_user_balance: RescueCiphertext,
pub pre_fee_vault_relayer_public_fees_spl: Amount,
pub pre_fee_vault_protocol_public_fees_spl: Amount,
pub optional_data: OptionalData,
}


