//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum UmbraError {
    /// 12000 - Invalid computation
    #[error("Invalid computation")]
    InvalidComputation = 0x2EE0,
    /// 12001 - Invalid callback
    #[error("Invalid callback")]
    InvalidCallback = 0x2EE1,
    /// 12002 - The computation was aborted
    #[error("The computation was aborted")]
    AbortedComputation = 0x2EE2,
    /// 12003 - Callback instruction generation failed
    #[error("Callback instruction generation failed")]
    CallbackInstructionGenerationFailed = 0x2EE3,
    /// 12004 - Invalid transaction
    #[error("Invalid transaction")]
    InvalidTransaction = 0x2EE4,
    /// 13000 - Cluster not set
    #[error("Cluster not set")]
    ClusterNotSet = 0x32C8,
    /// 13001 - Invalid mempool account address
    #[error("Invalid mempool account address")]
    InvalidMempoolAccountAddress = 0x32C9,
    /// 13002 - Invalid executing pool account address
    #[error("Invalid executing pool account address")]
    InvalidExecpoolAccountAddress = 0x32CA,
    /// 13003 - Invalid computation account address
    #[error("Invalid computation account address")]
    InvalidComputationAccountAddress = 0x32CB,
    /// 13004 - Invalid computation definition account address
    #[error("Invalid computation definition account address")]
    InvalidCompDefAccountAddress = 0x32CC,
    /// 13005 - Invalid cluster account address
    #[error("Invalid cluster account address")]
    InvalidClusterAccountAddress = 0x32CD,
    /// 13006 - Invalid sign PDA account address
    #[error("Invalid sign PDA account address")]
    InvalidSignPdaAccountAddress = 0x32CE,
    /// 13007 - Failed to derive mempool account address
    #[error("Failed to derive mempool account address")]
    MempoolAccountDerivationFailed = 0x32CF,
    /// 13008 - Failed to derive executing pool account address
    #[error("Failed to derive executing pool account address")]
    ExecpoolAccountDerivationFailed = 0x32D0,
    /// 13009 - Failed to derive computation account address
    #[error("Failed to derive computation account address")]
    ComputationAccountDerivationFailed = 0x32D1,
    /// 13010 - Failed to derive computation definition account address
    #[error("Failed to derive computation definition account address")]
    CompDefAccountDerivationFailed = 0x32D2,
    /// 13011 - Failed to derive cluster account address
    #[error("Failed to derive cluster account address")]
    ClusterAccountDerivationFailed = 0x32D3,
    /// 13012 - Failed to derive sign PDA account address
    #[error("Failed to derive sign PDA account address")]
    SignPdaAccountDerivationFailed = 0x32D4,
    /// 13013 - Invalid confidential claim proof account address
    #[error("Invalid confidential claim proof account address")]
    InvalidConfidentialClaimProofAccountAddress = 0x32D5,
    /// 13014 - Invalid confidential claim proof account bump
    #[error("Invalid confidential claim proof account bump")]
    InvalidConfidentialClaimProofAccountBump = 0x32D6,
    /// 13015 - Invalid ZK verifying key account address
    #[error("Invalid ZK verifying key account address")]
    InvalidZkVerifyingKeyAccountAddress = 0x32D7,
    /// 13016 - Invalid ZK verifying key account bump
    #[error("Invalid ZK verifying key account bump")]
    InvalidZkVerifyingKeyAccountBump = 0x32D8,
    /// 13017 - Invalid pool account address
    #[error("Invalid pool account address")]
    InvalidPoolAccountAddress = 0x32D9,
    /// 13018 - Invalid pool account bump
    #[error("Invalid pool account bump")]
    InvalidPoolAccountBump = 0x32DA,
    /// 13019 - Invalid program information account address
    #[error("Invalid program information account address")]
    InvalidProtocolConfigAccountAddress = 0x32DB,
    /// 13020 - Invalid program information account bump
    #[error("Invalid program information account bump")]
    InvalidProtocolConfigAccountBump = 0x32DC,
    /// 13021 - Invalid stealth pool account address
    #[error("Invalid stealth pool account address")]
    InvalidStealthPoolAccountAddress = 0x32DD,
    /// 14000 - Unable to Poseidon hash public inputs
    #[error("Unable to Poseidon hash public inputs")]
    UnableToPoseidonHashPublicInputs = 0x36B0,
    /// 14001 - Invalid ciphertext size
    #[error("Invalid ciphertext size")]
    InvalidCiphertextSize = 0x36B1,
    /// 14002 - Invalid ciphertext format
    #[error("Invalid ciphertext format")]
    InvalidCiphertextFormat = 0x36B2,
    /// 14003 - Groth16 verifier creation failed
    #[error("Groth16 verifier creation failed")]
    Groth16VerifierCreationFailed = 0x36B3,
    /// 14004 - Unable to initialise Groth16 verifier
    #[error("Unable to initialise Groth16 verifier")]
    UnableToInitialiseGroth16Verifier = 0x36B4,
    /// 14005 - Unable to verify Groth16 proof
    #[error("Unable to verify Groth16 proof")]
    UnableToVerifyGroth16Proof = 0x36B5,
    /// 14006 - Duplicate nullifier
    #[error("Duplicate nullifier")]
    DuplicateNullifier = 0x36B6,
    /// 14007 - Duplicate linker
    #[error("Duplicate linker")]
    DuplicateLinker = 0x36B7,
    /// 14008 - UnixEpochTimestamp difference exceeds maximum allowed
    #[error("UnixEpochTimestamp difference exceeds maximum allowed")]
    TimestampDifferenceExceedsMaximum = 0x36B8,
    /// 14009 - UnixEpochTimestamp must be positive
    #[error("UnixEpochTimestamp must be positive")]
    TimestampMustBePositive = 0x36B9,
    /// 14010 - Failed to deserialize proof A
    #[error("Failed to deserialize proof A")]
    FailedToDeserializeProofA = 0x36BA,
    /// 14011 - Failed to serialize negated proof A
    #[error("Failed to serialize negated proof A")]
    FailedToSerializeNegatedProofA = 0x36BB,
    /// 14012 - Failed to convert negated proof A
    #[error("Failed to convert negated proof A")]
    FailedToConvertNegatedProofA = 0x36BC,
    /// 14013 - RescueCiphertext is not a valid Curve25519 field element (must be < 2^255 - 19)
    #[error("RescueCiphertext is not a valid Curve25519 field element (must be < 2^255 - 19)")]
    InvalidRescueCiphertextFieldElement = 0x36BD,
    /// 14014 - PoseidonHash is not a valid BN254 scalar field element
    #[error("PoseidonHash is not a valid BN254 scalar field element")]
    InvalidPoseidonHashFieldElement = 0x36BE,
    /// 14015 - PoseidonCiphertext is not a valid BN254 scalar field element
    #[error("PoseidonCiphertext is not a valid BN254 scalar field element")]
    InvalidPoseidonCiphertextFieldElement = 0x36BF,
    /// 14016 - FieldElement25519 is not a valid Curve25519 field element (must be < 2^255 - 19)
    #[error("FieldElement25519 is not a valid Curve25519 field element (must be < 2^255 - 19)")]
    InvalidFieldElement25519 = 0x36C0,
    /// 14017 - UnixEpochTimestamp cannot be in the future
    #[error("UnixEpochTimestamp cannot be in the future")]
    TimestampInFuture = 0x36C1,
    /// 14018 - Deposit amount must be greater than zero after fees
    #[error("Deposit amount must be greater than zero after fees")]
    DepositAmountTooSmall = 0x36C2,
    /// 14019 - Invalid public inputs length
    #[error("Invalid public inputs length")]
    InvalidPublicInputsLength = 0x36C3,
    /// 14020 - Bn254ScalarElement is not a valid BN254 scalar field element
    #[error("Bn254ScalarElement is not a valid BN254 scalar field element")]
    InvalidBn254ScalarElement = 0x36C4,
    /// 14100 - Deposit amount mismatch: actual amount received does not match expected deposit amount
    #[error("Deposit amount mismatch: actual amount received does not match expected deposit amount")]
    DepositAmountMismatch = 0x3714,
    /// 14101 - Depositor must be the same as receiver for this instruction
    #[error("Depositor must be the same as receiver for this instruction")]
    DepositorMustBeReceiver = 0x3715,
    /// 14102 - Transfer amount must be greater than or equal to deposit amount
    #[error("Transfer amount must be greater than or equal to deposit amount")]
    TransferAmountLessThanDepositAmount = 0x3716,
    /// 14200 - Claim amount is too small to cover fees
    #[error("Claim amount is too small to cover fees")]
    ClaimAmountTooSmallForFees = 0x3778,
    /// 14230 - Claimer MVK audit tree is not initialised
    #[error("Claimer MVK audit tree is not initialised")]
    ClaimerMvkAuditTreeNotInitialised = 0x3796,
    /// 15000 - Custom error message
    #[error("Custom error message")]
    CustomError = 0x3A98,
    /// 15001 - Arithmetic overflow
    #[error("Arithmetic overflow")]
    ArithmeticOverflow = 0x3A99,
    /// 16000 - Wallet specifier not initialised
    #[error("Wallet specifier not initialised")]
    WalletSpecifierNotInitialised = 0x3E80,
    /// 16001 - Invalid instruction seed
    #[error("Invalid instruction seed")]
    InvalidInstructionSeed = 0x3E81,
    /// 16002 - Unauthorized signer
    #[error("Unauthorized signer")]
    UnauthorizedSigner = 0x3E82,
    /// 16003 - Invariant violation
    #[error("Invariant violation")]
    InvariantViolation = 0x3E83,
    /// 16005 - Unauthorized status bit modification - only specific bits can be modified
    #[error("Unauthorized status bit modification - only specific bits can be modified")]
    UnauthorizedStatusBitModification = 0x3E85,
    /// 16006 - Wallet specifier is permanently permissionless and cannot be updated
    #[error("Wallet specifier is permanently permissionless and cannot be updated")]
    WalletSpecifierIsPermanentlyPermissionless = 0x3E86,
    /// 18000 - Arcium encrypted user account is initialised bit must be set
    #[error("Arcium encrypted user account is initialised bit must be set")]
    EncryptedUserAccountIsInitialisedBitMustBeSet = 0x4650,
    /// 18001 - Arcium encrypted user account is active bit must be set
    #[error("Arcium encrypted user account is active bit must be set")]
    EncryptedUserAccountIsActiveBitMustBeSet = 0x4651,
    /// 18002 - Arcium encrypted user account is active for confidential usage bit must be set
    #[error("Arcium encrypted user account is active for confidential usage bit must be set")]
    EncryptedUserAccountIsActiveForConfidentialUsageBitMustBeSet = 0x4652,
    /// 18003 - Arcium encrypted user account is active for anonymous usage bit must be set
    #[error("Arcium encrypted user account is active for anonymous usage bit must be set")]
    EncryptedUserAccountIsActiveForAnonymousUsageBitMustBeSet = 0x4653,
    /// 18004 - Arcium encrypted user account is user commitment registered bit must be set
    #[error("Arcium encrypted user account is user commitment registered bit must be set")]
    EncryptedUserAccountIsUserCommitmentRegisteredBitMustBeSet = 0x4654,
    /// 18005 - Arcium encrypted user account is x25519 master viewing key public key registered bit must be set
    #[error("Arcium encrypted user account is x25519 master viewing key public key registered bit must be set")]
    EncryptedUserAccountIsX25519PublicKeyForMasterViewingKeyEncryptionRegisteredBitMustBeSet = 0x4655,
    /// 18006 - Arcium encrypted user account is above threshold encrypted sol balance bit must be set
    #[error("Arcium encrypted user account is above threshold encrypted sol balance bit must be set")]
    EncryptedUserAccountIsAboveThresholdEncryptedSolBalanceBitMustBeSet = 0x4656,
    /// 18007 - Arcium encrypted user account is transaction data initialised bit must be set
    #[error("Arcium encrypted user account is transaction data initialised bit must be set")]
    EncryptedUserAccountIsTransactionDataInitialisedBitMustBeSet = 0x4657,
    /// 18008 - Arcium encrypted user account is initialised bit must not be set
    #[error("Arcium encrypted user account is initialised bit must not be set")]
    EncryptedUserAccountIsInitialisedBitMustNotBeSet = 0x4658,
    /// 18009 - Arcium encrypted user account is active bit must not be set
    #[error("Arcium encrypted user account is active bit must not be set")]
    EncryptedUserAccountIsActiveBitMustNotBeSet = 0x4659,
    /// 18010 - Arcium encrypted user account is user commitment registered bit must not be set
    #[error("Arcium encrypted user account is user commitment registered bit must not be set")]
    EncryptedUserAccountIsUserCommitmentRegisteredBitMustNotBeSet = 0x465A,
    /// 18011 - Arcium encrypted user account is x25519 master viewing key public key registered bit must not be set
    #[error("Arcium encrypted user account is x25519 master viewing key public key registered bit must not be set")]
    EncryptedUserAccountIsX25519PublicKeyForMasterViewingKeyEncryptionRegisteredBitMustNotBeSet = 0x465B,
    /// 18012 - Arcium encrypted user account is above threshold encrypted sol balance bit must not be set
    #[error("Arcium encrypted user account is above threshold encrypted sol balance bit must not be set")]
    EncryptedUserAccountIsAboveThresholdEncryptedSolBalanceBitMustNotBeSet = 0x465C,
    /// 18013 - Arcium encrypted user account is transaction data initialised bit must not be set
    #[error("Arcium encrypted user account is transaction data initialised bit must not be set")]
    EncryptedUserAccountIsTransactionDataInitialisedBitMustNotBeSet = 0x465D,
    /// 18014 - Invalid X25519 public key - key must not be all zeros
    #[error("Invalid X25519 public key - key must not be all zeros")]
    InvalidX25519PublicKey = 0x465E,
    /// 18015 - Invalid random generation seed - seed must not be all zeros
    #[error("Invalid random generation seed - seed must not be all zeros")]
    InvalidRandomGenerationSeed = 0x465F,
    /// 18016 - Arcium encrypted user account is x25519 token public key registered bit must be set
    #[error("Arcium encrypted user account is x25519 token public key registered bit must be set")]
    EncryptedUserAccountIsX25519PublicKeyForTokenAccountsRegisteredBitMustBeSet = 0x4660,
    /// 18017 - Arcium encrypted user account is x25519 token public key registered bit must not be set
    #[error("Arcium encrypted user account is x25519 token public key registered bit must not be set")]
    EncryptedUserAccountIsX25519PublicKeyForTokenAccountsRegisteredBitMustNotBeSet = 0x4661,
    /// 18018 - Failed to decompress Ed25519 public key - invalid point on curve
    #[error("Failed to decompress Ed25519 public key - invalid point on curve")]
    InvalidEdwardsPointDecompression = 0x4662,
    /// 18019 - X25519 proving signer's Ed25519 key does not correspond to the stored X25519 master viewing key public key
    #[error("X25519 proving signer's Ed25519 key does not correspond to the stored X25519 master viewing key public key")]
    X25519ProvingSignerMismatch = 0x4663,
    /// 19000 - Arcium encrypted token account is initialised bit must be set
    #[error("Arcium encrypted token account is initialised bit must be set")]
    EncryptedTokenAccountIsInitialisedBitMustBeSet = 0x4A38,
    /// 19001 - Arcium encrypted token account is active for confidential usage bit must be set
    #[error("Arcium encrypted token account is active for confidential usage bit must be set")]
    EncryptedTokenAccountIsActiveForConfidentialUsageBitMustBeSet = 0x4A39,
    /// 19002 - Arcium encrypted token account is active for anonymous usage bit must be set
    #[error("Arcium encrypted token account is active for anonymous usage bit must be set")]
    EncryptedTokenAccountIsActiveForAnonymousUsageBitMustBeSet = 0x4A3A,
    /// 19003 - Arcium encrypted token account is shared mode bit must be set
    #[error("Arcium encrypted token account is shared mode bit must be set")]
    EncryptedTokenAccountIsSharedModeBitMustBeSet = 0x4A3B,
    /// 19004 - Arcium encrypted token account is arcium balance initialised bit must be set
    #[error("Arcium encrypted token account is arcium balance initialised bit must be set")]
    EncryptedTokenAccountIsArciumBalanceInitialisedBitMustBeSet = 0x4A3C,
    /// 19005 - Arcium encrypted token account is initialised bit must not be set
    #[error("Arcium encrypted token account is initialised bit must not be set")]
    EncryptedTokenAccountIsInitialisedBitMustNotBeSet = 0x4A3D,
    /// 19006 - Arcium encrypted token account is active for confidential usage bit must not be set
    #[error("Arcium encrypted token account is active for confidential usage bit must not be set")]
    EncryptedTokenAccountIsActiveForConfidentialUsageBitMustNotBeSet = 0x4A3E,
    /// 19007 - Arcium encrypted token account is active for anonymous usage bit must not be set
    #[error("Arcium encrypted token account is active for anonymous usage bit must not be set")]
    EncryptedTokenAccountIsActiveForAnonymousUsageBitMustNotBeSet = 0x4A3F,
    /// 19008 - Arcium encrypted token account is shared mode bit must not be set
    #[error("Arcium encrypted token account is shared mode bit must not be set")]
    EncryptedTokenAccountIsSharedModeBitMustNotBeSet = 0x4A40,
    /// 19009 - Arcium encrypted token account is arcium balance initialised bit must not be set
    #[error("Arcium encrypted token account is arcium balance initialised bit must not be set")]
    EncryptedTokenAccountIsArciumBalanceInitialisedBitMustNotBeSet = 0x4A41,
    /// 19010 - Insufficient staged amount for finalization
    #[error("Insufficient staged amount for finalization")]
    InsufficientStagedAmount = 0x4A42,
    /// 19011 - Token account cannot exist without an initialized user account
    #[error("Token account cannot exist without an initialized user account")]
    TokenAccountCannotExistWithoutUserAccount = 0x4A43,
    /// 19012 - Token account is not active
    #[error("Token account is not active")]
    TokenAccountNotActive = 0x4A44,
    /// 19013 - Invalid mint - destination token account mint does not match
    #[error("Invalid mint - destination token account mint does not match")]
    InvalidMint = 0x4A45,
    /// 19014 - X25519 key already registered on token account
    #[error("X25519 key already registered on token account")]
    X25519KeyAlreadyRegistered = 0x4A46,
    /// 19015 - Cannot use NETWORK balance update in Shared mode - token has x25519 key registered
    #[error("Cannot use NETWORK balance update in Shared mode - token has x25519 key registered")]
    CannotUseNetworkBalanceInSharedMode = 0x4A47,
    /// 19016 - Cannot use Shared balance update in NETWORK mode - token does not have x25519 key registered
    #[error("Cannot use Shared balance update in NETWORK mode - token does not have x25519 key registered")]
    CannotUseSharedBalanceInNetworkMode = 0x4A48,
    /// 19017 - Token account is already in Shared mode
    #[error("Token account is already in Shared mode")]
    AlreadyInSharedMode = 0x4A49,
    /// 19018 - User must have X25519 token key registered to use Shared mode
    #[error("User must have X25519 token key registered to use Shared mode")]
    UserX25519KeyRequiredForSharedMode = 0x4A4A,
    /// 19019 - Token account x25519 key does not match user account - re-encryption required
    #[error("Token account x25519 key does not match user account - re-encryption required")]
    X25519KeyMismatch = 0x4A4B,
    /// 19020 - Token account x25519 key already matches user account - re-encryption not needed
    #[error("Token account x25519 key already matches user account - re-encryption not needed")]
    X25519KeyAlreadyMatches = 0x4A4C,
    /// 19021 - X25519 private key does not match the public key stored in the encrypted token account
    #[error("X25519 private key does not match the public key stored in the encrypted token account")]
    InvalidX25519PrivateKey = 0x4A4D,
    /// 19022 - Rescue-XLIX CTR mode decryption failed
    #[error("Rescue-XLIX CTR mode decryption failed")]
    RescueCipherDecryptionFailed = 0x4A4E,
    /// 19023 - Arcium encrypted token account is points initialised bit must be set
    #[error("Arcium encrypted token account is points initialised bit must be set")]
    EncryptedTokenAccountIsPointsInitialisedBitMustBeSet = 0x4A4F,
    /// 19024 - Arcium encrypted token account is points initialised bit must not be set
    #[error("Arcium encrypted token account is points initialised bit must not be set")]
    EncryptedTokenAccountIsPointsInitialisedBitMustNotBeSet = 0x4A50,
    /// 19025 - Account data is too short or has otherwise invalid size
    #[error("Account data is too short or has otherwise invalid size")]
    InvalidAccountSize = 0x4A51,
    /// 19026 - Account discriminator does not match the expected value for this struct
    #[error("Account discriminator does not match the expected value for this struct")]
    InvalidAccountDiscriminator = 0x4A52,
    /// 19027 - Encrypted token account has already been migrated to the points layout
    #[error("Encrypted token account has already been migrated to the points layout")]
    EncryptedTokenAccountAlreadyMigratedForPoints = 0x4A53,
    /// 19028 - Encrypted token account has an unexpected pre-migration size
    #[error("Encrypted token account has an unexpected pre-migration size")]
    EncryptedTokenAccountInvalidPreMigrationSize = 0x4A54,
    /// 19029 - Destination ATA does not match the destination registered at queue time
    #[error("Destination ATA does not match the destination registered at queue time")]
    InvalidDestinationAta = 0x4A55,
    /// 19030 - Account is not owned by the Umbra program
    #[error("Account is not owned by the Umbra program")]
    InvalidAccountOwner = 0x4A56,
    /// 19100 - Insufficient pool balance for transfer
    #[error("Insufficient pool balance for transfer")]
    InsufficientPoolBalance = 0x4A9C,
    /// 19500 - Arcium compliance grant is initialised bit must be set
    #[error("Arcium compliance grant is initialised bit must be set")]
    ViewingGrantIsInitialisedBitMustBeSet = 0x4C2C,
    /// 19501 - Arcium compliance grant is initialised bit must not be set
    #[error("Arcium compliance grant is initialised bit must not be set")]
    ViewingGrantIsInitialisedBitMustNotBeSet = 0x4C2D,
    /// 20000 - Public fees pool is initialised bit must be set
    #[error("Public fees pool is initialised bit must be set")]
    PublicFeesPoolIsInitialisedBitMustBeSet = 0x4E20,
    /// 20001 - Public fees pool is active bit must be set
    #[error("Public fees pool is active bit must be set")]
    PublicFeesPoolIsActiveBitMustBeSet = 0x4E21,
    /// 20002 - Public fees pool is initialised bit must not be set
    #[error("Public fees pool is initialised bit must not be set")]
    PublicFeesPoolIsInitialisedBitMustNotBeSet = 0x4E22,
    /// 20003 - Public fees pool is active bit must not be set
    #[error("Public fees pool is active bit must not be set")]
    PublicFeesPoolIsActiveBitMustNotBeSet = 0x4E23,
    /// 21200 - Protocol fees configuration is initialised bit must be set
    #[error("Protocol fees configuration is initialised bit must be set")]
    FeeScheduleIsInitialisedBitMustBeSet = 0x52D0,
    /// 21201 - Protocol fees configuration is active bit must be set
    #[error("Protocol fees configuration is active bit must be set")]
    FeeScheduleIsActiveBitMustBeSet = 0x52D1,
    /// 21204 - Protocol fees configuration is initialised bit must not be set
    #[error("Protocol fees configuration is initialised bit must not be set")]
    FeeScheduleIsInitialisedBitMustNotBeSet = 0x52D4,
    /// 21205 - Protocol fees configuration is active bit must not be set
    #[error("Protocol fees configuration is active bit must not be set")]
    FeeScheduleIsActiveBitMustNotBeSet = 0x52D5,
    /// 21207 - Fee schedule access is unauthorised: schedule was not derived with permissionless or caller's pubkey
    #[error("Fee schedule access is unauthorised: schedule was not derived with permissionless or caller's pubkey")]
    FeeScheduleUnauthorisedAccess = 0x52D7,
    /// 21300 - Protocol fees pool is initialised bit must be set
    #[error("Protocol fees pool is initialised bit must be set")]
    ProtocolFeesPoolIsInitialisedBitMustBeSet = 0x5334,
    /// 21301 - Protocol fees pool is active bit must be set
    #[error("Protocol fees pool is active bit must be set")]
    ProtocolFeesPoolIsActiveBitMustBeSet = 0x5335,
    /// 21302 - Protocol fees pool is initialised bit must not be set
    #[error("Protocol fees pool is initialised bit must not be set")]
    ProtocolFeesPoolIsInitialisedBitMustNotBeSet = 0x5336,
    /// 21303 - Protocol fees pool is active bit must not be set
    #[error("Protocol fees pool is active bit must not be set")]
    ProtocolFeesPoolIsActiveBitMustNotBeSet = 0x5337,
    /// 21304 - Protocol fees pool is encrypted balance initialised bit must be set
    #[error("Protocol fees pool is encrypted balance initialised bit must be set")]
    ProtocolFeesPoolIsEncryptedBalanceInitialisedBitMustBeSet = 0x5338,
    /// 21305 - Protocol fees pool is encrypted balance initialised bit must not be set
    #[error("Protocol fees pool is encrypted balance initialised bit must not be set")]
    ProtocolFeesPoolIsEncryptedBalanceInitialisedBitMustNotBeSet = 0x5339,
    /// 22000 - TokenPool is initialised bit must be set
    #[error("TokenPool is initialised bit must be set")]
    TokenPoolIsInitialisedBitMustBeSet = 0x55F0,
    /// 22001 - TokenPool is confidential pool active bit must be set
    #[error("TokenPool is confidential pool active bit must be set")]
    TokenPoolIsConfidentialPoolActiveBitMustBeSet = 0x55F1,
    /// 22002 - TokenPool is stealth pool active bit must be set
    #[error("TokenPool is stealth pool active bit must be set")]
    TokenPoolIsStealthPoolActiveBitMustBeSet = 0x55F2,
    /// 22003 - TokenPool is stealth pool initialised bit must be set
    #[error("TokenPool is stealth pool initialised bit must be set")]
    TokenPoolIsStealthPoolInitialisedBitMustBeSet = 0x55F3,
    /// 22004 - TokenPool is confidential pool initialised bit must be set
    #[error("TokenPool is confidential pool initialised bit must be set")]
    TokenPoolIsConfidentialPoolInitialisedBitMustBeSet = 0x55F4,
    /// 22005 - TokenPool is initialised bit must not be set
    #[error("TokenPool is initialised bit must not be set")]
    TokenPoolIsInitialisedBitMustNotBeSet = 0x55F5,
    /// 22006 - TokenPool is confidential pool active bit must not be set
    #[error("TokenPool is confidential pool active bit must not be set")]
    TokenPoolIsConfidentialPoolActiveBitMustNotBeSet = 0x55F6,
    /// 22007 - TokenPool is stealth pool active bit must not be set
    #[error("TokenPool is stealth pool active bit must not be set")]
    TokenPoolIsStealthPoolActiveBitMustNotBeSet = 0x55F7,
    /// 22008 - TokenPool is stealth pool initialised bit must not be set
    #[error("TokenPool is stealth pool initialised bit must not be set")]
    TokenPoolIsStealthPoolInitialisedBitMustNotBeSet = 0x55F8,
    /// 22009 - TokenPool is confidential pool initialised bit must not be set
    #[error("TokenPool is confidential pool initialised bit must not be set")]
    TokenPoolIsConfidentialPoolInitialisedBitMustNotBeSet = 0x55F9,
    /// 22010 - TokenPool is migration in progress bit must be set
    #[error("TokenPool is migration in progress bit must be set")]
    TokenPoolIsMigrationInProgressBitMustBeSet = 0x55FA,
    /// 22011 - TokenPool is migration in progress bit must not be set
    #[error("TokenPool is migration in progress bit must not be set")]
    TokenPoolIsMigrationInProgressBitMustNotBeSet = 0x55FB,
    /// 22012 - TokenPool stealth pool has not been previously initialised
    #[error("TokenPool stealth pool has not been previously initialised")]
    TokenPoolMixerHasNotBeenPreviouslyInitialised = 0x55FC,
    /// 22013 - Cannot uninitialise confidential pool once initialised
    #[error("Cannot uninitialise confidential pool once initialised")]
    CannotUninitialiseConfidentialPool = 0x55FD,
    /// 22014 - Cannot uninitialise stealth pool once initialised
    #[error("Cannot uninitialise stealth pool once initialised")]
    CannotUninitialiseStealthPool = 0x55FE,
    /// 22015 - Cannot modify non-active status bits via update instruction
    #[error("Cannot modify non-active status bits via update instruction")]
    CannotModifyNonActiveBits = 0x55FF,
    /// 22016 - Cannot activate confidential pool before it is initialized
    #[error("Cannot activate confidential pool before it is initialized")]
    CannotActivateUninitializedConfidentialPool = 0x5600,
    /// 22017 - Cannot activate stealth pool before it is initialized
    #[error("Cannot activate stealth pool before it is initialized")]
    CannotActivateUninitializedStealthPool = 0x5601,
    /// 22500 - Relayer account is initialised bit must be set
    #[error("Relayer account is initialised bit must be set")]
    RelayerIsInitialisedBitMustBeSet = 0x57E4,
    /// 22501 - Relayer account is active bit must be set
    #[error("Relayer account is active bit must be set")]
    RelayerIsActiveBitMustBeSet = 0x57E5,
    /// 22502 - Relayer account is transaction data to be used bit must be set
    #[error("Relayer account is transaction data to be used bit must be set")]
    RelayerIsTransactionDataToBeUsedBitMustBeSet = 0x57E6,
    /// 22503 - Relayer account is initialised bit must not be set
    #[error("Relayer account is initialised bit must not be set")]
    RelayerIsInitialisedBitMustNotBeSet = 0x57E7,
    /// 22504 - Relayer account is active bit must not be set
    #[error("Relayer account is active bit must not be set")]
    RelayerIsActiveBitMustNotBeSet = 0x57E8,
    /// 22505 - Relayer account is transaction data to be used bit must not be set
    #[error("Relayer account is transaction data to be used bit must not be set")]
    RelayerIsTransactionDataToBeUsedBitMustNotBeSet = 0x57E9,
    /// 22520 - Relayer fees pool is initialised bit must be set
    #[error("Relayer fees pool is initialised bit must be set")]
    RelayerFeesPoolIsInitialisedBitMustBeSet = 0x57F8,
    /// 22521 - Relayer fees pool is active bit must be set
    #[error("Relayer fees pool is active bit must be set")]
    RelayerFeesPoolIsActiveBitMustBeSet = 0x57F9,
    /// 22522 - Relayer fees pool is transaction data to be used bit must be set
    #[error("Relayer fees pool is transaction data to be used bit must be set")]
    RelayerFeesPoolIsTransactionDataToBeUsedBitMustBeSet = 0x57FA,
    /// 22523 - Relayer fees pool is initialised bit must not be set
    #[error("Relayer fees pool is initialised bit must not be set")]
    RelayerFeesPoolIsInitialisedBitMustNotBeSet = 0x57FB,
    /// 22524 - Relayer fees pool is active bit must not be set
    #[error("Relayer fees pool is active bit must not be set")]
    RelayerFeesPoolIsActiveBitMustNotBeSet = 0x57FC,
    /// 22525 - Relayer fees pool is transaction data to be used bit must not be set
    #[error("Relayer fees pool is transaction data to be used bit must not be set")]
    RelayerFeesPoolIsTransactionDataToBeUsedBitMustNotBeSet = 0x57FD,
    /// 22526 - Relayer fees pool is encrypted balance initialised bit must be set
    #[error("Relayer fees pool is encrypted balance initialised bit must be set")]
    RelayerFeesPoolIsEncryptedBalanceInitialisedBitMustBeSet = 0x57FE,
    /// 22527 - Relayer fees pool is encrypted balance initialised bit must not be set
    #[error("Relayer fees pool is encrypted balance initialised bit must not be set")]
    RelayerFeesPoolIsEncryptedBalanceInitialisedBitMustNotBeSet = 0x57FF,
    /// 22600 - Unified fees pool is initialised bit must be set
    #[error("Unified fees pool is initialised bit must be set")]
    FeeVaultIsInitialisedBitMustBeSet = 0x5848,
    /// 22601 - Unified fees pool is active bit must be set
    #[error("Unified fees pool is active bit must be set")]
    FeeVaultIsActiveBitMustBeSet = 0x5849,
    /// 22602 - Unified fees pool is encrypted balance initialised bit must be set
    #[error("Unified fees pool is encrypted balance initialised bit must be set")]
    FeeVaultIsEncryptedBalanceInitialisedBitMustBeSet = 0x584A,
    /// 22603 - Unified fees pool is initialised bit must not be set
    #[error("Unified fees pool is initialised bit must not be set")]
    FeeVaultIsInitialisedBitMustNotBeSet = 0x584B,
    /// 22604 - Unified fees pool is active bit must not be set
    #[error("Unified fees pool is active bit must not be set")]
    FeeVaultIsActiveBitMustNotBeSet = 0x584C,
    /// 22605 - Unified fees pool is encrypted balance initialised bit must not be set
    #[error("Unified fees pool is encrypted balance initialised bit must not be set")]
    FeeVaultIsEncryptedBalanceInitialisedBitMustNotBeSet = 0x584D,
    /// 22606 - Invalid unified fees pool account address
    #[error("Invalid unified fees pool account address")]
    InvalidFeeVaultAccountAddress = 0x584E,
    /// 22607 - Unified fees pool total-volume-transferred ciphertext must be initialised before this instruction can run
    #[error("Unified fees pool total-volume-transferred ciphertext must be initialised before this instruction can run")]
    FeeVaultTotalVolumeNotInitialised = 0x584F,
    /// 22608 - Unified fees pool total-volume-transferred ciphertext is already initialised
    #[error("Unified fees pool total-volume-transferred ciphertext is already initialised")]
    FeeVaultTotalVolumeAlreadyInitialised = 0x5850,
    /// 22609 - Unified fees pool is total volume initialised bit must be set
    #[error("Unified fees pool is total volume initialised bit must be set")]
    FeeVaultIsTotalVolumeInitialisedBitMustBeSet = 0x5851,
    /// 22610 - Unified fees pool is total volume initialised bit must not be set
    #[error("Unified fees pool is total volume initialised bit must not be set")]
    FeeVaultIsTotalVolumeInitialisedBitMustNotBeSet = 0x5852,
    /// 22611 - FeeVault has already been migrated to the new layout
    #[error("FeeVault has already been migrated to the new layout")]
    FeeVaultAlreadyMigrated = 0x5853,
    /// 22612 - FeeVault has an unexpected pre-migration size
    #[error("FeeVault has an unexpected pre-migration size")]
    FeeVaultInvalidPreMigrationSize = 0x5854,
    /// 23000 - Program information is initialised bit must be set
    #[error("Program information is initialised bit must be set")]
    ProtocolConfigIsInitialisedBitMustBeSet = 0x59D8,
    /// 23001 - Program information is active bit must be set
    #[error("Program information is active bit must be set")]
    ProtocolConfigIsActiveBitMustBeSet = 0x59D9,
    /// 23002 - Program information is initialised bit must not be set
    #[error("Program information is initialised bit must not be set")]
    ProtocolConfigIsInitialisedBitMustNotBeSet = 0x59DA,
    /// 23003 - Program information is active bit must not be set
    #[error("Program information is active bit must not be set")]
    ProtocolConfigIsActiveBitMustNotBeSet = 0x59DB,
    /// 23004 - ProtocolConfig has already been migrated to the v0.1.1+ layout
    #[error("ProtocolConfig has already been migrated to the v0.1.1+ layout")]
    ProtocolConfigAlreadyMigrated = 0x59DC,
    /// 23005 - ProtocolConfig has an unexpected pre-migration size
    #[error("ProtocolConfig has an unexpected pre-migration size")]
    ProtocolConfigInvalidPreMigrationSize = 0x59DD,
    /// 23400 - Lottery config is initialised bit must be set
    #[error("Lottery config is initialised bit must be set")]
    LotteryConfigIsInitialisedBitMustBeSet = 0x5B68,
    /// 23401 - Lottery config is active bit must be set
    #[error("Lottery config is active bit must be set")]
    LotteryConfigIsActiveBitMustBeSet = 0x5B69,
    /// 23402 - Lottery config is initialised bit must not be set
    #[error("Lottery config is initialised bit must not be set")]
    LotteryConfigIsInitialisedBitMustNotBeSet = 0x5B6A,
    /// 23403 - Lottery config is active bit must not be set
    #[error("Lottery config is active bit must not be set")]
    LotteryConfigIsActiveBitMustNotBeSet = 0x5B6B,
    /// 23500 - NETWORK X25519 key is initialised bit must be set
    #[error("NETWORK X25519 key is initialised bit must be set")]
    NetworkKeyIsInitialisedBitMustBeSet = 0x5BCC,
    /// 23501 - NETWORK X25519 key is initialised bit must not be set
    #[error("NETWORK X25519 key is initialised bit must not be set")]
    NetworkKeyIsInitialisedBitMustNotBeSet = 0x5BCD,
    /// 24000 - Wallet specifier is initialised bit must be set
    #[error("Wallet specifier is initialised bit must be set")]
    AdminWalletIsInitialisedBitMustBeSet = 0x5DC0,
    /// 24001 - Wallet specifier is initialised bit must not be set
    #[error("Wallet specifier is initialised bit must not be set")]
    AdminWalletIsInitialisedBitMustNotBeSet = 0x5DC1,
    /// 24002 - Instruction must be the only instruction in the transaction
    #[error("Instruction must be the only instruction in the transaction")]
    MustBeOnlyInstruction = 0x5DC2,
    /// 24003 - Cannot use INITIALISE_WALLET_SPECIFIER_SEED with this instruction
    #[error("Cannot use INITIALISE_WALLET_SPECIFIER_SEED with this instruction")]
    CannotUseInitialiseWalletSpecifierSeed = 0x5DC3,
    /// 25000 - Arcium default cluster not set
    #[error("Arcium default cluster not set")]
    ArciumDefaultClusterNotSet = 0x61A8,
    /// 27000 - The provided key already exists in the Treap
    #[error("The provided key already exists in the Treap")]
    DuplicateKey = 0x6978,
    /// 27001 - Account owner is invalid
    #[error("Account owner is invalid")]
    InvalidOwner = 0x6979,
    /// 27002 - Account is not writable
    #[error("Account is not writable")]
    AccountNotWritable = 0x697A,
    /// 27003 - Account does not contain enough data
    #[error("Account does not contain enough data")]
    AccountTooSmall = 0x697B,
    /// 27004 - Count overflow
    #[error("Count overflow")]
    OverflowCount = 0x697C,
    /// 27005 - Account data is not properly aligned (8-byte alignment required)
    #[error("Account data is not properly aligned (8-byte alignment required)")]
    MemoryAlignmentError = 0x697D,
    /// 27006 - Tree depth exceeded limit (potential cycle or attack)
    #[error("Tree depth exceeded limit (potential cycle or attack)")]
    MaxDepthExceeded = 0x697E,
    /// 27007 - Nullifier set header or structure is corrupted
    #[error("Nullifier set header or structure is corrupted")]
    TreeCorrupted = 0x697F,
    /// 27008 - Bytemuck conversion failed (size or alignment mismatch)
    #[error("Bytemuck conversion failed (size or alignment mismatch)")]
    BytemuckConversionError = 0x6980,
    /// 27009 - Invalid nullifier set account address
    #[error("Invalid nullifier set account address")]
    InvalidNullifierSetAccountAddress = 0x6981,
    /// 27010 - Invalid nullifier storing account address
    #[error("Invalid nullifier storing account address")]
    InvalidNullifierStoringAccount = 0x6982,
    /// 27100 - Nullifier set account is not initialized
    #[error("Nullifier set account is not initialized")]
    NullifierSetNotInitialized = 0x69DC,
    /// 27101 - Nullifier set account is already initialized
    #[error("Nullifier set account is already initialized")]
    NullifierSetAlreadyInitialized = 0x69DD,
    /// 27102 - Nullifier set is at full capacity
    #[error("Nullifier set is at full capacity")]
    TreapCapacityExceeded = 0x69DE,
    /// 27103 - Nullifier set has reached maximum capacity of 218,452 nullifiers
    #[error("Nullifier set has reached maximum capacity of 218,452 nullifiers")]
    TreapMaxNullifiersReached = 0x69DF,
    /// 27104 - Nullifier set account size exceeds Solana's 10 MB limit
    #[error("Nullifier set account size exceeds Solana's 10 MB limit")]
    TreapExceedsMaximumSize = 0x69E0,
    /// 27105 - Invalid number of nullifiers: must be greater than 0
    #[error("Invalid number of nullifiers: must be greater than 0")]
    InvalidNumberOfNullifiers = 0x69E1,
    /// 27110 - Nullifier set account is program-owned but in an unexpected uninitialized state
    #[error("Nullifier set account is program-owned but in an unexpected uninitialized state")]
    NullifierSetAccountInUnexpectedUninitializedState = 0x69E6,
    /// 28000 - Merkle tree insertion index overflow
    #[error("Merkle tree insertion index overflow")]
    InsertionIndexOverflow = 0x6D60,
    /// 28001 - Unable to hash input for Merkle tree
    #[error("Unable to hash input for Merkle tree")]
    UnableToHashInput = 0x6D61,
    /// 28002 - Migration in progress
    #[error("Migration in progress")]
    MigrationInProgress = 0x6D62,
    /// 28003 - Invalid Merkle root
    #[error("Invalid Merkle root")]
    InvalidMerkleRoot = 0x6D63,
    /// 28004 - Nullifier already burnt
    #[error("Nullifier already burnt")]
    NullifierAlreadyBurnt = 0x6D64,
    /// 28005 - Nullifier and linker buffer must be initialised
    #[error("Nullifier and linker buffer must be initialised")]
    NullifierAndLinkerBufferAccountMustBeInitialised = 0x6D65,
    /// 28006 - Nullifier and linker buffer must be active
    #[error("Nullifier and linker buffer must be active")]
    NullifierAndLinkerBufferAccountMustBeActive = 0x6D66,
    /// 28007 - Nullifier insertion index must be equal to commitment index insertion index
    #[error("Nullifier insertion index must be equal to commitment index insertion index")]
    NullifierInsertionIndexMustBeEqualToCommitmentIndexInsertionIndex = 0x6D67,
    /// 28008 - Nullifier and linker buffer must not be being used for claim
    #[error("Nullifier and linker buffer must not be being used for claim")]
    NullifierAndLinkerBufferAccountMustNotBeBeingUsedForClaim = 0x6D68,
    /// 28009 - StealthPool is initialised bit must be set
    #[error("StealthPool is initialised bit must be set")]
    StealthPoolIsInitialisedBitMustBeSet = 0x6D69,
    /// 28010 - StealthPool is stealth pool initialised bit must be set
    #[error("StealthPool is stealth pool initialised bit must be set")]
    StealthPoolIsStealthPoolInitialisedBitMustBeSet = 0x6D6A,
    /// 28011 - StealthPool is stealth pool active bit must be set
    #[error("StealthPool is stealth pool active bit must be set")]
    StealthPoolIsStealthPoolActiveBitMustBeSet = 0x6D6B,
    /// 28012 - Groth16VerifyingKey is initialised bit must be set
    #[error("Groth16VerifyingKey is initialised bit must be set")]
    Groth16VerifyingKeyIsInitialisedBitMustBeSet = 0x6D6C,
    /// 28013 - Groth16VerifyingKey is active bit must be set
    #[error("Groth16VerifyingKey is active bit must be set")]
    Groth16VerifyingKeyIsActiveBitMustBeSet = 0x6D6D,
    /// 28014 - NullifierAndLinkerBufferAccount is initialised bit must be set
    #[error("NullifierAndLinkerBufferAccount is initialised bit must be set")]
    NullifierAndLinkerBufferAccountIsInitialisedBitMustBeSet = 0x6D6E,
    /// 28015 - NullifierAndLinkerBufferAccount is active bit must be set
    #[error("NullifierAndLinkerBufferAccount is active bit must be set")]
    NullifierAndLinkerBufferAccountIsActiveBitMustBeSet = 0x6D6F,
    /// 28016 - StealthPool must be initialised
    #[error("StealthPool must be initialised")]
    StealthPoolMustBeInitialised = 0x6D70,
    /// 28017 - StealthPool is not full
    #[error("StealthPool is not full")]
    StealthPoolNotFull = 0x6D71,
    /// 28018 - Maximum number of stealth pools reached
    #[error("Maximum number of stealth pools reached")]
    MaxStealthPoolsReached = 0x6D72,
    /// 28019 - Current stealth pool is not active
    #[error("Current stealth pool is not active")]
    CurrentStealthPoolNotActive = 0x6D73,
    /// 28020 - StealthPool already exists
    #[error("StealthPool already exists")]
    MixerTreeAlreadyExists = 0x6D74,
    /// 28021 - StealthPool not initialised
    #[error("StealthPool not initialised")]
    MixerTreeNotInitialised = 0x6D75,
    /// 28022 - Invalid unspent transaction output insert count: must be 1 or 2
    #[error("Invalid unspent transaction output insert count: must be 1 or 2")]
    InvalidUnspentTransactionOutputInsertCount = 0x6D76,
    /// 28023 - Nullifier and linker buffer slot is already occupied
    #[error("Nullifier and linker buffer slot is already occupied")]
    NullifierAndLinkerBufferSlotAlreadyOccupied = 0x6D77,
    /// 28024 - New incremental merkle tree index does not match expected value
    #[error("New incremental merkle tree index does not match expected value")]
    InvalidNewIncrementalMerkleTreeIndex = 0x6D78,
    /// 28025 - Cannot uninitialise stealth pool
    #[error("Cannot uninitialise stealth pool")]
    CannotUninitialiseStealthPoolAccount = 0x6D79,
    /// 28026 - Cannot modify non-active stealth pool bits
    #[error("Cannot modify non-active stealth pool bits")]
    CannotModifyNonActiveStealthPoolBits = 0x6D7A,
    /// 28027 - Cannot activate uninitialized stealth pool
    #[error("Cannot activate uninitialized stealth pool")]
    CannotActivateUninitializedStealthPoolAccount = 0x6D7B,
    /// 28028 - Incremental merkle tree index exceeds currently active incremental merkle tree index
    #[error("Incremental merkle tree index exceeds currently active incremental merkle tree index")]
    IncrementalMerkleTreeIndexExceedsCurrentlyActiveIncrementalMerkleTreeIndex = 0x6D7C,
    /// 28029 - Only the initial stealth pool (index 0) can be initialized via initialise_stealth_pool_state_tree
    #[error("Only the initial stealth pool (index 0) can be initialized via initialise_stealth_pool_state_tree")]
    OnlyInitialStealthPoolCanBeInitialized = 0x6D7D,
    /// 28030 - Mixer tree index exceeds the index of the currently active stealth pool
    #[error("Mixer tree index exceeds the index of the currently active stealth pool")]
    InvalidMixerTreeIndex = 0x6D7E,
    /// 28050 - Groth16VerifyingKey is active bit must not be set
    #[error("Groth16VerifyingKey is active bit must not be set")]
    Groth16VerifyingKeyIsActiveBitMustNotBeSet = 0x6D92,
    /// 29000 - Sender user account is invalid for transfer
    #[error("Sender user account is invalid for transfer")]
    SenderUserAccountInvalid = 0x7148,
    /// 29001 - Receiver user account is invalid for transfer
    #[error("Receiver user account is invalid for transfer")]
    ReceiverUserAccountInvalid = 0x7149,
    /// 29002 - Cannot transfer to self
    #[error("Cannot transfer to self")]
    CannotTransferToSelf = 0x714A,
    /// 29003 - Invalid receiver address
    #[error("Invalid receiver address")]
    InvalidReceiverAddress = 0x714B,
    /// 29004 - Invalid protocol fees configuration account
    #[error("Invalid protocol fees configuration account")]
    InvalidProtocolFeesConfigurationAccount = 0x714C,
    /// 29005 - Invalid protocol fees pool account
    #[error("Invalid protocol fees pool account")]
    InvalidProtocolFeesPoolAccount = 0x714D,
    /// 29006 - Receiver user account is not initialised
    #[error("Receiver user account is not initialised")]
    ReceiverUserAccountNotInitialised = 0x714E,
    /// 29007 - Receiver token account is not initialised
    #[error("Receiver token account is not initialised")]
    ReceiverTokenAccountNotInitialised = 0x714F,
    /// 29008 - Receiver x25519 key is not registered
    #[error("Receiver x25519 key is not registered")]
    ReceiverX25519KeyNotRegistered = 0x7150,
    /// 29050 - Cannot transfer to self via the same token account PDA
    #[error("Cannot transfer to self via the same token account PDA")]
    CannotTransferToSelfTokenAccount = 0x717A,
    /// 29100 - Insufficient funds in encrypted balance for withdrawal
    #[error("Insufficient funds in encrypted balance for withdrawal")]
    InsufficientFunds = 0x71AC,
    /// 29101 - Insufficient liquidity in pool for withdrawal
    #[error("Insufficient liquidity in pool for withdrawal")]
    InsufficientPoolLiquidity = 0x71AD,
    /// 29102 - Insufficient balance in public fees for withdrawal
    #[error("Insufficient balance in public fees for withdrawal")]
    InsufficientBalance = 0x71AE,
    /// 29103 - Zero amount withdrawals are not allowed
    #[error("Zero amount withdrawals are not allowed")]
    ZeroAmountNotAllowed = 0x71AF,
    /// 29200 - Failed to convert byte slice to u64 array
    #[error("Failed to convert byte slice to u64 array")]
    ByteSliceToU64ConversionFailed = 0x7210,
    /// 29201 - Failed to convert byte slice to u128 array
    #[error("Failed to convert byte slice to u128 array")]
    ByteSliceToU128ConversionFailed = 0x7211,
    /// 29300 - Invalid nonce for new account - nonce does not match computed initialization nonce
    #[error("Invalid nonce for new account - nonce does not match computed initialization nonce")]
    InvalidNonceForNewAccount = 0x7274,
    /// 29301 - Invalid nonce for existing account - expected current_nonce + 1
    #[error("Invalid nonce for existing account - expected current_nonce + 1")]
    InvalidNonceForExistingAccount = 0x7275,
    /// 29302 - Nonce mismatch - account nonce changed between handler and callback
    #[error("Nonce mismatch - account nonce changed between handler and callback")]
    NonceMismatch = 0x7276,
    /// 29303 - Queued computation count exceeds the maximum allowed by protocol config
    #[error("Queued computation count exceeds the maximum allowed by protocol config")]
    QueuedComputationCountExceedsMaximum = 0x7277,
    /// 29304 - Queue reset slot threshold not met - not enough slots have passed since oldest pending computation
    #[error("Queue reset slot threshold not met - not enough slots have passed since oldest pending computation")]
    QueueResetSlotThresholdNotMet = 0x7278,
    /// 29305 - Queue is not stuck - queued computation count is zero, nothing to reset
    #[error("Queue is not stuck - queued computation count is zero, nothing to reset")]
    QueueNotStuck = 0x7279,
    /// 29310 - Cannot close or convert account while MPC computations are still queued
    #[error("Cannot close or convert account while MPC computations are still queued")]
    CannotCloseAccountWithPendingComputations = 0x727E,
    /// 29312 - Concurrent x25519 key rotation detected — pre-rotation snapshot does not match live key
    #[error("Concurrent x25519 key rotation detected — pre-rotation snapshot does not match live key")]
    ConcurrentRotationDetected = 0x7280,
    /// 29313 - computation_data TTL not elapsed — wait protocol_config.computation_data_expiry_slots after queue time
    #[error("computation_data TTL not elapsed — wait protocol_config.computation_data_expiry_slots after queue time")]
    ComputationDataExpiryNotElapsed = 0x7281,
    /// 29400 - NETWORK token accounts can only be created for users who have not registered an X25519 token key. Use Shared mode for users with X25519 token keys.
    #[error("NETWORK token accounts can only be created for users who have not registered an X25519 token key. Use Shared mode for users with X25519 token keys.")]
    NetworkAccountRequiresNoX25519Key = 0x72D8,
    /// 30002 - EncData output bytes are out of bounds of the MPC signed-output buffer
    #[error("EncData output bytes are out of bounds of the MPC signed-output buffer")]
    EncDataOutOfBounds = 0x7532,
    /// 30003 - Invalid offset supplied to EncData byte decoder
    #[error("Invalid offset supplied to EncData byte decoder")]
    InvalidEncDataOffset = 0x7533,
    /// 30100 - Observer-forward destination_program account does not match the value stored at queue time
    #[error("Observer-forward destination_program account does not match the value stored at queue time")]
    ObserverForwardDestinationMismatch = 0x7594,
    /// 30101 - Observer-forward cpi_account_1 does not match the value stored at queue time
    #[error("Observer-forward cpi_account_1 does not match the value stored at queue time")]
    ObserverForwardCpiAccount1Mismatch = 0x7595,
    /// 30103 - MXE x25519 pubkey is not set; cannot perform observer sentinel check
    #[error("MXE x25519 pubkey is not set; cannot perform observer sentinel check")]
    MxeX25519PubkeyNotSet = 0x7597,
}

impl From<UmbraError> for solana_program_error::ProgramError {
    fn from(e: UmbraError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

