//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::ClaimIntoPublicBalanceToMxeV13Output;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const CLAIM_INTO_PUBLIC_BALANCE_TO_MXE_V13_CALLBACK_DISCRIMINATOR: [u8; 8] = [67, 85, 184, 56, 201, 69, 151, 49];

/// Accounts.
#[derive(Debug)]
pub struct ClaimIntoPublicBalanceToMxeV13Callback {
      
              
          pub arcium_program: solana_pubkey::Pubkey,
          
              
          pub comp_def_account: solana_pubkey::Pubkey,
          
              
          pub mxe_account: solana_pubkey::Pubkey,
          
              
          pub computation_account: solana_pubkey::Pubkey,
          
              
          pub cluster_account: solana_pubkey::Pubkey,
          
              
          pub instructions_sysvar: solana_pubkey::Pubkey,
          
              
          pub relayer: solana_pubkey::Pubkey,
                /// computation_data and the manual lamport transfers (helper ATA rent +
/// nullifier_and_linker_buffer rent). Must match the fee_payer used at
/// queue time (Arcium passes the queued account through to the callback).

    
              
          pub fee_payer: solana_pubkey::Pubkey,
                /// (receives native SOL from unwrap), for other tokens this is the receiver's ATA.

    
              
          pub receiver_account: solana_pubkey::Pubkey,
          
              
          pub fee_vault: solana_pubkey::Pubkey,
          
              
          pub public_claim_nullifier_and_linker_buffer: solana_pubkey::Pubkey,
          
              
          pub nullifier_set1: solana_pubkey::Pubkey,
          
              
          pub nullifier_set2: solana_pubkey::Pubkey,
          
              
          pub nullifier_set3: solana_pubkey::Pubkey,
          
              
          pub nullifier_set4: solana_pubkey::Pubkey,
          
              
          pub nullifier_set5: solana_pubkey::Pubkey,
          
              
          pub token_pool: solana_pubkey::Pubkey,
          
              
          pub token_pool_ata: solana_pubkey::Pubkey,
          
              
          pub mint: solana_pubkey::Pubkey,
          
              
          pub token_program: solana_pubkey::Pubkey,
                /// MPC callback data account - stores all callback data (fees, amounts, pool_index, etc.).
/// Closed after callback, returning rent to fee_payer.

    
              
          pub computation_data: solana_pubkey::Pubkey,
                /// Helper ATA owned by `computation_data` PDA. For wrapped SOL withdrawals, tokens are
/// transferred here first, then the account is closed to unwrap wrapped SOL into native SOL
/// for the receiver. For non-wrapped SOL, this is closed immediately (empty).

    
              
          pub mpc_callback_wrapped_sol_unwrapping_helper_account: solana_pubkey::Pubkey,
      }

impl ClaimIntoPublicBalanceToMxeV13Callback {
  pub fn instruction(&self, args: ClaimIntoPublicBalanceToMxeV13CallbackInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: ClaimIntoPublicBalanceToMxeV13CallbackInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(22+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.arcium_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.comp_def_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mxe_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.computation_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.cluster_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.instructions_sysvar,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.relayer,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_payer,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.receiver_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_vault,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.public_claim_nullifier_and_linker_buffer,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set1,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set2,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set3,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set4,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set5,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.token_pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.token_pool_ata,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.computation_data,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.mpc_callback_wrapped_sol_unwrapping_helper_account,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = ClaimIntoPublicBalanceToMxeV13CallbackInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ClaimIntoPublicBalanceToMxeV13CallbackInstructionData {
            discriminator: [u8; 8],
            }

impl ClaimIntoPublicBalanceToMxeV13CallbackInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [67, 85, 184, 56, 201, 69, 151, 49],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for ClaimIntoPublicBalanceToMxeV13CallbackInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum ClaimIntoPublicBalanceToMxeV13CallbackOutput {
Success(ClaimIntoPublicBalanceToMxeV13Output, [u8; 64]),
Failure,
MarkerForIdlBuildDoNotUseThis(ClaimIntoPublicBalanceToMxeV13Output),
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ClaimIntoPublicBalanceToMxeV13CallbackInstructionArgs {
                  pub outputs: ClaimIntoPublicBalanceToMxeV13CallbackOutput,
      }

impl ClaimIntoPublicBalanceToMxeV13CallbackInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `ClaimIntoPublicBalanceToMxeV13Callback`.
///
/// ### Accounts:
///
                ///   0. `[optional]` arcium_program (default to `Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ`)
          ///   1. `[]` comp_def_account
          ///   2. `[]` mxe_account
          ///   3. `[]` computation_account
          ///   4. `[]` cluster_account
                ///   5. `[optional]` instructions_sysvar (default to `Sysvar1nstructions1111111111111111111111111`)
                ///   6. `[writable]` relayer
                ///   7. `[writable]` fee_payer
                ///   8. `[writable]` receiver_account
                ///   9. `[writable]` fee_vault
                ///   10. `[writable]` public_claim_nullifier_and_linker_buffer
                ///   11. `[writable]` nullifier_set1
                ///   12. `[writable]` nullifier_set2
                ///   13. `[writable]` nullifier_set3
                ///   14. `[writable]` nullifier_set4
                ///   15. `[writable]` nullifier_set5
                ///   16. `[writable]` token_pool
                ///   17. `[writable]` token_pool_ata
          ///   18. `[]` mint
                ///   19. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
                ///   20. `[writable]` computation_data
                ///   21. `[writable]` mpc_callback_wrapped_sol_unwrapping_helper_account
#[derive(Clone, Debug, Default)]
pub struct ClaimIntoPublicBalanceToMxeV13CallbackBuilder {
            arcium_program: Option<solana_pubkey::Pubkey>,
                comp_def_account: Option<solana_pubkey::Pubkey>,
                mxe_account: Option<solana_pubkey::Pubkey>,
                computation_account: Option<solana_pubkey::Pubkey>,
                cluster_account: Option<solana_pubkey::Pubkey>,
                instructions_sysvar: Option<solana_pubkey::Pubkey>,
                relayer: Option<solana_pubkey::Pubkey>,
                fee_payer: Option<solana_pubkey::Pubkey>,
                receiver_account: Option<solana_pubkey::Pubkey>,
                fee_vault: Option<solana_pubkey::Pubkey>,
                public_claim_nullifier_and_linker_buffer: Option<solana_pubkey::Pubkey>,
                nullifier_set1: Option<solana_pubkey::Pubkey>,
                nullifier_set2: Option<solana_pubkey::Pubkey>,
                nullifier_set3: Option<solana_pubkey::Pubkey>,
                nullifier_set4: Option<solana_pubkey::Pubkey>,
                nullifier_set5: Option<solana_pubkey::Pubkey>,
                token_pool: Option<solana_pubkey::Pubkey>,
                token_pool_ata: Option<solana_pubkey::Pubkey>,
                mint: Option<solana_pubkey::Pubkey>,
                token_program: Option<solana_pubkey::Pubkey>,
                computation_data: Option<solana_pubkey::Pubkey>,
                mpc_callback_wrapped_sol_unwrapping_helper_account: Option<solana_pubkey::Pubkey>,
                        outputs: Option<ClaimIntoPublicBalanceToMxeV13CallbackOutput>,
        __program_id: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ClaimIntoPublicBalanceToMxeV13CallbackBuilder {
  pub fn new() -> Self {
    Self::default()
  }
    /// Set a custom program ID for the instruction (overrides the default).
    /// Use this when targeting a different deployment (e.g. devnet vs mainnet).
    #[inline(always)]
    pub fn program_id(&mut self, program_id: solana_pubkey::Pubkey) -> &mut Self {
        self.__program_id = Some(program_id);
        self
    }
            /// `[optional account, default to 'Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ']`
#[inline(always)]
    pub fn arcium_program(&mut self, arcium_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.arcium_program = Some(arcium_program);
                    self
    }
            #[inline(always)]
    pub fn comp_def_account(&mut self, comp_def_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.comp_def_account = Some(comp_def_account);
                    self
    }
            #[inline(always)]
    pub fn mxe_account(&mut self, mxe_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.mxe_account = Some(mxe_account);
                    self
    }
            #[inline(always)]
    pub fn computation_account(&mut self, computation_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.computation_account = Some(computation_account);
                    self
    }
            #[inline(always)]
    pub fn cluster_account(&mut self, cluster_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.cluster_account = Some(cluster_account);
                    self
    }
            /// `[optional account, default to 'Sysvar1nstructions1111111111111111111111111']`
#[inline(always)]
    pub fn instructions_sysvar(&mut self, instructions_sysvar: solana_pubkey::Pubkey) -> &mut Self {
                        self.instructions_sysvar = Some(instructions_sysvar);
                    self
    }
            #[inline(always)]
    pub fn relayer(&mut self, relayer: solana_pubkey::Pubkey) -> &mut Self {
                        self.relayer = Some(relayer);
                    self
    }
            /// computation_data and the manual lamport transfers (helper ATA rent +
/// nullifier_and_linker_buffer rent). Must match the fee_payer used at
/// queue time (Arcium passes the queued account through to the callback).
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_payer = Some(fee_payer);
                    self
    }
            /// (receives native SOL from unwrap), for other tokens this is the receiver's ATA.
#[inline(always)]
    pub fn receiver_account(&mut self, receiver_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.receiver_account = Some(receiver_account);
                    self
    }
            #[inline(always)]
    pub fn fee_vault(&mut self, fee_vault: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_vault = Some(fee_vault);
                    self
    }
            #[inline(always)]
    pub fn public_claim_nullifier_and_linker_buffer(&mut self, public_claim_nullifier_and_linker_buffer: solana_pubkey::Pubkey) -> &mut Self {
                        self.public_claim_nullifier_and_linker_buffer = Some(public_claim_nullifier_and_linker_buffer);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set1(&mut self, nullifier_set1: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set1 = Some(nullifier_set1);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set2(&mut self, nullifier_set2: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set2 = Some(nullifier_set2);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set3(&mut self, nullifier_set3: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set3 = Some(nullifier_set3);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set4(&mut self, nullifier_set4: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set4 = Some(nullifier_set4);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set5(&mut self, nullifier_set5: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set5 = Some(nullifier_set5);
                    self
    }
            #[inline(always)]
    pub fn token_pool(&mut self, token_pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_pool = Some(token_pool);
                    self
    }
            #[inline(always)]
    pub fn token_pool_ata(&mut self, token_pool_ata: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_pool_ata = Some(token_pool_ata);
                    self
    }
            #[inline(always)]
    pub fn mint(&mut self, mint: solana_pubkey::Pubkey) -> &mut Self {
                        self.mint = Some(mint);
                    self
    }
            /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
#[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
            /// MPC callback data account - stores all callback data (fees, amounts, pool_index, etc.).
/// Closed after callback, returning rent to fee_payer.
#[inline(always)]
    pub fn computation_data(&mut self, computation_data: solana_pubkey::Pubkey) -> &mut Self {
                        self.computation_data = Some(computation_data);
                    self
    }
            /// Helper ATA owned by `computation_data` PDA. For wrapped SOL withdrawals, tokens are
/// transferred here first, then the account is closed to unwrap wrapped SOL into native SOL
/// for the receiver. For non-wrapped SOL, this is closed immediately (empty).
#[inline(always)]
    pub fn mpc_callback_wrapped_sol_unwrapping_helper_account(&mut self, mpc_callback_wrapped_sol_unwrapping_helper_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.mpc_callback_wrapped_sol_unwrapping_helper_account = Some(mpc_callback_wrapped_sol_unwrapping_helper_account);
                    self
    }
                    #[inline(always)]
      pub fn outputs(&mut self, outputs: ClaimIntoPublicBalanceToMxeV13CallbackOutput) -> &mut Self {
        self.outputs = Some(outputs);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = ClaimIntoPublicBalanceToMxeV13Callback {
                              arcium_program: self.arcium_program.unwrap_or(solana_pubkey::pubkey!("Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ")),
                                        comp_def_account: self.comp_def_account.expect("comp_def_account is not set"),
                                        mxe_account: self.mxe_account.expect("mxe_account is not set"),
                                        computation_account: self.computation_account.expect("computation_account is not set"),
                                        cluster_account: self.cluster_account.expect("cluster_account is not set"),
                                        instructions_sysvar: self.instructions_sysvar.unwrap_or(solana_pubkey::pubkey!("Sysvar1nstructions1111111111111111111111111")),
                                        relayer: self.relayer.expect("relayer is not set"),
                                        fee_payer: self.fee_payer.expect("fee_payer is not set"),
                                        receiver_account: self.receiver_account.expect("receiver_account is not set"),
                                        fee_vault: self.fee_vault.expect("fee_vault is not set"),
                                        public_claim_nullifier_and_linker_buffer: self.public_claim_nullifier_and_linker_buffer.expect("public_claim_nullifier_and_linker_buffer is not set"),
                                        nullifier_set1: self.nullifier_set1.expect("nullifier_set1 is not set"),
                                        nullifier_set2: self.nullifier_set2.expect("nullifier_set2 is not set"),
                                        nullifier_set3: self.nullifier_set3.expect("nullifier_set3 is not set"),
                                        nullifier_set4: self.nullifier_set4.expect("nullifier_set4 is not set"),
                                        nullifier_set5: self.nullifier_set5.expect("nullifier_set5 is not set"),
                                        token_pool: self.token_pool.expect("token_pool is not set"),
                                        token_pool_ata: self.token_pool_ata.expect("token_pool_ata is not set"),
                                        mint: self.mint.expect("mint is not set"),
                                        token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
                                        computation_data: self.computation_data.expect("computation_data is not set"),
                                        mpc_callback_wrapped_sol_unwrapping_helper_account: self.mpc_callback_wrapped_sol_unwrapping_helper_account.expect("mpc_callback_wrapped_sol_unwrapping_helper_account is not set"),
                      };
          let args = ClaimIntoPublicBalanceToMxeV13CallbackInstructionArgs {
                                                              outputs: self.outputs.clone().expect("outputs is not set"),
                                    };
    
    {
            let mut ix = accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts);
            if let Some(program_id) = self.__program_id {
                ix.program_id = program_id;
            }
            ix
        }
  }
}

  /// `claim_into_public_balance_to_mxe_v13_callback` CPI accounts.
  pub struct ClaimIntoPublicBalanceToMxeV13CallbackCpiAccounts<'a, 'b> {
          
                    
              pub arcium_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub comp_def_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mxe_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub computation_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cluster_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub instructions_sysvar: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub relayer: &'b solana_account_info::AccountInfo<'a>,
                        /// computation_data and the manual lamport transfers (helper ATA rent +
/// nullifier_and_linker_buffer rent). Must match the fee_payer used at
/// queue time (Arcium passes the queued account through to the callback).

      
                    
              pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                        /// (receives native SOL from unwrap), for other tokens this is the receiver's ATA.

      
                    
              pub receiver_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub fee_vault: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub public_claim_nullifier_and_linker_buffer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set1: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set2: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set3: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set4: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set5: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_pool: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_pool_ata: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mint: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_account_info::AccountInfo<'a>,
                        /// MPC callback data account - stores all callback data (fees, amounts, pool_index, etc.).
/// Closed after callback, returning rent to fee_payer.

      
                    
              pub computation_data: &'b solana_account_info::AccountInfo<'a>,
                        /// Helper ATA owned by `computation_data` PDA. For wrapped SOL withdrawals, tokens are
/// transferred here first, then the account is closed to unwrap wrapped SOL into native SOL
/// for the receiver. For non-wrapped SOL, this is closed immediately (empty).

      
                    
              pub mpc_callback_wrapped_sol_unwrapping_helper_account: &'b solana_account_info::AccountInfo<'a>,
            }

/// `claim_into_public_balance_to_mxe_v13_callback` CPI instruction.
pub struct ClaimIntoPublicBalanceToMxeV13CallbackCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub arcium_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub comp_def_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mxe_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub computation_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cluster_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub instructions_sysvar: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub relayer: &'b solana_account_info::AccountInfo<'a>,
                /// computation_data and the manual lamport transfers (helper ATA rent +
/// nullifier_and_linker_buffer rent). Must match the fee_payer used at
/// queue time (Arcium passes the queued account through to the callback).

    
              
          pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                /// (receives native SOL from unwrap), for other tokens this is the receiver's ATA.

    
              
          pub receiver_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub fee_vault: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub public_claim_nullifier_and_linker_buffer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set1: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set2: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set3: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set4: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set5: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_pool: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_pool_ata: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mint: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_account_info::AccountInfo<'a>,
                /// MPC callback data account - stores all callback data (fees, amounts, pool_index, etc.).
/// Closed after callback, returning rent to fee_payer.

    
              
          pub computation_data: &'b solana_account_info::AccountInfo<'a>,
                /// Helper ATA owned by `computation_data` PDA. For wrapped SOL withdrawals, tokens are
/// transferred here first, then the account is closed to unwrap wrapped SOL into native SOL
/// for the receiver. For non-wrapped SOL, this is closed immediately (empty).

    
              
          pub mpc_callback_wrapped_sol_unwrapping_helper_account: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: ClaimIntoPublicBalanceToMxeV13CallbackInstructionArgs,
  }

impl<'a, 'b> ClaimIntoPublicBalanceToMxeV13CallbackCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: ClaimIntoPublicBalanceToMxeV13CallbackCpiAccounts<'a, 'b>,
              args: ClaimIntoPublicBalanceToMxeV13CallbackInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              arcium_program: accounts.arcium_program,
              comp_def_account: accounts.comp_def_account,
              mxe_account: accounts.mxe_account,
              computation_account: accounts.computation_account,
              cluster_account: accounts.cluster_account,
              instructions_sysvar: accounts.instructions_sysvar,
              relayer: accounts.relayer,
              fee_payer: accounts.fee_payer,
              receiver_account: accounts.receiver_account,
              fee_vault: accounts.fee_vault,
              public_claim_nullifier_and_linker_buffer: accounts.public_claim_nullifier_and_linker_buffer,
              nullifier_set1: accounts.nullifier_set1,
              nullifier_set2: accounts.nullifier_set2,
              nullifier_set3: accounts.nullifier_set3,
              nullifier_set4: accounts.nullifier_set4,
              nullifier_set5: accounts.nullifier_set5,
              token_pool: accounts.token_pool,
              token_pool_ata: accounts.token_pool_ata,
              mint: accounts.mint,
              token_program: accounts.token_program,
              computation_data: accounts.computation_data,
              mpc_callback_wrapped_sol_unwrapping_helper_account: accounts.mpc_callback_wrapped_sol_unwrapping_helper_account,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(22+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.arcium_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.comp_def_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mxe_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.computation_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.cluster_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.instructions_sysvar.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.relayer.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_payer.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.receiver_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_vault.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.public_claim_nullifier_and_linker_buffer.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set1.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set2.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set3.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set4.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set5.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.token_pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.token_pool_ata.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.computation_data.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.mpc_callback_wrapped_sol_unwrapping_helper_account.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = ClaimIntoPublicBalanceToMxeV13CallbackInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(23 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.arcium_program.clone());
                        account_infos.push(self.comp_def_account.clone());
                        account_infos.push(self.mxe_account.clone());
                        account_infos.push(self.computation_account.clone());
                        account_infos.push(self.cluster_account.clone());
                        account_infos.push(self.instructions_sysvar.clone());
                        account_infos.push(self.relayer.clone());
                        account_infos.push(self.fee_payer.clone());
                        account_infos.push(self.receiver_account.clone());
                        account_infos.push(self.fee_vault.clone());
                        account_infos.push(self.public_claim_nullifier_and_linker_buffer.clone());
                        account_infos.push(self.nullifier_set1.clone());
                        account_infos.push(self.nullifier_set2.clone());
                        account_infos.push(self.nullifier_set3.clone());
                        account_infos.push(self.nullifier_set4.clone());
                        account_infos.push(self.nullifier_set5.clone());
                        account_infos.push(self.token_pool.clone());
                        account_infos.push(self.token_pool_ata.clone());
                        account_infos.push(self.mint.clone());
                        account_infos.push(self.token_program.clone());
                        account_infos.push(self.computation_data.clone());
                        account_infos.push(self.mpc_callback_wrapped_sol_unwrapping_helper_account.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `ClaimIntoPublicBalanceToMxeV13Callback` via CPI.
///
/// ### Accounts:
///
          ///   0. `[]` arcium_program
          ///   1. `[]` comp_def_account
          ///   2. `[]` mxe_account
          ///   3. `[]` computation_account
          ///   4. `[]` cluster_account
          ///   5. `[]` instructions_sysvar
                ///   6. `[writable]` relayer
                ///   7. `[writable]` fee_payer
                ///   8. `[writable]` receiver_account
                ///   9. `[writable]` fee_vault
                ///   10. `[writable]` public_claim_nullifier_and_linker_buffer
                ///   11. `[writable]` nullifier_set1
                ///   12. `[writable]` nullifier_set2
                ///   13. `[writable]` nullifier_set3
                ///   14. `[writable]` nullifier_set4
                ///   15. `[writable]` nullifier_set5
                ///   16. `[writable]` token_pool
                ///   17. `[writable]` token_pool_ata
          ///   18. `[]` mint
          ///   19. `[]` token_program
                ///   20. `[writable]` computation_data
                ///   21. `[writable]` mpc_callback_wrapped_sol_unwrapping_helper_account
#[derive(Clone, Debug)]
pub struct ClaimIntoPublicBalanceToMxeV13CallbackCpiBuilder<'a, 'b> {
  instruction: Box<ClaimIntoPublicBalanceToMxeV13CallbackCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ClaimIntoPublicBalanceToMxeV13CallbackCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(ClaimIntoPublicBalanceToMxeV13CallbackCpiBuilderInstruction {
      __program: program,
              arcium_program: None,
              comp_def_account: None,
              mxe_account: None,
              computation_account: None,
              cluster_account: None,
              instructions_sysvar: None,
              relayer: None,
              fee_payer: None,
              receiver_account: None,
              fee_vault: None,
              public_claim_nullifier_and_linker_buffer: None,
              nullifier_set1: None,
              nullifier_set2: None,
              nullifier_set3: None,
              nullifier_set4: None,
              nullifier_set5: None,
              token_pool: None,
              token_pool_ata: None,
              mint: None,
              token_program: None,
              computation_data: None,
              mpc_callback_wrapped_sol_unwrapping_helper_account: None,
                                            outputs: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn arcium_program(&mut self, arcium_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.arcium_program = Some(arcium_program);
                    self
    }
      #[inline(always)]
    pub fn comp_def_account(&mut self, comp_def_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.comp_def_account = Some(comp_def_account);
                    self
    }
      #[inline(always)]
    pub fn mxe_account(&mut self, mxe_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mxe_account = Some(mxe_account);
                    self
    }
      #[inline(always)]
    pub fn computation_account(&mut self, computation_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.computation_account = Some(computation_account);
                    self
    }
      #[inline(always)]
    pub fn cluster_account(&mut self, cluster_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cluster_account = Some(cluster_account);
                    self
    }
      #[inline(always)]
    pub fn instructions_sysvar(&mut self, instructions_sysvar: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.instructions_sysvar = Some(instructions_sysvar);
                    self
    }
      #[inline(always)]
    pub fn relayer(&mut self, relayer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.relayer = Some(relayer);
                    self
    }
      /// computation_data and the manual lamport transfers (helper ATA rent +
/// nullifier_and_linker_buffer rent). Must match the fee_payer used at
/// queue time (Arcium passes the queued account through to the callback).
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_payer = Some(fee_payer);
                    self
    }
      /// (receives native SOL from unwrap), for other tokens this is the receiver's ATA.
#[inline(always)]
    pub fn receiver_account(&mut self, receiver_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.receiver_account = Some(receiver_account);
                    self
    }
      #[inline(always)]
    pub fn fee_vault(&mut self, fee_vault: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_vault = Some(fee_vault);
                    self
    }
      #[inline(always)]
    pub fn public_claim_nullifier_and_linker_buffer(&mut self, public_claim_nullifier_and_linker_buffer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.public_claim_nullifier_and_linker_buffer = Some(public_claim_nullifier_and_linker_buffer);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set1(&mut self, nullifier_set1: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set1 = Some(nullifier_set1);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set2(&mut self, nullifier_set2: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set2 = Some(nullifier_set2);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set3(&mut self, nullifier_set3: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set3 = Some(nullifier_set3);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set4(&mut self, nullifier_set4: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set4 = Some(nullifier_set4);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set5(&mut self, nullifier_set5: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set5 = Some(nullifier_set5);
                    self
    }
      #[inline(always)]
    pub fn token_pool(&mut self, token_pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_pool = Some(token_pool);
                    self
    }
      #[inline(always)]
    pub fn token_pool_ata(&mut self, token_pool_ata: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_pool_ata = Some(token_pool_ata);
                    self
    }
      #[inline(always)]
    pub fn mint(&mut self, mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mint = Some(mint);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
      /// MPC callback data account - stores all callback data (fees, amounts, pool_index, etc.).
/// Closed after callback, returning rent to fee_payer.
#[inline(always)]
    pub fn computation_data(&mut self, computation_data: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.computation_data = Some(computation_data);
                    self
    }
      /// Helper ATA owned by `computation_data` PDA. For wrapped SOL withdrawals, tokens are
/// transferred here first, then the account is closed to unwrap wrapped SOL into native SOL
/// for the receiver. For non-wrapped SOL, this is closed immediately (empty).
#[inline(always)]
    pub fn mpc_callback_wrapped_sol_unwrapping_helper_account(&mut self, mpc_callback_wrapped_sol_unwrapping_helper_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mpc_callback_wrapped_sol_unwrapping_helper_account = Some(mpc_callback_wrapped_sol_unwrapping_helper_account);
                    self
    }
                    #[inline(always)]
      pub fn outputs(&mut self, outputs: ClaimIntoPublicBalanceToMxeV13CallbackOutput) -> &mut Self {
        self.instruction.outputs = Some(outputs);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = ClaimIntoPublicBalanceToMxeV13CallbackInstructionArgs {
                                                              outputs: self.instruction.outputs.clone().expect("outputs is not set"),
                                    };
        let instruction = ClaimIntoPublicBalanceToMxeV13CallbackCpi {
        __program: self.instruction.__program,
                  
          arcium_program: self.instruction.arcium_program.expect("arcium_program is not set"),
                  
          comp_def_account: self.instruction.comp_def_account.expect("comp_def_account is not set"),
                  
          mxe_account: self.instruction.mxe_account.expect("mxe_account is not set"),
                  
          computation_account: self.instruction.computation_account.expect("computation_account is not set"),
                  
          cluster_account: self.instruction.cluster_account.expect("cluster_account is not set"),
                  
          instructions_sysvar: self.instruction.instructions_sysvar.expect("instructions_sysvar is not set"),
                  
          relayer: self.instruction.relayer.expect("relayer is not set"),
                  
          fee_payer: self.instruction.fee_payer.expect("fee_payer is not set"),
                  
          receiver_account: self.instruction.receiver_account.expect("receiver_account is not set"),
                  
          fee_vault: self.instruction.fee_vault.expect("fee_vault is not set"),
                  
          public_claim_nullifier_and_linker_buffer: self.instruction.public_claim_nullifier_and_linker_buffer.expect("public_claim_nullifier_and_linker_buffer is not set"),
                  
          nullifier_set1: self.instruction.nullifier_set1.expect("nullifier_set1 is not set"),
                  
          nullifier_set2: self.instruction.nullifier_set2.expect("nullifier_set2 is not set"),
                  
          nullifier_set3: self.instruction.nullifier_set3.expect("nullifier_set3 is not set"),
                  
          nullifier_set4: self.instruction.nullifier_set4.expect("nullifier_set4 is not set"),
                  
          nullifier_set5: self.instruction.nullifier_set5.expect("nullifier_set5 is not set"),
                  
          token_pool: self.instruction.token_pool.expect("token_pool is not set"),
                  
          token_pool_ata: self.instruction.token_pool_ata.expect("token_pool_ata is not set"),
                  
          mint: self.instruction.mint.expect("mint is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                  
          computation_data: self.instruction.computation_data.expect("computation_data is not set"),
                  
          mpc_callback_wrapped_sol_unwrapping_helper_account: self.instruction.mpc_callback_wrapped_sol_unwrapping_helper_account.expect("mpc_callback_wrapped_sol_unwrapping_helper_account is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct ClaimIntoPublicBalanceToMxeV13CallbackCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            arcium_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                comp_def_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                mxe_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                computation_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                cluster_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                instructions_sysvar: Option<&'b solana_account_info::AccountInfo<'a>>,
                relayer: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                receiver_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
                public_claim_nullifier_and_linker_buffer: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set1: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set2: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set3: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set4: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set5: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_pool_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
                mint: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                computation_data: Option<&'b solana_account_info::AccountInfo<'a>>,
                mpc_callback_wrapped_sol_unwrapping_helper_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                        outputs: Option<ClaimIntoPublicBalanceToMxeV13CallbackOutput>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

