//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::Sha256Hash;
use crate::types::InstructionSeed;
use crate::types::AccountOffset;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const CLOSE_COMPUTATION_DATA_DISCRIMINATOR: [u8; 8] = [177, 43, 205, 198, 42, 249, 101, 82];

/// Accounts.
#[derive(Debug)]
pub struct CloseComputationData {
            /// The original `fee_payer` that paid rent for the computation_data PDA.
/// PDA derivation pins this signer to the queue-time fee_payer.

    
              
          pub signer: solana_pubkey::Pubkey,
                /// The MPC computation data account to close.
/// Validated by PDA seeds: [struct_seed, instruction_seed, signer, offset].
/// instruction is generic across all computation data variants.
/// The PDA seed constraint guarantees ownership and derivation, and the
/// handler reads `queued_at_slot` from a canonical byte offset that all
/// ComputationData structs share via `umbra_computation_data_account`.

    
              
          pub computation_data: solana_pubkey::Pubkey,
                /// Read for the `computation_data_expiry_slots` TTL parameter.

    
              
          pub protocol_config: solana_pubkey::Pubkey,
          
              
          pub clock: solana_pubkey::Pubkey,
      }

impl CloseComputationData {
  pub fn instruction(&self, args: CloseComputationDataInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: CloseComputationDataInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(4+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.signer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.computation_data,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.protocol_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.clock,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = CloseComputationDataInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct CloseComputationDataInstructionData {
            discriminator: [u8; 8],
                        }

impl CloseComputationDataInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [177, 43, 205, 198, 42, 249, 101, 82],
                                                            }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for CloseComputationDataInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct CloseComputationDataInstructionArgs {
                  pub struct_seed: Sha256Hash,
                pub instruction_seed: InstructionSeed,
                pub offset: AccountOffset,
      }

impl CloseComputationDataInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `CloseComputationData`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
                ///   1. `[writable]` computation_data
          ///   2. `[]` protocol_config
                ///   3. `[optional]` clock (default to `SysvarC1ock11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CloseComputationDataBuilder {
            signer: Option<solana_pubkey::Pubkey>,
                computation_data: Option<solana_pubkey::Pubkey>,
                protocol_config: Option<solana_pubkey::Pubkey>,
                clock: Option<solana_pubkey::Pubkey>,
                        struct_seed: Option<Sha256Hash>,
                instruction_seed: Option<InstructionSeed>,
                offset: Option<AccountOffset>,
        __program_id: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CloseComputationDataBuilder {
  pub fn new() -> Self {
    Self::default()
  }
    /// Set a custom program ID for the instruction (overrides the default).
    /// Use this when targeting a different deployment (e.g. devnet vs mainnet).
    #[inline(always)]
    pub fn program_id(&mut self, program_id: solana_pubkey::Pubkey) -> &mut Self {
        self.__program_id = Some(program_id);
        self
    }
            /// The original `fee_payer` that paid rent for the computation_data PDA.
/// PDA derivation pins this signer to the queue-time fee_payer.
#[inline(always)]
    pub fn signer(&mut self, signer: solana_pubkey::Pubkey) -> &mut Self {
                        self.signer = Some(signer);
                    self
    }
            /// The MPC computation data account to close.
/// Validated by PDA seeds: [struct_seed, instruction_seed, signer, offset].
/// instruction is generic across all computation data variants.
/// The PDA seed constraint guarantees ownership and derivation, and the
/// handler reads `queued_at_slot` from a canonical byte offset that all
/// ComputationData structs share via `umbra_computation_data_account`.
#[inline(always)]
    pub fn computation_data(&mut self, computation_data: solana_pubkey::Pubkey) -> &mut Self {
                        self.computation_data = Some(computation_data);
                    self
    }
            /// Read for the `computation_data_expiry_slots` TTL parameter.
#[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.protocol_config = Some(protocol_config);
                    self
    }
            /// `[optional account, default to 'SysvarC1ock11111111111111111111111111111111']`
#[inline(always)]
    pub fn clock(&mut self, clock: solana_pubkey::Pubkey) -> &mut Self {
                        self.clock = Some(clock);
                    self
    }
                    #[inline(always)]
      pub fn struct_seed(&mut self, struct_seed: Sha256Hash) -> &mut Self {
        self.struct_seed = Some(struct_seed);
        self
      }
                #[inline(always)]
      pub fn instruction_seed(&mut self, instruction_seed: InstructionSeed) -> &mut Self {
        self.instruction_seed = Some(instruction_seed);
        self
      }
                #[inline(always)]
      pub fn offset(&mut self, offset: AccountOffset) -> &mut Self {
        self.offset = Some(offset);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = CloseComputationData {
                              signer: self.signer.expect("signer is not set"),
                                        computation_data: self.computation_data.expect("computation_data is not set"),
                                        protocol_config: self.protocol_config.expect("protocol_config is not set"),
                                        clock: self.clock.unwrap_or(solana_pubkey::pubkey!("SysvarC1ock11111111111111111111111111111111")),
                      };
          let args = CloseComputationDataInstructionArgs {
                                                              struct_seed: self.struct_seed.clone().expect("struct_seed is not set"),
                                                                  instruction_seed: self.instruction_seed.clone().expect("instruction_seed is not set"),
                                                                  offset: self.offset.clone().expect("offset is not set"),
                                    };
    
    {
            let mut ix = accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts);
            if let Some(program_id) = self.__program_id {
                ix.program_id = program_id;
            }
            ix
        }
  }
}

  /// `close_computation_data` CPI accounts.
  pub struct CloseComputationDataCpiAccounts<'a, 'b> {
                  /// The original `fee_payer` that paid rent for the computation_data PDA.
/// PDA derivation pins this signer to the queue-time fee_payer.

      
                    
              pub signer: &'b solana_account_info::AccountInfo<'a>,
                        /// The MPC computation data account to close.
/// Validated by PDA seeds: [struct_seed, instruction_seed, signer, offset].
/// instruction is generic across all computation data variants.
/// The PDA seed constraint guarantees ownership and derivation, and the
/// handler reads `queued_at_slot` from a canonical byte offset that all
/// ComputationData structs share via `umbra_computation_data_account`.

      
                    
              pub computation_data: &'b solana_account_info::AccountInfo<'a>,
                        /// Read for the `computation_data_expiry_slots` TTL parameter.

      
                    
              pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub clock: &'b solana_account_info::AccountInfo<'a>,
            }

/// `close_computation_data` CPI instruction.
pub struct CloseComputationDataCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
            /// The original `fee_payer` that paid rent for the computation_data PDA.
/// PDA derivation pins this signer to the queue-time fee_payer.

    
              
          pub signer: &'b solana_account_info::AccountInfo<'a>,
                /// The MPC computation data account to close.
/// Validated by PDA seeds: [struct_seed, instruction_seed, signer, offset].
/// instruction is generic across all computation data variants.
/// The PDA seed constraint guarantees ownership and derivation, and the
/// handler reads `queued_at_slot` from a canonical byte offset that all
/// ComputationData structs share via `umbra_computation_data_account`.

    
              
          pub computation_data: &'b solana_account_info::AccountInfo<'a>,
                /// Read for the `computation_data_expiry_slots` TTL parameter.

    
              
          pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub clock: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: CloseComputationDataInstructionArgs,
  }

impl<'a, 'b> CloseComputationDataCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: CloseComputationDataCpiAccounts<'a, 'b>,
              args: CloseComputationDataInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              signer: accounts.signer,
              computation_data: accounts.computation_data,
              protocol_config: accounts.protocol_config,
              clock: accounts.clock,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(4+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.signer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.computation_data.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.protocol_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.clock.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = CloseComputationDataInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(5 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.signer.clone());
                        account_infos.push(self.computation_data.clone());
                        account_infos.push(self.protocol_config.clone());
                        account_infos.push(self.clock.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `CloseComputationData` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
                ///   1. `[writable]` computation_data
          ///   2. `[]` protocol_config
          ///   3. `[]` clock
#[derive(Clone, Debug)]
pub struct CloseComputationDataCpiBuilder<'a, 'b> {
  instruction: Box<CloseComputationDataCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CloseComputationDataCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(CloseComputationDataCpiBuilderInstruction {
      __program: program,
              signer: None,
              computation_data: None,
              protocol_config: None,
              clock: None,
                                            struct_seed: None,
                                instruction_seed: None,
                                offset: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      /// The original `fee_payer` that paid rent for the computation_data PDA.
/// PDA derivation pins this signer to the queue-time fee_payer.
#[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer = Some(signer);
                    self
    }
      /// The MPC computation data account to close.
/// Validated by PDA seeds: [struct_seed, instruction_seed, signer, offset].
/// instruction is generic across all computation data variants.
/// The PDA seed constraint guarantees ownership and derivation, and the
/// handler reads `queued_at_slot` from a canonical byte offset that all
/// ComputationData structs share via `umbra_computation_data_account`.
#[inline(always)]
    pub fn computation_data(&mut self, computation_data: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.computation_data = Some(computation_data);
                    self
    }
      /// Read for the `computation_data_expiry_slots` TTL parameter.
#[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.protocol_config = Some(protocol_config);
                    self
    }
      #[inline(always)]
    pub fn clock(&mut self, clock: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.clock = Some(clock);
                    self
    }
                    #[inline(always)]
      pub fn struct_seed(&mut self, struct_seed: Sha256Hash) -> &mut Self {
        self.instruction.struct_seed = Some(struct_seed);
        self
      }
                #[inline(always)]
      pub fn instruction_seed(&mut self, instruction_seed: InstructionSeed) -> &mut Self {
        self.instruction.instruction_seed = Some(instruction_seed);
        self
      }
                #[inline(always)]
      pub fn offset(&mut self, offset: AccountOffset) -> &mut Self {
        self.instruction.offset = Some(offset);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = CloseComputationDataInstructionArgs {
                                                              struct_seed: self.instruction.struct_seed.clone().expect("struct_seed is not set"),
                                                                  instruction_seed: self.instruction.instruction_seed.clone().expect("instruction_seed is not set"),
                                                                  offset: self.instruction.offset.clone().expect("offset is not set"),
                                    };
        let instruction = CloseComputationDataCpi {
        __program: self.instruction.__program,
                  
          signer: self.instruction.signer.expect("signer is not set"),
                  
          computation_data: self.instruction.computation_data.expect("computation_data is not set"),
                  
          protocol_config: self.instruction.protocol_config.expect("protocol_config is not set"),
                  
          clock: self.instruction.clock.expect("clock is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct CloseComputationDataCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            signer: Option<&'b solana_account_info::AccountInfo<'a>>,
                computation_data: Option<&'b solana_account_info::AccountInfo<'a>>,
                protocol_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                clock: Option<&'b solana_account_info::AccountInfo<'a>>,
                        struct_seed: Option<Sha256Hash>,
                instruction_seed: Option<InstructionSeed>,
                offset: Option<AccountOffset>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

