//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::StatusBits;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const UPDATE_ENCRYPTED_USER_ACCOUNT_DISCRIMINATOR: [u8; 8] = [191, 53, 60, 88, 97, 71, 109, 109];

/// Accounts.
#[derive(Debug)]
pub struct UpdateEncryptedUserAccount {
            /// The fee payer for the transaction.
/// This is separate from the admin to allow for sponsored transactions.

    
              
          pub fee_payer: solana_pubkey::Pubkey,
                /// The Arcium Encrypted User Account being updated.
/// Must be initialized and derived from user_address.

    
              
          pub user_account: solana_pubkey::Pubkey,
                /// The user whose account is being updated.

    
              
          pub user_address: solana_pubkey::Pubkey,
                /// The wallet specifier that authorizes this update operation.
/// Each instruction type has its own wallet specifier PDA.

    
              
          pub admin_wallet: solana_pubkey::Pubkey,
                /// Global program configuration.
/// Used to verify the program is in a valid state.

    
              
          pub protocol_config: solana_pubkey::Pubkey,
                /// The admin authorized to perform this update.
/// Must match the wallet specifier's configured admin address,
/// OR the wallet specifier must be set to PERMISSIONLESS_ADDRESS (making it permissionless).

    
              
          pub admin: solana_pubkey::Pubkey,
      }

impl UpdateEncryptedUserAccount {
  pub fn instruction(&self, args: UpdateEncryptedUserAccountInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateEncryptedUserAccountInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.fee_payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.user_address,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.admin_wallet,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.protocol_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.admin,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = UpdateEncryptedUserAccountInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateEncryptedUserAccountInstructionData {
            discriminator: [u8; 8],
                        }

impl UpdateEncryptedUserAccountInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [191, 53, 60, 88, 97, 71, 109, 109],
                                                            }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for UpdateEncryptedUserAccountInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateEncryptedUserAccountInstructionArgs {
                  pub bits_to_set: StatusBits,
                pub bits_to_unset: StatusBits,
                pub optional_data: OptionalData,
      }

impl UpdateEncryptedUserAccountInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `UpdateEncryptedUserAccount`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` fee_payer
                ///   1. `[writable]` user_account
          ///   2. `[]` user_address
          ///   3. `[]` admin_wallet
          ///   4. `[]` protocol_config
                ///   5. `[signer]` admin
#[derive(Clone, Debug, Default)]
pub struct UpdateEncryptedUserAccountBuilder {
            fee_payer: Option<solana_pubkey::Pubkey>,
                user_account: Option<solana_pubkey::Pubkey>,
                user_address: Option<solana_pubkey::Pubkey>,
                admin_wallet: Option<solana_pubkey::Pubkey>,
                protocol_config: Option<solana_pubkey::Pubkey>,
                admin: Option<solana_pubkey::Pubkey>,
                        bits_to_set: Option<StatusBits>,
                bits_to_unset: Option<StatusBits>,
                optional_data: Option<OptionalData>,
        __program_id: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateEncryptedUserAccountBuilder {
  pub fn new() -> Self {
    Self::default()
  }
    /// Set a custom program ID for the instruction (overrides the default).
    /// Use this when targeting a different deployment (e.g. devnet vs mainnet).
    #[inline(always)]
    pub fn program_id(&mut self, program_id: solana_pubkey::Pubkey) -> &mut Self {
        self.__program_id = Some(program_id);
        self
    }
            /// The fee payer for the transaction.
/// This is separate from the admin to allow for sponsored transactions.
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_payer = Some(fee_payer);
                    self
    }
            /// The Arcium Encrypted User Account being updated.
/// Must be initialized and derived from user_address.
#[inline(always)]
    pub fn user_account(&mut self, user_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_account = Some(user_account);
                    self
    }
            /// The user whose account is being updated.
#[inline(always)]
    pub fn user_address(&mut self, user_address: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_address = Some(user_address);
                    self
    }
            /// The wallet specifier that authorizes this update operation.
/// Each instruction type has its own wallet specifier PDA.
#[inline(always)]
    pub fn admin_wallet(&mut self, admin_wallet: solana_pubkey::Pubkey) -> &mut Self {
                        self.admin_wallet = Some(admin_wallet);
                    self
    }
            /// Global program configuration.
/// Used to verify the program is in a valid state.
#[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.protocol_config = Some(protocol_config);
                    self
    }
            /// The admin authorized to perform this update.
/// Must match the wallet specifier's configured admin address,
/// OR the wallet specifier must be set to PERMISSIONLESS_ADDRESS (making it permissionless).
#[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
                        self.admin = Some(admin);
                    self
    }
                    #[inline(always)]
      pub fn bits_to_set(&mut self, bits_to_set: StatusBits) -> &mut Self {
        self.bits_to_set = Some(bits_to_set);
        self
      }
                #[inline(always)]
      pub fn bits_to_unset(&mut self, bits_to_unset: StatusBits) -> &mut Self {
        self.bits_to_unset = Some(bits_to_unset);
        self
      }
                #[inline(always)]
      pub fn optional_data(&mut self, optional_data: OptionalData) -> &mut Self {
        self.optional_data = Some(optional_data);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = UpdateEncryptedUserAccount {
                              fee_payer: self.fee_payer.expect("fee_payer is not set"),
                                        user_account: self.user_account.expect("user_account is not set"),
                                        user_address: self.user_address.expect("user_address is not set"),
                                        admin_wallet: self.admin_wallet.expect("admin_wallet is not set"),
                                        protocol_config: self.protocol_config.expect("protocol_config is not set"),
                                        admin: self.admin.expect("admin is not set"),
                      };
          let args = UpdateEncryptedUserAccountInstructionArgs {
                                                              bits_to_set: self.bits_to_set.clone().expect("bits_to_set is not set"),
                                                                  bits_to_unset: self.bits_to_unset.clone().expect("bits_to_unset is not set"),
                                                                  optional_data: self.optional_data.clone().expect("optional_data is not set"),
                                    };
    
    {
            let mut ix = accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts);
            if let Some(program_id) = self.__program_id {
                ix.program_id = program_id;
            }
            ix
        }
  }
}

  /// `update_encrypted_user_account` CPI accounts.
  pub struct UpdateEncryptedUserAccountCpiAccounts<'a, 'b> {
                  /// The fee payer for the transaction.
/// This is separate from the admin to allow for sponsored transactions.

      
                    
              pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                        /// The Arcium Encrypted User Account being updated.
/// Must be initialized and derived from user_address.

      
                    
              pub user_account: &'b solana_account_info::AccountInfo<'a>,
                        /// The user whose account is being updated.

      
                    
              pub user_address: &'b solana_account_info::AccountInfo<'a>,
                        /// The wallet specifier that authorizes this update operation.
/// Each instruction type has its own wallet specifier PDA.

      
                    
              pub admin_wallet: &'b solana_account_info::AccountInfo<'a>,
                        /// Global program configuration.
/// Used to verify the program is in a valid state.

      
                    
              pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
                        /// The admin authorized to perform this update.
/// Must match the wallet specifier's configured admin address,
/// OR the wallet specifier must be set to PERMISSIONLESS_ADDRESS (making it permissionless).

      
                    
              pub admin: &'b solana_account_info::AccountInfo<'a>,
            }

/// `update_encrypted_user_account` CPI instruction.
pub struct UpdateEncryptedUserAccountCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
            /// The fee payer for the transaction.
/// This is separate from the admin to allow for sponsored transactions.

    
              
          pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                /// The Arcium Encrypted User Account being updated.
/// Must be initialized and derived from user_address.

    
              
          pub user_account: &'b solana_account_info::AccountInfo<'a>,
                /// The user whose account is being updated.

    
              
          pub user_address: &'b solana_account_info::AccountInfo<'a>,
                /// The wallet specifier that authorizes this update operation.
/// Each instruction type has its own wallet specifier PDA.

    
              
          pub admin_wallet: &'b solana_account_info::AccountInfo<'a>,
                /// Global program configuration.
/// Used to verify the program is in a valid state.

    
              
          pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
                /// The admin authorized to perform this update.
/// Must match the wallet specifier's configured admin address,
/// OR the wallet specifier must be set to PERMISSIONLESS_ADDRESS (making it permissionless).

    
              
          pub admin: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateEncryptedUserAccountInstructionArgs,
  }

impl<'a, 'b> UpdateEncryptedUserAccountCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: UpdateEncryptedUserAccountCpiAccounts<'a, 'b>,
              args: UpdateEncryptedUserAccountInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              fee_payer: accounts.fee_payer,
              user_account: accounts.user_account,
              user_address: accounts.user_address,
              admin_wallet: accounts.admin_wallet,
              protocol_config: accounts.protocol_config,
              admin: accounts.admin,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.user_address.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.admin_wallet.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.protocol_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.admin.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = UpdateEncryptedUserAccountInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.fee_payer.clone());
                        account_infos.push(self.user_account.clone());
                        account_infos.push(self.user_address.clone());
                        account_infos.push(self.admin_wallet.clone());
                        account_infos.push(self.protocol_config.clone());
                        account_infos.push(self.admin.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateEncryptedUserAccount` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` fee_payer
                ///   1. `[writable]` user_account
          ///   2. `[]` user_address
          ///   3. `[]` admin_wallet
          ///   4. `[]` protocol_config
                ///   5. `[signer]` admin
#[derive(Clone, Debug)]
pub struct UpdateEncryptedUserAccountCpiBuilder<'a, 'b> {
  instruction: Box<UpdateEncryptedUserAccountCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateEncryptedUserAccountCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateEncryptedUserAccountCpiBuilderInstruction {
      __program: program,
              fee_payer: None,
              user_account: None,
              user_address: None,
              admin_wallet: None,
              protocol_config: None,
              admin: None,
                                            bits_to_set: None,
                                bits_to_unset: None,
                                optional_data: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      /// The fee payer for the transaction.
/// This is separate from the admin to allow for sponsored transactions.
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_payer = Some(fee_payer);
                    self
    }
      /// The Arcium Encrypted User Account being updated.
/// Must be initialized and derived from user_address.
#[inline(always)]
    pub fn user_account(&mut self, user_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_account = Some(user_account);
                    self
    }
      /// The user whose account is being updated.
#[inline(always)]
    pub fn user_address(&mut self, user_address: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_address = Some(user_address);
                    self
    }
      /// The wallet specifier that authorizes this update operation.
/// Each instruction type has its own wallet specifier PDA.
#[inline(always)]
    pub fn admin_wallet(&mut self, admin_wallet: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin_wallet = Some(admin_wallet);
                    self
    }
      /// Global program configuration.
/// Used to verify the program is in a valid state.
#[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.protocol_config = Some(protocol_config);
                    self
    }
      /// The admin authorized to perform this update.
/// Must match the wallet specifier's configured admin address,
/// OR the wallet specifier must be set to PERMISSIONLESS_ADDRESS (making it permissionless).
#[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin = Some(admin);
                    self
    }
                    #[inline(always)]
      pub fn bits_to_set(&mut self, bits_to_set: StatusBits) -> &mut Self {
        self.instruction.bits_to_set = Some(bits_to_set);
        self
      }
                #[inline(always)]
      pub fn bits_to_unset(&mut self, bits_to_unset: StatusBits) -> &mut Self {
        self.instruction.bits_to_unset = Some(bits_to_unset);
        self
      }
                #[inline(always)]
      pub fn optional_data(&mut self, optional_data: OptionalData) -> &mut Self {
        self.instruction.optional_data = Some(optional_data);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = UpdateEncryptedUserAccountInstructionArgs {
                                                              bits_to_set: self.instruction.bits_to_set.clone().expect("bits_to_set is not set"),
                                                                  bits_to_unset: self.instruction.bits_to_unset.clone().expect("bits_to_unset is not set"),
                                                                  optional_data: self.instruction.optional_data.clone().expect("optional_data is not set"),
                                    };
        let instruction = UpdateEncryptedUserAccountCpi {
        __program: self.instruction.__program,
                  
          fee_payer: self.instruction.fee_payer.expect("fee_payer is not set"),
                  
          user_account: self.instruction.user_account.expect("user_account is not set"),
                  
          user_address: self.instruction.user_address.expect("user_address is not set"),
                  
          admin_wallet: self.instruction.admin_wallet.expect("admin_wallet is not set"),
                  
          protocol_config: self.instruction.protocol_config.expect("protocol_config is not set"),
                  
          admin: self.instruction.admin.expect("admin is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateEncryptedUserAccountCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            fee_payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_address: Option<&'b solana_account_info::AccountInfo<'a>>,
                admin_wallet: Option<&'b solana_account_info::AccountInfo<'a>>,
                protocol_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                admin: Option<&'b solana_account_info::AccountInfo<'a>>,
                        bits_to_set: Option<StatusBits>,
                bits_to_unset: Option<StatusBits>,
                optional_data: Option<OptionalData>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

