//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::ComputationOffset;
use crate::types::AccountOffset;
use crate::types::NumberOfBurns;
use crate::types::DispatchObserverCpi;
use crate::types::ArciumX25519PublicKey;
use crate::types::InstructionDiscriminator;
use crate::types::PriorityFees;
use crate::types::OptionalData;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const CLAIM_INTO_NEW_SHARED_BALANCE_V17_DISCRIMINATOR: [u8; 8] = [167, 73, 241, 22, 238, 27, 46, 202];

/// Accounts.
#[derive(Debug)]
pub struct ClaimIntoNewSharedBalanceV17 {
            /// The relayer — both domain signer AND rent payer for account creation.

    
              
          pub relayer: solana_pubkey::Pubkey,
          
              
          pub sign_pda_account: solana_pubkey::Pubkey,
          
              
          pub mxe_account: solana_pubkey::Pubkey,
          
              
          pub mempool_account: solana_pubkey::Pubkey,
          
              
          pub executing_pool: solana_pubkey::Pubkey,
          
              
          pub computation_account: solana_pubkey::Pubkey,
          
              
          pub comp_def_account: solana_pubkey::Pubkey,
          
              
          pub cluster_account: solana_pubkey::Pubkey,
          
              
          pub pool_account: solana_pubkey::Pubkey,
          
              
          pub clock_account: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
          
              
          pub arcium_program: solana_pubkey::Pubkey,
                /// ZK input buffer containing cryptographic data for the claim.
/// Contains: rescue encryption data, Groth16 proof, merkle root, timestamps, fees.
/// Closed after processing to return rent to relayer.

    
              
          pub claim_input_buffer: solana_pubkey::Pubkey,
                /// Used as a seed for deriving the user and token account PDAs.

    
              
          pub receiver_address: solana_pubkey::Pubkey,
                /// User's encrypted account containing their X25519 public key.
/// Must already exist with x25519 key registered for Shared encryption.

    
              
          pub receiver_user_account: solana_pubkey::Pubkey,
                /// Token account that will receive the claimed funds.
/// Created if needed (init_if_needed) for new accounts.

    
              
          pub receiver_token_account: solana_pubkey::Pubkey,
                /// Relayer's registration account for this mint.
/// Validates that the relayer is authorized to process transactions.

    
              
          pub relayer_account: solana_pubkey::Pubkey,
                /// Relayer's fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.

    
              
          pub relayer_fee_schedule: solana_pubkey::Pubkey,
                /// Protocol fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.

    
              
          pub fee_schedule: solana_pubkey::Pubkey,
                /// Unified fees pool for collecting both relayer and protocol fees.
/// Contains encrypted fee balances that can only be decrypted by MPC.
/// Updated in callback with new fee balances.

    
              
          pub fee_vault: solana_pubkey::Pubkey,
                /// Token pool holding the liquidity for this mint.
/// Funds are transferred from pool to user in the callback.
/// PDA validated in validate_preconditions.

    
              
          pub token_pool: solana_pubkey::Pubkey,
                /// SPL token mint for the token being claimed.
/// Used for PDA derivation and token operations.

    
              
          pub mint: solana_pubkey::Pubkey,
                /// Global program configuration account.
/// Contains: active incremental merkle tree index, timestamp limits, priority fees.
/// PDA validated in validate_program_information_account.

    
              
          pub protocol_config: solana_pubkey::Pubkey,
                /// Indexed Merkle Tree containing all commitment hashes.
/// Used to validate that the claimed unspent transaction outputs exist.
/// PDA validated in validate_stealth_pool.

    
              
          pub stealth_pool: solana_pubkey::Pubkey,
                /// Data is validated through ZK proof verification.
/// Contains: nullifiers, linker encryptions, linker key commitments.

    
              
          pub nullifier_and_linker_buffer: solana_pubkey::Pubkey,
                /// Nullifier set data structure for efficient nullifier lookups.
/// PDA validated in validate_nullifier_set_accounts.

    
              
          pub nullifier_set1: solana_pubkey::Pubkey,
          
              
          pub nullifier_set2: solana_pubkey::Pubkey,
          
              
          pub nullifier_set3: solana_pubkey::Pubkey,
          
              
          pub nullifier_set4: solana_pubkey::Pubkey,
          
              
          pub nullifier_set5: solana_pubkey::Pubkey,
                /// ZK verifying key for Groth16 proof verification.
/// Contains the verification key elements (alpha, beta, gamma, delta, IC).
/// PDA validated in validate_zk_verifying_key_account.

    
              
          pub zero_knowledge_verifying_key: solana_pubkey::Pubkey,
                /// Temporary storage for MPC callback data.
/// Stores nonces and fees data needed by the callback handler.
/// Closed after callback to return rent to relayer.

    
              
          pub computation_data: solana_pubkey::Pubkey,
                /// Per-mint lottery configuration. Bound into the Fiat-Shamir
/// aggregated hash so the prover and verifier agree on the constant
/// set used for the claim circuit's `ClaimTicketCalculator`.

    
              
          pub lottery_config: solana_pubkey::Pubkey,
                /// Independent initiator identity — signs the queue ix separately from the relayer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."

    
              
          pub initiator: solana_pubkey::Pubkey,
      }

impl ClaimIntoNewSharedBalanceV17 {
  pub fn instruction(&self, args: ClaimIntoNewSharedBalanceV17InstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: ClaimIntoNewSharedBalanceV17InstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(34+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.relayer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.sign_pda_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mxe_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.mempool_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.executing_pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.computation_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.comp_def_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.cluster_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.pool_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.clock_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.arcium_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.claim_input_buffer,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.receiver_address,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.receiver_user_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.receiver_token_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.relayer_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.relayer_fee_schedule,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.fee_schedule,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_vault,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.token_pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.protocol_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.stealth_pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_and_linker_buffer,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set1,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set2,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set3,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set4,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.nullifier_set5,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.zero_knowledge_verifying_key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.computation_data,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.lottery_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.initiator,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = ClaimIntoNewSharedBalanceV17InstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ClaimIntoNewSharedBalanceV17InstructionData {
            discriminator: [u8; 8],
                                                                              }

impl ClaimIntoNewSharedBalanceV17InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [167, 73, 241, 22, 238, 27, 46, 202],
                                                                                                                                                                                          }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for ClaimIntoNewSharedBalanceV17InstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ClaimIntoNewSharedBalanceV17InstructionArgs {
                  pub computation_offset: ComputationOffset,
                pub fee_vault_offset: AccountOffset,
                pub mpc_callback_data_offset: AccountOffset,
                pub number_of_burns: NumberOfBurns,
                pub claim_input_buffer_offset: AccountOffset,
                pub stealth_pool_index: AccountOffset,
                pub nullifier_and_linker_buffer_offset: AccountOffset,
                pub dispatch_observer_cpi: DispatchObserverCpi,
                pub observer_output_x25519_public_key: ArciumX25519PublicKey,
                pub destination_discriminator: InstructionDiscriminator,
                pub priority_fees: PriorityFees,
                pub optional_data: OptionalData,
      }

impl ClaimIntoNewSharedBalanceV17InstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `ClaimIntoNewSharedBalanceV17`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` relayer
                ///   1. `[writable]` sign_pda_account
          ///   2. `[]` mxe_account
                ///   3. `[writable]` mempool_account
                ///   4. `[writable]` executing_pool
                ///   5. `[writable]` computation_account
          ///   6. `[]` comp_def_account
                ///   7. `[writable]` cluster_account
                      ///   8. `[writable, optional]` pool_account (default to `G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC`)
                      ///   9. `[writable, optional]` clock_account (default to `7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot`)
                ///   10. `[optional]` system_program (default to `11111111111111111111111111111111`)
                ///   11. `[optional]` arcium_program (default to `Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ`)
                ///   12. `[writable]` claim_input_buffer
          ///   13. `[]` receiver_address
          ///   14. `[]` receiver_user_account
                ///   15. `[writable]` receiver_token_account
                ///   16. `[writable]` relayer_account
          ///   17. `[]` relayer_fee_schedule
          ///   18. `[]` fee_schedule
                ///   19. `[writable]` fee_vault
                ///   20. `[writable]` token_pool
          ///   21. `[]` mint
          ///   22. `[]` protocol_config
          ///   23. `[]` stealth_pool
                ///   24. `[writable]` nullifier_and_linker_buffer
                ///   25. `[writable]` nullifier_set1
                ///   26. `[writable]` nullifier_set2
                ///   27. `[writable]` nullifier_set3
                ///   28. `[writable]` nullifier_set4
                ///   29. `[writable]` nullifier_set5
          ///   30. `[]` zero_knowledge_verifying_key
                ///   31. `[writable]` computation_data
          ///   32. `[]` lottery_config
                ///   33. `[signer]` initiator
#[derive(Clone, Debug, Default)]
pub struct ClaimIntoNewSharedBalanceV17Builder {
            relayer: Option<solana_pubkey::Pubkey>,
                sign_pda_account: Option<solana_pubkey::Pubkey>,
                mxe_account: Option<solana_pubkey::Pubkey>,
                mempool_account: Option<solana_pubkey::Pubkey>,
                executing_pool: Option<solana_pubkey::Pubkey>,
                computation_account: Option<solana_pubkey::Pubkey>,
                comp_def_account: Option<solana_pubkey::Pubkey>,
                cluster_account: Option<solana_pubkey::Pubkey>,
                pool_account: Option<solana_pubkey::Pubkey>,
                clock_account: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                arcium_program: Option<solana_pubkey::Pubkey>,
                claim_input_buffer: Option<solana_pubkey::Pubkey>,
                receiver_address: Option<solana_pubkey::Pubkey>,
                receiver_user_account: Option<solana_pubkey::Pubkey>,
                receiver_token_account: Option<solana_pubkey::Pubkey>,
                relayer_account: Option<solana_pubkey::Pubkey>,
                relayer_fee_schedule: Option<solana_pubkey::Pubkey>,
                fee_schedule: Option<solana_pubkey::Pubkey>,
                fee_vault: Option<solana_pubkey::Pubkey>,
                token_pool: Option<solana_pubkey::Pubkey>,
                mint: Option<solana_pubkey::Pubkey>,
                protocol_config: Option<solana_pubkey::Pubkey>,
                stealth_pool: Option<solana_pubkey::Pubkey>,
                nullifier_and_linker_buffer: Option<solana_pubkey::Pubkey>,
                nullifier_set1: Option<solana_pubkey::Pubkey>,
                nullifier_set2: Option<solana_pubkey::Pubkey>,
                nullifier_set3: Option<solana_pubkey::Pubkey>,
                nullifier_set4: Option<solana_pubkey::Pubkey>,
                nullifier_set5: Option<solana_pubkey::Pubkey>,
                zero_knowledge_verifying_key: Option<solana_pubkey::Pubkey>,
                computation_data: Option<solana_pubkey::Pubkey>,
                lottery_config: Option<solana_pubkey::Pubkey>,
                initiator: Option<solana_pubkey::Pubkey>,
                        computation_offset: Option<ComputationOffset>,
                fee_vault_offset: Option<AccountOffset>,
                mpc_callback_data_offset: Option<AccountOffset>,
                number_of_burns: Option<NumberOfBurns>,
                claim_input_buffer_offset: Option<AccountOffset>,
                stealth_pool_index: Option<AccountOffset>,
                nullifier_and_linker_buffer_offset: Option<AccountOffset>,
                dispatch_observer_cpi: Option<DispatchObserverCpi>,
                observer_output_x25519_public_key: Option<ArciumX25519PublicKey>,
                destination_discriminator: Option<InstructionDiscriminator>,
                priority_fees: Option<PriorityFees>,
                optional_data: Option<OptionalData>,
        __program_id: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ClaimIntoNewSharedBalanceV17Builder {
  pub fn new() -> Self {
    Self::default()
  }
    /// Set a custom program ID for the instruction (overrides the default).
    /// Use this when targeting a different deployment (e.g. devnet vs mainnet).
    #[inline(always)]
    pub fn program_id(&mut self, program_id: solana_pubkey::Pubkey) -> &mut Self {
        self.__program_id = Some(program_id);
        self
    }
            /// The relayer — both domain signer AND rent payer for account creation.
#[inline(always)]
    pub fn relayer(&mut self, relayer: solana_pubkey::Pubkey) -> &mut Self {
                        self.relayer = Some(relayer);
                    self
    }
            #[inline(always)]
    pub fn sign_pda_account(&mut self, sign_pda_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.sign_pda_account = Some(sign_pda_account);
                    self
    }
            #[inline(always)]
    pub fn mxe_account(&mut self, mxe_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.mxe_account = Some(mxe_account);
                    self
    }
            #[inline(always)]
    pub fn mempool_account(&mut self, mempool_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.mempool_account = Some(mempool_account);
                    self
    }
            #[inline(always)]
    pub fn executing_pool(&mut self, executing_pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.executing_pool = Some(executing_pool);
                    self
    }
            #[inline(always)]
    pub fn computation_account(&mut self, computation_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.computation_account = Some(computation_account);
                    self
    }
            #[inline(always)]
    pub fn comp_def_account(&mut self, comp_def_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.comp_def_account = Some(comp_def_account);
                    self
    }
            #[inline(always)]
    pub fn cluster_account(&mut self, cluster_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.cluster_account = Some(cluster_account);
                    self
    }
            /// `[optional account, default to 'G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC']`
#[inline(always)]
    pub fn pool_account(&mut self, pool_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.pool_account = Some(pool_account);
                    self
    }
            /// `[optional account, default to '7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot']`
#[inline(always)]
    pub fn clock_account(&mut self, clock_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.clock_account = Some(clock_account);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// `[optional account, default to 'Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ']`
#[inline(always)]
    pub fn arcium_program(&mut self, arcium_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.arcium_program = Some(arcium_program);
                    self
    }
            /// ZK input buffer containing cryptographic data for the claim.
/// Contains: rescue encryption data, Groth16 proof, merkle root, timestamps, fees.
/// Closed after processing to return rent to relayer.
#[inline(always)]
    pub fn claim_input_buffer(&mut self, claim_input_buffer: solana_pubkey::Pubkey) -> &mut Self {
                        self.claim_input_buffer = Some(claim_input_buffer);
                    self
    }
            /// Used as a seed for deriving the user and token account PDAs.
#[inline(always)]
    pub fn receiver_address(&mut self, receiver_address: solana_pubkey::Pubkey) -> &mut Self {
                        self.receiver_address = Some(receiver_address);
                    self
    }
            /// User's encrypted account containing their X25519 public key.
/// Must already exist with x25519 key registered for Shared encryption.
#[inline(always)]
    pub fn receiver_user_account(&mut self, receiver_user_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.receiver_user_account = Some(receiver_user_account);
                    self
    }
            /// Token account that will receive the claimed funds.
/// Created if needed (init_if_needed) for new accounts.
#[inline(always)]
    pub fn receiver_token_account(&mut self, receiver_token_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.receiver_token_account = Some(receiver_token_account);
                    self
    }
            /// Relayer's registration account for this mint.
/// Validates that the relayer is authorized to process transactions.
#[inline(always)]
    pub fn relayer_account(&mut self, relayer_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.relayer_account = Some(relayer_account);
                    self
    }
            /// Relayer's fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.
#[inline(always)]
    pub fn relayer_fee_schedule(&mut self, relayer_fee_schedule: solana_pubkey::Pubkey) -> &mut Self {
                        self.relayer_fee_schedule = Some(relayer_fee_schedule);
                    self
    }
            /// Protocol fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.
#[inline(always)]
    pub fn fee_schedule(&mut self, fee_schedule: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_schedule = Some(fee_schedule);
                    self
    }
            /// Unified fees pool for collecting both relayer and protocol fees.
/// Contains encrypted fee balances that can only be decrypted by MPC.
/// Updated in callback with new fee balances.
#[inline(always)]
    pub fn fee_vault(&mut self, fee_vault: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_vault = Some(fee_vault);
                    self
    }
            /// Token pool holding the liquidity for this mint.
/// Funds are transferred from pool to user in the callback.
/// PDA validated in validate_preconditions.
#[inline(always)]
    pub fn token_pool(&mut self, token_pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_pool = Some(token_pool);
                    self
    }
            /// SPL token mint for the token being claimed.
/// Used for PDA derivation and token operations.
#[inline(always)]
    pub fn mint(&mut self, mint: solana_pubkey::Pubkey) -> &mut Self {
                        self.mint = Some(mint);
                    self
    }
            /// Global program configuration account.
/// Contains: active incremental merkle tree index, timestamp limits, priority fees.
/// PDA validated in validate_program_information_account.
#[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.protocol_config = Some(protocol_config);
                    self
    }
            /// Indexed Merkle Tree containing all commitment hashes.
/// Used to validate that the claimed unspent transaction outputs exist.
/// PDA validated in validate_stealth_pool.
#[inline(always)]
    pub fn stealth_pool(&mut self, stealth_pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.stealth_pool = Some(stealth_pool);
                    self
    }
            /// Data is validated through ZK proof verification.
/// Contains: nullifiers, linker encryptions, linker key commitments.
#[inline(always)]
    pub fn nullifier_and_linker_buffer(&mut self, nullifier_and_linker_buffer: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_and_linker_buffer = Some(nullifier_and_linker_buffer);
                    self
    }
            /// Nullifier set data structure for efficient nullifier lookups.
/// PDA validated in validate_nullifier_set_accounts.
#[inline(always)]
    pub fn nullifier_set1(&mut self, nullifier_set1: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set1 = Some(nullifier_set1);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set2(&mut self, nullifier_set2: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set2 = Some(nullifier_set2);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set3(&mut self, nullifier_set3: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set3 = Some(nullifier_set3);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set4(&mut self, nullifier_set4: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set4 = Some(nullifier_set4);
                    self
    }
            #[inline(always)]
    pub fn nullifier_set5(&mut self, nullifier_set5: solana_pubkey::Pubkey) -> &mut Self {
                        self.nullifier_set5 = Some(nullifier_set5);
                    self
    }
            /// ZK verifying key for Groth16 proof verification.
/// Contains the verification key elements (alpha, beta, gamma, delta, IC).
/// PDA validated in validate_zk_verifying_key_account.
#[inline(always)]
    pub fn zero_knowledge_verifying_key(&mut self, zero_knowledge_verifying_key: solana_pubkey::Pubkey) -> &mut Self {
                        self.zero_knowledge_verifying_key = Some(zero_knowledge_verifying_key);
                    self
    }
            /// Temporary storage for MPC callback data.
/// Stores nonces and fees data needed by the callback handler.
/// Closed after callback to return rent to relayer.
#[inline(always)]
    pub fn computation_data(&mut self, computation_data: solana_pubkey::Pubkey) -> &mut Self {
                        self.computation_data = Some(computation_data);
                    self
    }
            /// Per-mint lottery configuration. Bound into the Fiat-Shamir
/// aggregated hash so the prover and verifier agree on the constant
/// set used for the claim circuit's `ClaimTicketCalculator`.
#[inline(always)]
    pub fn lottery_config(&mut self, lottery_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.lottery_config = Some(lottery_config);
                    self
    }
            /// Independent initiator identity — signs the queue ix separately from the relayer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."
#[inline(always)]
    pub fn initiator(&mut self, initiator: solana_pubkey::Pubkey) -> &mut Self {
                        self.initiator = Some(initiator);
                    self
    }
                    #[inline(always)]
      pub fn computation_offset(&mut self, computation_offset: ComputationOffset) -> &mut Self {
        self.computation_offset = Some(computation_offset);
        self
      }
                #[inline(always)]
      pub fn fee_vault_offset(&mut self, fee_vault_offset: AccountOffset) -> &mut Self {
        self.fee_vault_offset = Some(fee_vault_offset);
        self
      }
                #[inline(always)]
      pub fn mpc_callback_data_offset(&mut self, mpc_callback_data_offset: AccountOffset) -> &mut Self {
        self.mpc_callback_data_offset = Some(mpc_callback_data_offset);
        self
      }
                #[inline(always)]
      pub fn number_of_burns(&mut self, number_of_burns: NumberOfBurns) -> &mut Self {
        self.number_of_burns = Some(number_of_burns);
        self
      }
                #[inline(always)]
      pub fn claim_input_buffer_offset(&mut self, claim_input_buffer_offset: AccountOffset) -> &mut Self {
        self.claim_input_buffer_offset = Some(claim_input_buffer_offset);
        self
      }
                #[inline(always)]
      pub fn stealth_pool_index(&mut self, stealth_pool_index: AccountOffset) -> &mut Self {
        self.stealth_pool_index = Some(stealth_pool_index);
        self
      }
                #[inline(always)]
      pub fn nullifier_and_linker_buffer_offset(&mut self, nullifier_and_linker_buffer_offset: AccountOffset) -> &mut Self {
        self.nullifier_and_linker_buffer_offset = Some(nullifier_and_linker_buffer_offset);
        self
      }
                #[inline(always)]
      pub fn dispatch_observer_cpi(&mut self, dispatch_observer_cpi: DispatchObserverCpi) -> &mut Self {
        self.dispatch_observer_cpi = Some(dispatch_observer_cpi);
        self
      }
                #[inline(always)]
      pub fn observer_output_x25519_public_key(&mut self, observer_output_x25519_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.observer_output_x25519_public_key = Some(observer_output_x25519_public_key);
        self
      }
                #[inline(always)]
      pub fn destination_discriminator(&mut self, destination_discriminator: InstructionDiscriminator) -> &mut Self {
        self.destination_discriminator = Some(destination_discriminator);
        self
      }
                #[inline(always)]
      pub fn priority_fees(&mut self, priority_fees: PriorityFees) -> &mut Self {
        self.priority_fees = Some(priority_fees);
        self
      }
                #[inline(always)]
      pub fn optional_data(&mut self, optional_data: OptionalData) -> &mut Self {
        self.optional_data = Some(optional_data);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = ClaimIntoNewSharedBalanceV17 {
                              relayer: self.relayer.expect("relayer is not set"),
                                        sign_pda_account: self.sign_pda_account.expect("sign_pda_account is not set"),
                                        mxe_account: self.mxe_account.expect("mxe_account is not set"),
                                        mempool_account: self.mempool_account.expect("mempool_account is not set"),
                                        executing_pool: self.executing_pool.expect("executing_pool is not set"),
                                        computation_account: self.computation_account.expect("computation_account is not set"),
                                        comp_def_account: self.comp_def_account.expect("comp_def_account is not set"),
                                        cluster_account: self.cluster_account.expect("cluster_account is not set"),
                                        pool_account: self.pool_account.unwrap_or(solana_pubkey::pubkey!("G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC")),
                                        clock_account: self.clock_account.unwrap_or(solana_pubkey::pubkey!("7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot")),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                                        arcium_program: self.arcium_program.unwrap_or(solana_pubkey::pubkey!("Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ")),
                                        claim_input_buffer: self.claim_input_buffer.expect("claim_input_buffer is not set"),
                                        receiver_address: self.receiver_address.expect("receiver_address is not set"),
                                        receiver_user_account: self.receiver_user_account.expect("receiver_user_account is not set"),
                                        receiver_token_account: self.receiver_token_account.expect("receiver_token_account is not set"),
                                        relayer_account: self.relayer_account.expect("relayer_account is not set"),
                                        relayer_fee_schedule: self.relayer_fee_schedule.expect("relayer_fee_schedule is not set"),
                                        fee_schedule: self.fee_schedule.expect("fee_schedule is not set"),
                                        fee_vault: self.fee_vault.expect("fee_vault is not set"),
                                        token_pool: self.token_pool.expect("token_pool is not set"),
                                        mint: self.mint.expect("mint is not set"),
                                        protocol_config: self.protocol_config.expect("protocol_config is not set"),
                                        stealth_pool: self.stealth_pool.expect("stealth_pool is not set"),
                                        nullifier_and_linker_buffer: self.nullifier_and_linker_buffer.expect("nullifier_and_linker_buffer is not set"),
                                        nullifier_set1: self.nullifier_set1.expect("nullifier_set1 is not set"),
                                        nullifier_set2: self.nullifier_set2.expect("nullifier_set2 is not set"),
                                        nullifier_set3: self.nullifier_set3.expect("nullifier_set3 is not set"),
                                        nullifier_set4: self.nullifier_set4.expect("nullifier_set4 is not set"),
                                        nullifier_set5: self.nullifier_set5.expect("nullifier_set5 is not set"),
                                        zero_knowledge_verifying_key: self.zero_knowledge_verifying_key.expect("zero_knowledge_verifying_key is not set"),
                                        computation_data: self.computation_data.expect("computation_data is not set"),
                                        lottery_config: self.lottery_config.expect("lottery_config is not set"),
                                        initiator: self.initiator.expect("initiator is not set"),
                      };
          let args = ClaimIntoNewSharedBalanceV17InstructionArgs {
                                                              computation_offset: self.computation_offset.clone().expect("computation_offset is not set"),
                                                                  fee_vault_offset: self.fee_vault_offset.clone().expect("fee_vault_offset is not set"),
                                                                  mpc_callback_data_offset: self.mpc_callback_data_offset.clone().expect("mpc_callback_data_offset is not set"),
                                                                  number_of_burns: self.number_of_burns.clone().expect("number_of_burns is not set"),
                                                                  claim_input_buffer_offset: self.claim_input_buffer_offset.clone().expect("claim_input_buffer_offset is not set"),
                                                                  stealth_pool_index: self.stealth_pool_index.clone().expect("stealth_pool_index is not set"),
                                                                  nullifier_and_linker_buffer_offset: self.nullifier_and_linker_buffer_offset.clone().expect("nullifier_and_linker_buffer_offset is not set"),
                                                                  dispatch_observer_cpi: self.dispatch_observer_cpi.clone().expect("dispatch_observer_cpi is not set"),
                                                                  observer_output_x25519_public_key: self.observer_output_x25519_public_key.clone().expect("observer_output_x25519_public_key is not set"),
                                                                  destination_discriminator: self.destination_discriminator.clone().expect("destination_discriminator is not set"),
                                                                  priority_fees: self.priority_fees.clone().expect("priority_fees is not set"),
                                                                  optional_data: self.optional_data.clone().expect("optional_data is not set"),
                                    };
    
    {
            let mut ix = accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts);
            if let Some(program_id) = self.__program_id {
                ix.program_id = program_id;
            }
            ix
        }
  }
}

  /// `claim_into_new_shared_balance_v17` CPI accounts.
  pub struct ClaimIntoNewSharedBalanceV17CpiAccounts<'a, 'b> {
                  /// The relayer — both domain signer AND rent payer for account creation.

      
                    
              pub relayer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub sign_pda_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mxe_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mempool_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub executing_pool: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub computation_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub comp_def_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cluster_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub pool_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub clock_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub arcium_program: &'b solana_account_info::AccountInfo<'a>,
                        /// ZK input buffer containing cryptographic data for the claim.
/// Contains: rescue encryption data, Groth16 proof, merkle root, timestamps, fees.
/// Closed after processing to return rent to relayer.

      
                    
              pub claim_input_buffer: &'b solana_account_info::AccountInfo<'a>,
                        /// Used as a seed for deriving the user and token account PDAs.

      
                    
              pub receiver_address: &'b solana_account_info::AccountInfo<'a>,
                        /// User's encrypted account containing their X25519 public key.
/// Must already exist with x25519 key registered for Shared encryption.

      
                    
              pub receiver_user_account: &'b solana_account_info::AccountInfo<'a>,
                        /// Token account that will receive the claimed funds.
/// Created if needed (init_if_needed) for new accounts.

      
                    
              pub receiver_token_account: &'b solana_account_info::AccountInfo<'a>,
                        /// Relayer's registration account for this mint.
/// Validates that the relayer is authorized to process transactions.

      
                    
              pub relayer_account: &'b solana_account_info::AccountInfo<'a>,
                        /// Relayer's fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.

      
                    
              pub relayer_fee_schedule: &'b solana_account_info::AccountInfo<'a>,
                        /// Protocol fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.

      
                    
              pub fee_schedule: &'b solana_account_info::AccountInfo<'a>,
                        /// Unified fees pool for collecting both relayer and protocol fees.
/// Contains encrypted fee balances that can only be decrypted by MPC.
/// Updated in callback with new fee balances.

      
                    
              pub fee_vault: &'b solana_account_info::AccountInfo<'a>,
                        /// Token pool holding the liquidity for this mint.
/// Funds are transferred from pool to user in the callback.
/// PDA validated in validate_preconditions.

      
                    
              pub token_pool: &'b solana_account_info::AccountInfo<'a>,
                        /// SPL token mint for the token being claimed.
/// Used for PDA derivation and token operations.

      
                    
              pub mint: &'b solana_account_info::AccountInfo<'a>,
                        /// Global program configuration account.
/// Contains: active incremental merkle tree index, timestamp limits, priority fees.
/// PDA validated in validate_program_information_account.

      
                    
              pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
                        /// Indexed Merkle Tree containing all commitment hashes.
/// Used to validate that the claimed unspent transaction outputs exist.
/// PDA validated in validate_stealth_pool.

      
                    
              pub stealth_pool: &'b solana_account_info::AccountInfo<'a>,
                        /// Data is validated through ZK proof verification.
/// Contains: nullifiers, linker encryptions, linker key commitments.

      
                    
              pub nullifier_and_linker_buffer: &'b solana_account_info::AccountInfo<'a>,
                        /// Nullifier set data structure for efficient nullifier lookups.
/// PDA validated in validate_nullifier_set_accounts.

      
                    
              pub nullifier_set1: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set2: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set3: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set4: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub nullifier_set5: &'b solana_account_info::AccountInfo<'a>,
                        /// ZK verifying key for Groth16 proof verification.
/// Contains the verification key elements (alpha, beta, gamma, delta, IC).
/// PDA validated in validate_zk_verifying_key_account.

      
                    
              pub zero_knowledge_verifying_key: &'b solana_account_info::AccountInfo<'a>,
                        /// Temporary storage for MPC callback data.
/// Stores nonces and fees data needed by the callback handler.
/// Closed after callback to return rent to relayer.

      
                    
              pub computation_data: &'b solana_account_info::AccountInfo<'a>,
                        /// Per-mint lottery configuration. Bound into the Fiat-Shamir
/// aggregated hash so the prover and verifier agree on the constant
/// set used for the claim circuit's `ClaimTicketCalculator`.

      
                    
              pub lottery_config: &'b solana_account_info::AccountInfo<'a>,
                        /// Independent initiator identity — signs the queue ix separately from the relayer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."

      
                    
              pub initiator: &'b solana_account_info::AccountInfo<'a>,
            }

/// `claim_into_new_shared_balance_v17` CPI instruction.
pub struct ClaimIntoNewSharedBalanceV17Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
            /// The relayer — both domain signer AND rent payer for account creation.

    
              
          pub relayer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub sign_pda_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mxe_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mempool_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub executing_pool: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub computation_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub comp_def_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cluster_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub pool_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub clock_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub arcium_program: &'b solana_account_info::AccountInfo<'a>,
                /// ZK input buffer containing cryptographic data for the claim.
/// Contains: rescue encryption data, Groth16 proof, merkle root, timestamps, fees.
/// Closed after processing to return rent to relayer.

    
              
          pub claim_input_buffer: &'b solana_account_info::AccountInfo<'a>,
                /// Used as a seed for deriving the user and token account PDAs.

    
              
          pub receiver_address: &'b solana_account_info::AccountInfo<'a>,
                /// User's encrypted account containing their X25519 public key.
/// Must already exist with x25519 key registered for Shared encryption.

    
              
          pub receiver_user_account: &'b solana_account_info::AccountInfo<'a>,
                /// Token account that will receive the claimed funds.
/// Created if needed (init_if_needed) for new accounts.

    
              
          pub receiver_token_account: &'b solana_account_info::AccountInfo<'a>,
                /// Relayer's registration account for this mint.
/// Validates that the relayer is authorized to process transactions.

    
              
          pub relayer_account: &'b solana_account_info::AccountInfo<'a>,
                /// Relayer's fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.

    
              
          pub relayer_fee_schedule: &'b solana_account_info::AccountInfo<'a>,
                /// Protocol fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.

    
              
          pub fee_schedule: &'b solana_account_info::AccountInfo<'a>,
                /// Unified fees pool for collecting both relayer and protocol fees.
/// Contains encrypted fee balances that can only be decrypted by MPC.
/// Updated in callback with new fee balances.

    
              
          pub fee_vault: &'b solana_account_info::AccountInfo<'a>,
                /// Token pool holding the liquidity for this mint.
/// Funds are transferred from pool to user in the callback.
/// PDA validated in validate_preconditions.

    
              
          pub token_pool: &'b solana_account_info::AccountInfo<'a>,
                /// SPL token mint for the token being claimed.
/// Used for PDA derivation and token operations.

    
              
          pub mint: &'b solana_account_info::AccountInfo<'a>,
                /// Global program configuration account.
/// Contains: active incremental merkle tree index, timestamp limits, priority fees.
/// PDA validated in validate_program_information_account.

    
              
          pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
                /// Indexed Merkle Tree containing all commitment hashes.
/// Used to validate that the claimed unspent transaction outputs exist.
/// PDA validated in validate_stealth_pool.

    
              
          pub stealth_pool: &'b solana_account_info::AccountInfo<'a>,
                /// Data is validated through ZK proof verification.
/// Contains: nullifiers, linker encryptions, linker key commitments.

    
              
          pub nullifier_and_linker_buffer: &'b solana_account_info::AccountInfo<'a>,
                /// Nullifier set data structure for efficient nullifier lookups.
/// PDA validated in validate_nullifier_set_accounts.

    
              
          pub nullifier_set1: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set2: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set3: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set4: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub nullifier_set5: &'b solana_account_info::AccountInfo<'a>,
                /// ZK verifying key for Groth16 proof verification.
/// Contains the verification key elements (alpha, beta, gamma, delta, IC).
/// PDA validated in validate_zk_verifying_key_account.

    
              
          pub zero_knowledge_verifying_key: &'b solana_account_info::AccountInfo<'a>,
                /// Temporary storage for MPC callback data.
/// Stores nonces and fees data needed by the callback handler.
/// Closed after callback to return rent to relayer.

    
              
          pub computation_data: &'b solana_account_info::AccountInfo<'a>,
                /// Per-mint lottery configuration. Bound into the Fiat-Shamir
/// aggregated hash so the prover and verifier agree on the constant
/// set used for the claim circuit's `ClaimTicketCalculator`.

    
              
          pub lottery_config: &'b solana_account_info::AccountInfo<'a>,
                /// Independent initiator identity — signs the queue ix separately from the relayer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."

    
              
          pub initiator: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: ClaimIntoNewSharedBalanceV17InstructionArgs,
  }

impl<'a, 'b> ClaimIntoNewSharedBalanceV17Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: ClaimIntoNewSharedBalanceV17CpiAccounts<'a, 'b>,
              args: ClaimIntoNewSharedBalanceV17InstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              relayer: accounts.relayer,
              sign_pda_account: accounts.sign_pda_account,
              mxe_account: accounts.mxe_account,
              mempool_account: accounts.mempool_account,
              executing_pool: accounts.executing_pool,
              computation_account: accounts.computation_account,
              comp_def_account: accounts.comp_def_account,
              cluster_account: accounts.cluster_account,
              pool_account: accounts.pool_account,
              clock_account: accounts.clock_account,
              system_program: accounts.system_program,
              arcium_program: accounts.arcium_program,
              claim_input_buffer: accounts.claim_input_buffer,
              receiver_address: accounts.receiver_address,
              receiver_user_account: accounts.receiver_user_account,
              receiver_token_account: accounts.receiver_token_account,
              relayer_account: accounts.relayer_account,
              relayer_fee_schedule: accounts.relayer_fee_schedule,
              fee_schedule: accounts.fee_schedule,
              fee_vault: accounts.fee_vault,
              token_pool: accounts.token_pool,
              mint: accounts.mint,
              protocol_config: accounts.protocol_config,
              stealth_pool: accounts.stealth_pool,
              nullifier_and_linker_buffer: accounts.nullifier_and_linker_buffer,
              nullifier_set1: accounts.nullifier_set1,
              nullifier_set2: accounts.nullifier_set2,
              nullifier_set3: accounts.nullifier_set3,
              nullifier_set4: accounts.nullifier_set4,
              nullifier_set5: accounts.nullifier_set5,
              zero_knowledge_verifying_key: accounts.zero_knowledge_verifying_key,
              computation_data: accounts.computation_data,
              lottery_config: accounts.lottery_config,
              initiator: accounts.initiator,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(34+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.relayer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.sign_pda_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mxe_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.mempool_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.executing_pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.computation_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.comp_def_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.cluster_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.clock_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.arcium_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.claim_input_buffer.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.receiver_address.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.receiver_user_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.receiver_token_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.relayer_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.relayer_fee_schedule.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.fee_schedule.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_vault.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.token_pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.protocol_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.stealth_pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_and_linker_buffer.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set1.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set2.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set3.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set4.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.nullifier_set5.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.zero_knowledge_verifying_key.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.computation_data.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.lottery_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.initiator.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = ClaimIntoNewSharedBalanceV17InstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(35 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.relayer.clone());
                        account_infos.push(self.sign_pda_account.clone());
                        account_infos.push(self.mxe_account.clone());
                        account_infos.push(self.mempool_account.clone());
                        account_infos.push(self.executing_pool.clone());
                        account_infos.push(self.computation_account.clone());
                        account_infos.push(self.comp_def_account.clone());
                        account_infos.push(self.cluster_account.clone());
                        account_infos.push(self.pool_account.clone());
                        account_infos.push(self.clock_account.clone());
                        account_infos.push(self.system_program.clone());
                        account_infos.push(self.arcium_program.clone());
                        account_infos.push(self.claim_input_buffer.clone());
                        account_infos.push(self.receiver_address.clone());
                        account_infos.push(self.receiver_user_account.clone());
                        account_infos.push(self.receiver_token_account.clone());
                        account_infos.push(self.relayer_account.clone());
                        account_infos.push(self.relayer_fee_schedule.clone());
                        account_infos.push(self.fee_schedule.clone());
                        account_infos.push(self.fee_vault.clone());
                        account_infos.push(self.token_pool.clone());
                        account_infos.push(self.mint.clone());
                        account_infos.push(self.protocol_config.clone());
                        account_infos.push(self.stealth_pool.clone());
                        account_infos.push(self.nullifier_and_linker_buffer.clone());
                        account_infos.push(self.nullifier_set1.clone());
                        account_infos.push(self.nullifier_set2.clone());
                        account_infos.push(self.nullifier_set3.clone());
                        account_infos.push(self.nullifier_set4.clone());
                        account_infos.push(self.nullifier_set5.clone());
                        account_infos.push(self.zero_knowledge_verifying_key.clone());
                        account_infos.push(self.computation_data.clone());
                        account_infos.push(self.lottery_config.clone());
                        account_infos.push(self.initiator.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `ClaimIntoNewSharedBalanceV17` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` relayer
                ///   1. `[writable]` sign_pda_account
          ///   2. `[]` mxe_account
                ///   3. `[writable]` mempool_account
                ///   4. `[writable]` executing_pool
                ///   5. `[writable]` computation_account
          ///   6. `[]` comp_def_account
                ///   7. `[writable]` cluster_account
                ///   8. `[writable]` pool_account
                ///   9. `[writable]` clock_account
          ///   10. `[]` system_program
          ///   11. `[]` arcium_program
                ///   12. `[writable]` claim_input_buffer
          ///   13. `[]` receiver_address
          ///   14. `[]` receiver_user_account
                ///   15. `[writable]` receiver_token_account
                ///   16. `[writable]` relayer_account
          ///   17. `[]` relayer_fee_schedule
          ///   18. `[]` fee_schedule
                ///   19. `[writable]` fee_vault
                ///   20. `[writable]` token_pool
          ///   21. `[]` mint
          ///   22. `[]` protocol_config
          ///   23. `[]` stealth_pool
                ///   24. `[writable]` nullifier_and_linker_buffer
                ///   25. `[writable]` nullifier_set1
                ///   26. `[writable]` nullifier_set2
                ///   27. `[writable]` nullifier_set3
                ///   28. `[writable]` nullifier_set4
                ///   29. `[writable]` nullifier_set5
          ///   30. `[]` zero_knowledge_verifying_key
                ///   31. `[writable]` computation_data
          ///   32. `[]` lottery_config
                ///   33. `[signer]` initiator
#[derive(Clone, Debug)]
pub struct ClaimIntoNewSharedBalanceV17CpiBuilder<'a, 'b> {
  instruction: Box<ClaimIntoNewSharedBalanceV17CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ClaimIntoNewSharedBalanceV17CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(ClaimIntoNewSharedBalanceV17CpiBuilderInstruction {
      __program: program,
              relayer: None,
              sign_pda_account: None,
              mxe_account: None,
              mempool_account: None,
              executing_pool: None,
              computation_account: None,
              comp_def_account: None,
              cluster_account: None,
              pool_account: None,
              clock_account: None,
              system_program: None,
              arcium_program: None,
              claim_input_buffer: None,
              receiver_address: None,
              receiver_user_account: None,
              receiver_token_account: None,
              relayer_account: None,
              relayer_fee_schedule: None,
              fee_schedule: None,
              fee_vault: None,
              token_pool: None,
              mint: None,
              protocol_config: None,
              stealth_pool: None,
              nullifier_and_linker_buffer: None,
              nullifier_set1: None,
              nullifier_set2: None,
              nullifier_set3: None,
              nullifier_set4: None,
              nullifier_set5: None,
              zero_knowledge_verifying_key: None,
              computation_data: None,
              lottery_config: None,
              initiator: None,
                                            computation_offset: None,
                                fee_vault_offset: None,
                                mpc_callback_data_offset: None,
                                number_of_burns: None,
                                claim_input_buffer_offset: None,
                                stealth_pool_index: None,
                                nullifier_and_linker_buffer_offset: None,
                                dispatch_observer_cpi: None,
                                observer_output_x25519_public_key: None,
                                destination_discriminator: None,
                                priority_fees: None,
                                optional_data: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      /// The relayer — both domain signer AND rent payer for account creation.
#[inline(always)]
    pub fn relayer(&mut self, relayer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.relayer = Some(relayer);
                    self
    }
      #[inline(always)]
    pub fn sign_pda_account(&mut self, sign_pda_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.sign_pda_account = Some(sign_pda_account);
                    self
    }
      #[inline(always)]
    pub fn mxe_account(&mut self, mxe_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mxe_account = Some(mxe_account);
                    self
    }
      #[inline(always)]
    pub fn mempool_account(&mut self, mempool_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mempool_account = Some(mempool_account);
                    self
    }
      #[inline(always)]
    pub fn executing_pool(&mut self, executing_pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.executing_pool = Some(executing_pool);
                    self
    }
      #[inline(always)]
    pub fn computation_account(&mut self, computation_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.computation_account = Some(computation_account);
                    self
    }
      #[inline(always)]
    pub fn comp_def_account(&mut self, comp_def_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.comp_def_account = Some(comp_def_account);
                    self
    }
      #[inline(always)]
    pub fn cluster_account(&mut self, cluster_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cluster_account = Some(cluster_account);
                    self
    }
      #[inline(always)]
    pub fn pool_account(&mut self, pool_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.pool_account = Some(pool_account);
                    self
    }
      #[inline(always)]
    pub fn clock_account(&mut self, clock_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.clock_account = Some(clock_account);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      #[inline(always)]
    pub fn arcium_program(&mut self, arcium_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.arcium_program = Some(arcium_program);
                    self
    }
      /// ZK input buffer containing cryptographic data for the claim.
/// Contains: rescue encryption data, Groth16 proof, merkle root, timestamps, fees.
/// Closed after processing to return rent to relayer.
#[inline(always)]
    pub fn claim_input_buffer(&mut self, claim_input_buffer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.claim_input_buffer = Some(claim_input_buffer);
                    self
    }
      /// Used as a seed for deriving the user and token account PDAs.
#[inline(always)]
    pub fn receiver_address(&mut self, receiver_address: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.receiver_address = Some(receiver_address);
                    self
    }
      /// User's encrypted account containing their X25519 public key.
/// Must already exist with x25519 key registered for Shared encryption.
#[inline(always)]
    pub fn receiver_user_account(&mut self, receiver_user_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.receiver_user_account = Some(receiver_user_account);
                    self
    }
      /// Token account that will receive the claimed funds.
/// Created if needed (init_if_needed) for new accounts.
#[inline(always)]
    pub fn receiver_token_account(&mut self, receiver_token_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.receiver_token_account = Some(receiver_token_account);
                    self
    }
      /// Relayer's registration account for this mint.
/// Validates that the relayer is authorized to process transactions.
#[inline(always)]
    pub fn relayer_account(&mut self, relayer_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.relayer_account = Some(relayer_account);
                    self
    }
      /// Relayer's fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.
#[inline(always)]
    pub fn relayer_fee_schedule(&mut self, relayer_fee_schedule: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.relayer_fee_schedule = Some(relayer_fee_schedule);
                    self
    }
      /// Protocol fee configuration for this instruction type.
/// Contains the per-(ix, mint, allowed_address) `fee_basis_points` rate.
#[inline(always)]
    pub fn fee_schedule(&mut self, fee_schedule: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_schedule = Some(fee_schedule);
                    self
    }
      /// Unified fees pool for collecting both relayer and protocol fees.
/// Contains encrypted fee balances that can only be decrypted by MPC.
/// Updated in callback with new fee balances.
#[inline(always)]
    pub fn fee_vault(&mut self, fee_vault: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_vault = Some(fee_vault);
                    self
    }
      /// Token pool holding the liquidity for this mint.
/// Funds are transferred from pool to user in the callback.
/// PDA validated in validate_preconditions.
#[inline(always)]
    pub fn token_pool(&mut self, token_pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_pool = Some(token_pool);
                    self
    }
      /// SPL token mint for the token being claimed.
/// Used for PDA derivation and token operations.
#[inline(always)]
    pub fn mint(&mut self, mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mint = Some(mint);
                    self
    }
      /// Global program configuration account.
/// Contains: active incremental merkle tree index, timestamp limits, priority fees.
/// PDA validated in validate_program_information_account.
#[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.protocol_config = Some(protocol_config);
                    self
    }
      /// Indexed Merkle Tree containing all commitment hashes.
/// Used to validate that the claimed unspent transaction outputs exist.
/// PDA validated in validate_stealth_pool.
#[inline(always)]
    pub fn stealth_pool(&mut self, stealth_pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.stealth_pool = Some(stealth_pool);
                    self
    }
      /// Data is validated through ZK proof verification.
/// Contains: nullifiers, linker encryptions, linker key commitments.
#[inline(always)]
    pub fn nullifier_and_linker_buffer(&mut self, nullifier_and_linker_buffer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_and_linker_buffer = Some(nullifier_and_linker_buffer);
                    self
    }
      /// Nullifier set data structure for efficient nullifier lookups.
/// PDA validated in validate_nullifier_set_accounts.
#[inline(always)]
    pub fn nullifier_set1(&mut self, nullifier_set1: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set1 = Some(nullifier_set1);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set2(&mut self, nullifier_set2: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set2 = Some(nullifier_set2);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set3(&mut self, nullifier_set3: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set3 = Some(nullifier_set3);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set4(&mut self, nullifier_set4: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set4 = Some(nullifier_set4);
                    self
    }
      #[inline(always)]
    pub fn nullifier_set5(&mut self, nullifier_set5: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.nullifier_set5 = Some(nullifier_set5);
                    self
    }
      /// ZK verifying key for Groth16 proof verification.
/// Contains the verification key elements (alpha, beta, gamma, delta, IC).
/// PDA validated in validate_zk_verifying_key_account.
#[inline(always)]
    pub fn zero_knowledge_verifying_key(&mut self, zero_knowledge_verifying_key: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.zero_knowledge_verifying_key = Some(zero_knowledge_verifying_key);
                    self
    }
      /// Temporary storage for MPC callback data.
/// Stores nonces and fees data needed by the callback handler.
/// Closed after callback to return rent to relayer.
#[inline(always)]
    pub fn computation_data(&mut self, computation_data: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.computation_data = Some(computation_data);
                    self
    }
      /// Per-mint lottery configuration. Bound into the Fiat-Shamir
/// aggregated hash so the prover and verifier agree on the constant
/// set used for the claim circuit's `ClaimTicketCalculator`.
#[inline(always)]
    pub fn lottery_config(&mut self, lottery_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lottery_config = Some(lottery_config);
                    self
    }
      /// Independent initiator identity — signs the queue ix separately from the relayer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."
#[inline(always)]
    pub fn initiator(&mut self, initiator: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.initiator = Some(initiator);
                    self
    }
                    #[inline(always)]
      pub fn computation_offset(&mut self, computation_offset: ComputationOffset) -> &mut Self {
        self.instruction.computation_offset = Some(computation_offset);
        self
      }
                #[inline(always)]
      pub fn fee_vault_offset(&mut self, fee_vault_offset: AccountOffset) -> &mut Self {
        self.instruction.fee_vault_offset = Some(fee_vault_offset);
        self
      }
                #[inline(always)]
      pub fn mpc_callback_data_offset(&mut self, mpc_callback_data_offset: AccountOffset) -> &mut Self {
        self.instruction.mpc_callback_data_offset = Some(mpc_callback_data_offset);
        self
      }
                #[inline(always)]
      pub fn number_of_burns(&mut self, number_of_burns: NumberOfBurns) -> &mut Self {
        self.instruction.number_of_burns = Some(number_of_burns);
        self
      }
                #[inline(always)]
      pub fn claim_input_buffer_offset(&mut self, claim_input_buffer_offset: AccountOffset) -> &mut Self {
        self.instruction.claim_input_buffer_offset = Some(claim_input_buffer_offset);
        self
      }
                #[inline(always)]
      pub fn stealth_pool_index(&mut self, stealth_pool_index: AccountOffset) -> &mut Self {
        self.instruction.stealth_pool_index = Some(stealth_pool_index);
        self
      }
                #[inline(always)]
      pub fn nullifier_and_linker_buffer_offset(&mut self, nullifier_and_linker_buffer_offset: AccountOffset) -> &mut Self {
        self.instruction.nullifier_and_linker_buffer_offset = Some(nullifier_and_linker_buffer_offset);
        self
      }
                #[inline(always)]
      pub fn dispatch_observer_cpi(&mut self, dispatch_observer_cpi: DispatchObserverCpi) -> &mut Self {
        self.instruction.dispatch_observer_cpi = Some(dispatch_observer_cpi);
        self
      }
                #[inline(always)]
      pub fn observer_output_x25519_public_key(&mut self, observer_output_x25519_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.instruction.observer_output_x25519_public_key = Some(observer_output_x25519_public_key);
        self
      }
                #[inline(always)]
      pub fn destination_discriminator(&mut self, destination_discriminator: InstructionDiscriminator) -> &mut Self {
        self.instruction.destination_discriminator = Some(destination_discriminator);
        self
      }
                #[inline(always)]
      pub fn priority_fees(&mut self, priority_fees: PriorityFees) -> &mut Self {
        self.instruction.priority_fees = Some(priority_fees);
        self
      }
                #[inline(always)]
      pub fn optional_data(&mut self, optional_data: OptionalData) -> &mut Self {
        self.instruction.optional_data = Some(optional_data);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = ClaimIntoNewSharedBalanceV17InstructionArgs {
                                                              computation_offset: self.instruction.computation_offset.clone().expect("computation_offset is not set"),
                                                                  fee_vault_offset: self.instruction.fee_vault_offset.clone().expect("fee_vault_offset is not set"),
                                                                  mpc_callback_data_offset: self.instruction.mpc_callback_data_offset.clone().expect("mpc_callback_data_offset is not set"),
                                                                  number_of_burns: self.instruction.number_of_burns.clone().expect("number_of_burns is not set"),
                                                                  claim_input_buffer_offset: self.instruction.claim_input_buffer_offset.clone().expect("claim_input_buffer_offset is not set"),
                                                                  stealth_pool_index: self.instruction.stealth_pool_index.clone().expect("stealth_pool_index is not set"),
                                                                  nullifier_and_linker_buffer_offset: self.instruction.nullifier_and_linker_buffer_offset.clone().expect("nullifier_and_linker_buffer_offset is not set"),
                                                                  dispatch_observer_cpi: self.instruction.dispatch_observer_cpi.clone().expect("dispatch_observer_cpi is not set"),
                                                                  observer_output_x25519_public_key: self.instruction.observer_output_x25519_public_key.clone().expect("observer_output_x25519_public_key is not set"),
                                                                  destination_discriminator: self.instruction.destination_discriminator.clone().expect("destination_discriminator is not set"),
                                                                  priority_fees: self.instruction.priority_fees.clone().expect("priority_fees is not set"),
                                                                  optional_data: self.instruction.optional_data.clone().expect("optional_data is not set"),
                                    };
        let instruction = ClaimIntoNewSharedBalanceV17Cpi {
        __program: self.instruction.__program,
                  
          relayer: self.instruction.relayer.expect("relayer is not set"),
                  
          sign_pda_account: self.instruction.sign_pda_account.expect("sign_pda_account is not set"),
                  
          mxe_account: self.instruction.mxe_account.expect("mxe_account is not set"),
                  
          mempool_account: self.instruction.mempool_account.expect("mempool_account is not set"),
                  
          executing_pool: self.instruction.executing_pool.expect("executing_pool is not set"),
                  
          computation_account: self.instruction.computation_account.expect("computation_account is not set"),
                  
          comp_def_account: self.instruction.comp_def_account.expect("comp_def_account is not set"),
                  
          cluster_account: self.instruction.cluster_account.expect("cluster_account is not set"),
                  
          pool_account: self.instruction.pool_account.expect("pool_account is not set"),
                  
          clock_account: self.instruction.clock_account.expect("clock_account is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          arcium_program: self.instruction.arcium_program.expect("arcium_program is not set"),
                  
          claim_input_buffer: self.instruction.claim_input_buffer.expect("claim_input_buffer is not set"),
                  
          receiver_address: self.instruction.receiver_address.expect("receiver_address is not set"),
                  
          receiver_user_account: self.instruction.receiver_user_account.expect("receiver_user_account is not set"),
                  
          receiver_token_account: self.instruction.receiver_token_account.expect("receiver_token_account is not set"),
                  
          relayer_account: self.instruction.relayer_account.expect("relayer_account is not set"),
                  
          relayer_fee_schedule: self.instruction.relayer_fee_schedule.expect("relayer_fee_schedule is not set"),
                  
          fee_schedule: self.instruction.fee_schedule.expect("fee_schedule is not set"),
                  
          fee_vault: self.instruction.fee_vault.expect("fee_vault is not set"),
                  
          token_pool: self.instruction.token_pool.expect("token_pool is not set"),
                  
          mint: self.instruction.mint.expect("mint is not set"),
                  
          protocol_config: self.instruction.protocol_config.expect("protocol_config is not set"),
                  
          stealth_pool: self.instruction.stealth_pool.expect("stealth_pool is not set"),
                  
          nullifier_and_linker_buffer: self.instruction.nullifier_and_linker_buffer.expect("nullifier_and_linker_buffer is not set"),
                  
          nullifier_set1: self.instruction.nullifier_set1.expect("nullifier_set1 is not set"),
                  
          nullifier_set2: self.instruction.nullifier_set2.expect("nullifier_set2 is not set"),
                  
          nullifier_set3: self.instruction.nullifier_set3.expect("nullifier_set3 is not set"),
                  
          nullifier_set4: self.instruction.nullifier_set4.expect("nullifier_set4 is not set"),
                  
          nullifier_set5: self.instruction.nullifier_set5.expect("nullifier_set5 is not set"),
                  
          zero_knowledge_verifying_key: self.instruction.zero_knowledge_verifying_key.expect("zero_knowledge_verifying_key is not set"),
                  
          computation_data: self.instruction.computation_data.expect("computation_data is not set"),
                  
          lottery_config: self.instruction.lottery_config.expect("lottery_config is not set"),
                  
          initiator: self.instruction.initiator.expect("initiator is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct ClaimIntoNewSharedBalanceV17CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            relayer: Option<&'b solana_account_info::AccountInfo<'a>>,
                sign_pda_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                mxe_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                mempool_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                executing_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                computation_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                comp_def_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                cluster_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                pool_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                clock_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                arcium_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                claim_input_buffer: Option<&'b solana_account_info::AccountInfo<'a>>,
                receiver_address: Option<&'b solana_account_info::AccountInfo<'a>>,
                receiver_user_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                receiver_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                relayer_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                relayer_fee_schedule: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_schedule: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                mint: Option<&'b solana_account_info::AccountInfo<'a>>,
                protocol_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                stealth_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_and_linker_buffer: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set1: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set2: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set3: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set4: Option<&'b solana_account_info::AccountInfo<'a>>,
                nullifier_set5: Option<&'b solana_account_info::AccountInfo<'a>>,
                zero_knowledge_verifying_key: Option<&'b solana_account_info::AccountInfo<'a>>,
                computation_data: Option<&'b solana_account_info::AccountInfo<'a>>,
                lottery_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                initiator: Option<&'b solana_account_info::AccountInfo<'a>>,
                        computation_offset: Option<ComputationOffset>,
                fee_vault_offset: Option<AccountOffset>,
                mpc_callback_data_offset: Option<AccountOffset>,
                number_of_burns: Option<NumberOfBurns>,
                claim_input_buffer_offset: Option<AccountOffset>,
                stealth_pool_index: Option<AccountOffset>,
                nullifier_and_linker_buffer_offset: Option<AccountOffset>,
                dispatch_observer_cpi: Option<DispatchObserverCpi>,
                observer_output_x25519_public_key: Option<ArciumX25519PublicKey>,
                destination_discriminator: Option<InstructionDiscriminator>,
                priority_fees: Option<PriorityFees>,
                optional_data: Option<OptionalData>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

