//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::SlotNumber;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const MIGRATE_PROTOCOL_CONFIG_LAYOUT_DISCRIMINATOR: [u8; 8] = [116, 225, 157, 18, 77, 255, 60, 128];

/// Accounts.
#[derive(Debug)]
pub struct MigrateProtocolConfigLayout {
            /// in the handler. The runtime's `realloc` additionally requires
/// the executing program to own the account.

    
              
          pub protocol_config: solana_pubkey::Pubkey,
                /// `AdminWallet` PDA gating the migration. Reuses the
/// `UPDATE_PROGRAM_INFORMATION_SEED` admin wallet — whoever can
/// already call `update_program_information` can migrate the
/// layout.

    
              
          pub admin_wallet: solana_pubkey::Pubkey,
                /// Either matches the admin wallet's authorised solana_address, or
/// the admin wallet is `PERMISSIONLESS_ADDRESS`.

    
              
          pub signer: solana_pubkey::Pubkey,
                /// Pays the rent delta for the +8-byte realloc.

    
              
          pub fee_payer: solana_pubkey::Pubkey,
                /// System program — used by `realloc` for rent transfer.

    
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl MigrateProtocolConfigLayout {
  pub fn instruction(&self, args: MigrateProtocolConfigLayoutInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: MigrateProtocolConfigLayoutInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.protocol_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.admin_wallet,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.signer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = MigrateProtocolConfigLayoutInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct MigrateProtocolConfigLayoutInstructionData {
            discriminator: [u8; 8],
            }

impl MigrateProtocolConfigLayoutInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [116, 225, 157, 18, 77, 255, 60, 128],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for MigrateProtocolConfigLayoutInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct MigrateProtocolConfigLayoutInstructionArgs {
                  pub computation_data_expiry_slots: SlotNumber,
      }

impl MigrateProtocolConfigLayoutInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `MigrateProtocolConfigLayout`.
///
/// ### Accounts:
///
                ///   0. `[writable]` protocol_config
          ///   1. `[]` admin_wallet
                ///   2. `[signer]` signer
                      ///   3. `[writable, signer]` fee_payer
                ///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct MigrateProtocolConfigLayoutBuilder {
            protocol_config: Option<solana_pubkey::Pubkey>,
                admin_wallet: Option<solana_pubkey::Pubkey>,
                signer: Option<solana_pubkey::Pubkey>,
                fee_payer: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                        computation_data_expiry_slots: Option<SlotNumber>,
        __program_id: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl MigrateProtocolConfigLayoutBuilder {
  pub fn new() -> Self {
    Self::default()
  }
    /// Set a custom program ID for the instruction (overrides the default).
    /// Use this when targeting a different deployment (e.g. devnet vs mainnet).
    #[inline(always)]
    pub fn program_id(&mut self, program_id: solana_pubkey::Pubkey) -> &mut Self {
        self.__program_id = Some(program_id);
        self
    }
            /// in the handler. The runtime's `realloc` additionally requires
/// the executing program to own the account.
#[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.protocol_config = Some(protocol_config);
                    self
    }
            /// `AdminWallet` PDA gating the migration. Reuses the
/// `UPDATE_PROGRAM_INFORMATION_SEED` admin wallet — whoever can
/// already call `update_program_information` can migrate the
/// layout.
#[inline(always)]
    pub fn admin_wallet(&mut self, admin_wallet: solana_pubkey::Pubkey) -> &mut Self {
                        self.admin_wallet = Some(admin_wallet);
                    self
    }
            /// Either matches the admin wallet's authorised solana_address, or
/// the admin wallet is `PERMISSIONLESS_ADDRESS`.
#[inline(always)]
    pub fn signer(&mut self, signer: solana_pubkey::Pubkey) -> &mut Self {
                        self.signer = Some(signer);
                    self
    }
            /// Pays the rent delta for the +8-byte realloc.
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_payer = Some(fee_payer);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
/// System program — used by `realloc` for rent transfer.
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn computation_data_expiry_slots(&mut self, computation_data_expiry_slots: SlotNumber) -> &mut Self {
        self.computation_data_expiry_slots = Some(computation_data_expiry_slots);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = MigrateProtocolConfigLayout {
                              protocol_config: self.protocol_config.expect("protocol_config is not set"),
                                        admin_wallet: self.admin_wallet.expect("admin_wallet is not set"),
                                        signer: self.signer.expect("signer is not set"),
                                        fee_payer: self.fee_payer.expect("fee_payer is not set"),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                      };
          let args = MigrateProtocolConfigLayoutInstructionArgs {
                                                              computation_data_expiry_slots: self.computation_data_expiry_slots.clone().expect("computation_data_expiry_slots is not set"),
                                    };
    
    {
            let mut ix = accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts);
            if let Some(program_id) = self.__program_id {
                ix.program_id = program_id;
            }
            ix
        }
  }
}

  /// `migrate_protocol_config_layout` CPI accounts.
  pub struct MigrateProtocolConfigLayoutCpiAccounts<'a, 'b> {
                  /// in the handler. The runtime's `realloc` additionally requires
/// the executing program to own the account.

      
                    
              pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
                        /// `AdminWallet` PDA gating the migration. Reuses the
/// `UPDATE_PROGRAM_INFORMATION_SEED` admin wallet — whoever can
/// already call `update_program_information` can migrate the
/// layout.

      
                    
              pub admin_wallet: &'b solana_account_info::AccountInfo<'a>,
                        /// Either matches the admin wallet's authorised solana_address, or
/// the admin wallet is `PERMISSIONLESS_ADDRESS`.

      
                    
              pub signer: &'b solana_account_info::AccountInfo<'a>,
                        /// Pays the rent delta for the +8-byte realloc.

      
                    
              pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                        /// System program — used by `realloc` for rent transfer.

      
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `migrate_protocol_config_layout` CPI instruction.
pub struct MigrateProtocolConfigLayoutCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
            /// in the handler. The runtime's `realloc` additionally requires
/// the executing program to own the account.

    
              
          pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
                /// `AdminWallet` PDA gating the migration. Reuses the
/// `UPDATE_PROGRAM_INFORMATION_SEED` admin wallet — whoever can
/// already call `update_program_information` can migrate the
/// layout.

    
              
          pub admin_wallet: &'b solana_account_info::AccountInfo<'a>,
                /// Either matches the admin wallet's authorised solana_address, or
/// the admin wallet is `PERMISSIONLESS_ADDRESS`.

    
              
          pub signer: &'b solana_account_info::AccountInfo<'a>,
                /// Pays the rent delta for the +8-byte realloc.

    
              
          pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                /// System program — used by `realloc` for rent transfer.

    
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: MigrateProtocolConfigLayoutInstructionArgs,
  }

impl<'a, 'b> MigrateProtocolConfigLayoutCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: MigrateProtocolConfigLayoutCpiAccounts<'a, 'b>,
              args: MigrateProtocolConfigLayoutInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              protocol_config: accounts.protocol_config,
              admin_wallet: accounts.admin_wallet,
              signer: accounts.signer,
              fee_payer: accounts.fee_payer,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.protocol_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.admin_wallet.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.signer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = MigrateProtocolConfigLayoutInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.protocol_config.clone());
                        account_infos.push(self.admin_wallet.clone());
                        account_infos.push(self.signer.clone());
                        account_infos.push(self.fee_payer.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `MigrateProtocolConfigLayout` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` protocol_config
          ///   1. `[]` admin_wallet
                ///   2. `[signer]` signer
                      ///   3. `[writable, signer]` fee_payer
          ///   4. `[]` system_program
#[derive(Clone, Debug)]
pub struct MigrateProtocolConfigLayoutCpiBuilder<'a, 'b> {
  instruction: Box<MigrateProtocolConfigLayoutCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> MigrateProtocolConfigLayoutCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(MigrateProtocolConfigLayoutCpiBuilderInstruction {
      __program: program,
              protocol_config: None,
              admin_wallet: None,
              signer: None,
              fee_payer: None,
              system_program: None,
                                            computation_data_expiry_slots: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      /// in the handler. The runtime's `realloc` additionally requires
/// the executing program to own the account.
#[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.protocol_config = Some(protocol_config);
                    self
    }
      /// `AdminWallet` PDA gating the migration. Reuses the
/// `UPDATE_PROGRAM_INFORMATION_SEED` admin wallet — whoever can
/// already call `update_program_information` can migrate the
/// layout.
#[inline(always)]
    pub fn admin_wallet(&mut self, admin_wallet: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin_wallet = Some(admin_wallet);
                    self
    }
      /// Either matches the admin wallet's authorised solana_address, or
/// the admin wallet is `PERMISSIONLESS_ADDRESS`.
#[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer = Some(signer);
                    self
    }
      /// Pays the rent delta for the +8-byte realloc.
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_payer = Some(fee_payer);
                    self
    }
      /// System program — used by `realloc` for rent transfer.
#[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn computation_data_expiry_slots(&mut self, computation_data_expiry_slots: SlotNumber) -> &mut Self {
        self.instruction.computation_data_expiry_slots = Some(computation_data_expiry_slots);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = MigrateProtocolConfigLayoutInstructionArgs {
                                                              computation_data_expiry_slots: self.instruction.computation_data_expiry_slots.clone().expect("computation_data_expiry_slots is not set"),
                                    };
        let instruction = MigrateProtocolConfigLayoutCpi {
        __program: self.instruction.__program,
                  
          protocol_config: self.instruction.protocol_config.expect("protocol_config is not set"),
                  
          admin_wallet: self.instruction.admin_wallet.expect("admin_wallet is not set"),
                  
          signer: self.instruction.signer.expect("signer is not set"),
                  
          fee_payer: self.instruction.fee_payer.expect("fee_payer is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct MigrateProtocolConfigLayoutCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            protocol_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                admin_wallet: Option<&'b solana_account_info::AccountInfo<'a>>,
                signer: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        computation_data_expiry_slots: Option<SlotNumber>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

