//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::AccountOffset;
use crate::types::ArciumX25519PublicKey;
use crate::types::ArciumX25519Nonce;
use crate::types::RescueCiphertext;
use crate::types::FieldElement25519;
use crate::types::PoseidonHash;
use crate::types::Groth16ProofA;
use crate::types::Groth16ProofB;
use crate::types::Groth16ProofC;
use crate::types::AesEncryptedUnspentTransactionOutputData;
use crate::types::OptionalData;
use solana_pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const POPULATE_STEALTH_POOL_DEPOSIT_WITH_ENCRYPTED_ADDRESS_INPUT_BUFFER_DISCRIMINATOR: [u8; 8] = [51, 97, 210, 102, 68, 137, 181, 142];

/// Accounts.
#[derive(Debug)]
pub struct PopulateStealthPoolDepositWithEncryptedAddressInputBuffer {
            /// The fee payer who pays rent on first allocation and binds the buffer's
/// PDA. The same `fee_payer` must consume / re-populate / close the buffer
/// in subsequent transactions (PDA seed match enforces this).

    
              
          pub fee_payer: solana_pubkey::Pubkey,
                /// The encrypted-address deposit input buffer. Allocated on first call,
/// overwritten on subsequent calls.

    
              
          pub stealth_pool_deposit_with_encrypted_address_input_buffer: solana_pubkey::Pubkey,
                /// System program for account creation.

    
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl PopulateStealthPoolDepositWithEncryptedAddressInputBuffer {
  pub fn instruction(&self, args: PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.fee_payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.stealth_pool_deposit_with_encrypted_address_input_buffer,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionData {
            discriminator: [u8; 8],
                                                                                                                              }

impl PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [51, 97, 210, 102, 68, 137, 181, 142],
                                                                                                                                                                                                                                                                                                          }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionArgs {
                  pub offset: AccountOffset,
                pub rescue_encryption_public_key: ArciumX25519PublicKey,
                pub aes_encryption_public_key: ArciumX25519PublicKey,
                pub rescue_encryption_nonce: ArciumX25519Nonce,
                pub rescue_encrypted_address_low: RescueCiphertext,
                pub rescue_encrypted_address_high: RescueCiphertext,
                pub rescue_encrypted_random_factor: RescueCiphertext,
                pub encrypted_address_source_pubkey: ArciumX25519PublicKey,
                pub encrypted_address_source_nonce: ArciumX25519Nonce,
                pub encrypted_address_source_ciphertext_low: RescueCiphertext,
                pub encrypted_address_source_ciphertext_high: RescueCiphertext,
                pub encryption_validation_polynomial: FieldElement25519,
                pub rescue_encryption_fiat_shamir_commitment: PoseidonHash,
                pub groth16_proof_a: Groth16ProofA,
                pub groth16_proof_b: Groth16ProofB,
                pub groth16_proof_c: Groth16ProofC,
                pub aes_encrypted_data: AesEncryptedUnspentTransactionOutputData,
                pub optional_data: OptionalData,
                pub destination_program: Pubkey,
                pub cpi_account1: Pubkey,
      }

impl PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `PopulateStealthPoolDepositWithEncryptedAddressInputBuffer`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` fee_payer
                ///   1. `[writable]` stealth_pool_deposit_with_encrypted_address_input_buffer
                ///   2. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct PopulateStealthPoolDepositWithEncryptedAddressInputBufferBuilder {
            fee_payer: Option<solana_pubkey::Pubkey>,
                stealth_pool_deposit_with_encrypted_address_input_buffer: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                        offset: Option<AccountOffset>,
                rescue_encryption_public_key: Option<ArciumX25519PublicKey>,
                aes_encryption_public_key: Option<ArciumX25519PublicKey>,
                rescue_encryption_nonce: Option<ArciumX25519Nonce>,
                rescue_encrypted_address_low: Option<RescueCiphertext>,
                rescue_encrypted_address_high: Option<RescueCiphertext>,
                rescue_encrypted_random_factor: Option<RescueCiphertext>,
                encrypted_address_source_pubkey: Option<ArciumX25519PublicKey>,
                encrypted_address_source_nonce: Option<ArciumX25519Nonce>,
                encrypted_address_source_ciphertext_low: Option<RescueCiphertext>,
                encrypted_address_source_ciphertext_high: Option<RescueCiphertext>,
                encryption_validation_polynomial: Option<FieldElement25519>,
                rescue_encryption_fiat_shamir_commitment: Option<PoseidonHash>,
                groth16_proof_a: Option<Groth16ProofA>,
                groth16_proof_b: Option<Groth16ProofB>,
                groth16_proof_c: Option<Groth16ProofC>,
                aes_encrypted_data: Option<AesEncryptedUnspentTransactionOutputData>,
                optional_data: Option<OptionalData>,
                destination_program: Option<Pubkey>,
                cpi_account1: Option<Pubkey>,
        __program_id: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl PopulateStealthPoolDepositWithEncryptedAddressInputBufferBuilder {
  pub fn new() -> Self {
    Self::default()
  }
    /// Set a custom program ID for the instruction (overrides the default).
    /// Use this when targeting a different deployment (e.g. devnet vs mainnet).
    #[inline(always)]
    pub fn program_id(&mut self, program_id: solana_pubkey::Pubkey) -> &mut Self {
        self.__program_id = Some(program_id);
        self
    }
            /// The fee payer who pays rent on first allocation and binds the buffer's
/// PDA. The same `fee_payer` must consume / re-populate / close the buffer
/// in subsequent transactions (PDA seed match enforces this).
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_payer = Some(fee_payer);
                    self
    }
            /// The encrypted-address deposit input buffer. Allocated on first call,
/// overwritten on subsequent calls.
#[inline(always)]
    pub fn stealth_pool_deposit_with_encrypted_address_input_buffer(&mut self, stealth_pool_deposit_with_encrypted_address_input_buffer: solana_pubkey::Pubkey) -> &mut Self {
                        self.stealth_pool_deposit_with_encrypted_address_input_buffer = Some(stealth_pool_deposit_with_encrypted_address_input_buffer);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
/// System program for account creation.
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn offset(&mut self, offset: AccountOffset) -> &mut Self {
        self.offset = Some(offset);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_public_key(&mut self, rescue_encryption_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.rescue_encryption_public_key = Some(rescue_encryption_public_key);
        self
      }
                #[inline(always)]
      pub fn aes_encryption_public_key(&mut self, aes_encryption_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.aes_encryption_public_key = Some(aes_encryption_public_key);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_nonce(&mut self, rescue_encryption_nonce: ArciumX25519Nonce) -> &mut Self {
        self.rescue_encryption_nonce = Some(rescue_encryption_nonce);
        self
      }
                #[inline(always)]
      pub fn rescue_encrypted_address_low(&mut self, rescue_encrypted_address_low: RescueCiphertext) -> &mut Self {
        self.rescue_encrypted_address_low = Some(rescue_encrypted_address_low);
        self
      }
                #[inline(always)]
      pub fn rescue_encrypted_address_high(&mut self, rescue_encrypted_address_high: RescueCiphertext) -> &mut Self {
        self.rescue_encrypted_address_high = Some(rescue_encrypted_address_high);
        self
      }
                #[inline(always)]
      pub fn rescue_encrypted_random_factor(&mut self, rescue_encrypted_random_factor: RescueCiphertext) -> &mut Self {
        self.rescue_encrypted_random_factor = Some(rescue_encrypted_random_factor);
        self
      }
                #[inline(always)]
      pub fn encrypted_address_source_pubkey(&mut self, encrypted_address_source_pubkey: ArciumX25519PublicKey) -> &mut Self {
        self.encrypted_address_source_pubkey = Some(encrypted_address_source_pubkey);
        self
      }
                #[inline(always)]
      pub fn encrypted_address_source_nonce(&mut self, encrypted_address_source_nonce: ArciumX25519Nonce) -> &mut Self {
        self.encrypted_address_source_nonce = Some(encrypted_address_source_nonce);
        self
      }
                #[inline(always)]
      pub fn encrypted_address_source_ciphertext_low(&mut self, encrypted_address_source_ciphertext_low: RescueCiphertext) -> &mut Self {
        self.encrypted_address_source_ciphertext_low = Some(encrypted_address_source_ciphertext_low);
        self
      }
                #[inline(always)]
      pub fn encrypted_address_source_ciphertext_high(&mut self, encrypted_address_source_ciphertext_high: RescueCiphertext) -> &mut Self {
        self.encrypted_address_source_ciphertext_high = Some(encrypted_address_source_ciphertext_high);
        self
      }
                #[inline(always)]
      pub fn encryption_validation_polynomial(&mut self, encryption_validation_polynomial: FieldElement25519) -> &mut Self {
        self.encryption_validation_polynomial = Some(encryption_validation_polynomial);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_fiat_shamir_commitment(&mut self, rescue_encryption_fiat_shamir_commitment: PoseidonHash) -> &mut Self {
        self.rescue_encryption_fiat_shamir_commitment = Some(rescue_encryption_fiat_shamir_commitment);
        self
      }
                #[inline(always)]
      pub fn groth16_proof_a(&mut self, groth16_proof_a: Groth16ProofA) -> &mut Self {
        self.groth16_proof_a = Some(groth16_proof_a);
        self
      }
                #[inline(always)]
      pub fn groth16_proof_b(&mut self, groth16_proof_b: Groth16ProofB) -> &mut Self {
        self.groth16_proof_b = Some(groth16_proof_b);
        self
      }
                #[inline(always)]
      pub fn groth16_proof_c(&mut self, groth16_proof_c: Groth16ProofC) -> &mut Self {
        self.groth16_proof_c = Some(groth16_proof_c);
        self
      }
                #[inline(always)]
      pub fn aes_encrypted_data(&mut self, aes_encrypted_data: AesEncryptedUnspentTransactionOutputData) -> &mut Self {
        self.aes_encrypted_data = Some(aes_encrypted_data);
        self
      }
                #[inline(always)]
      pub fn optional_data(&mut self, optional_data: OptionalData) -> &mut Self {
        self.optional_data = Some(optional_data);
        self
      }
                #[inline(always)]
      pub fn destination_program(&mut self, destination_program: Pubkey) -> &mut Self {
        self.destination_program = Some(destination_program);
        self
      }
                #[inline(always)]
      pub fn cpi_account1(&mut self, cpi_account1: Pubkey) -> &mut Self {
        self.cpi_account1 = Some(cpi_account1);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = PopulateStealthPoolDepositWithEncryptedAddressInputBuffer {
                              fee_payer: self.fee_payer.expect("fee_payer is not set"),
                                        stealth_pool_deposit_with_encrypted_address_input_buffer: self.stealth_pool_deposit_with_encrypted_address_input_buffer.expect("stealth_pool_deposit_with_encrypted_address_input_buffer is not set"),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                      };
          let args = PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionArgs {
                                                              offset: self.offset.clone().expect("offset is not set"),
                                                                  rescue_encryption_public_key: self.rescue_encryption_public_key.clone().expect("rescue_encryption_public_key is not set"),
                                                                  aes_encryption_public_key: self.aes_encryption_public_key.clone().expect("aes_encryption_public_key is not set"),
                                                                  rescue_encryption_nonce: self.rescue_encryption_nonce.clone().expect("rescue_encryption_nonce is not set"),
                                                                  rescue_encrypted_address_low: self.rescue_encrypted_address_low.clone().expect("rescue_encrypted_address_low is not set"),
                                                                  rescue_encrypted_address_high: self.rescue_encrypted_address_high.clone().expect("rescue_encrypted_address_high is not set"),
                                                                  rescue_encrypted_random_factor: self.rescue_encrypted_random_factor.clone().expect("rescue_encrypted_random_factor is not set"),
                                                                  encrypted_address_source_pubkey: self.encrypted_address_source_pubkey.clone().expect("encrypted_address_source_pubkey is not set"),
                                                                  encrypted_address_source_nonce: self.encrypted_address_source_nonce.clone().expect("encrypted_address_source_nonce is not set"),
                                                                  encrypted_address_source_ciphertext_low: self.encrypted_address_source_ciphertext_low.clone().expect("encrypted_address_source_ciphertext_low is not set"),
                                                                  encrypted_address_source_ciphertext_high: self.encrypted_address_source_ciphertext_high.clone().expect("encrypted_address_source_ciphertext_high is not set"),
                                                                  encryption_validation_polynomial: self.encryption_validation_polynomial.clone().expect("encryption_validation_polynomial is not set"),
                                                                  rescue_encryption_fiat_shamir_commitment: self.rescue_encryption_fiat_shamir_commitment.clone().expect("rescue_encryption_fiat_shamir_commitment is not set"),
                                                                  groth16_proof_a: self.groth16_proof_a.clone().expect("groth16_proof_a is not set"),
                                                                  groth16_proof_b: self.groth16_proof_b.clone().expect("groth16_proof_b is not set"),
                                                                  groth16_proof_c: self.groth16_proof_c.clone().expect("groth16_proof_c is not set"),
                                                                  aes_encrypted_data: self.aes_encrypted_data.clone().expect("aes_encrypted_data is not set"),
                                                                  optional_data: self.optional_data.clone().expect("optional_data is not set"),
                                                                  destination_program: self.destination_program.clone().expect("destination_program is not set"),
                                                                  cpi_account1: self.cpi_account1.clone().expect("cpi_account1 is not set"),
                                    };
    
    {
            let mut ix = accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts);
            if let Some(program_id) = self.__program_id {
                ix.program_id = program_id;
            }
            ix
        }
  }
}

  /// `populate_stealth_pool_deposit_with_encrypted_address_input_buffer` CPI accounts.
  pub struct PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpiAccounts<'a, 'b> {
                  /// The fee payer who pays rent on first allocation and binds the buffer's
/// PDA. The same `fee_payer` must consume / re-populate / close the buffer
/// in subsequent transactions (PDA seed match enforces this).

      
                    
              pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                        /// The encrypted-address deposit input buffer. Allocated on first call,
/// overwritten on subsequent calls.

      
                    
              pub stealth_pool_deposit_with_encrypted_address_input_buffer: &'b solana_account_info::AccountInfo<'a>,
                        /// System program for account creation.

      
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `populate_stealth_pool_deposit_with_encrypted_address_input_buffer` CPI instruction.
pub struct PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
            /// The fee payer who pays rent on first allocation and binds the buffer's
/// PDA. The same `fee_payer` must consume / re-populate / close the buffer
/// in subsequent transactions (PDA seed match enforces this).

    
              
          pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                /// The encrypted-address deposit input buffer. Allocated on first call,
/// overwritten on subsequent calls.

    
              
          pub stealth_pool_deposit_with_encrypted_address_input_buffer: &'b solana_account_info::AccountInfo<'a>,
                /// System program for account creation.

    
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionArgs,
  }

impl<'a, 'b> PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpiAccounts<'a, 'b>,
              args: PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              fee_payer: accounts.fee_payer,
              stealth_pool_deposit_with_encrypted_address_input_buffer: accounts.stealth_pool_deposit_with_encrypted_address_input_buffer,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(3+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.stealth_pool_deposit_with_encrypted_address_input_buffer.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.fee_payer.clone());
                        account_infos.push(self.stealth_pool_deposit_with_encrypted_address_input_buffer.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `PopulateStealthPoolDepositWithEncryptedAddressInputBuffer` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` fee_payer
                ///   1. `[writable]` stealth_pool_deposit_with_encrypted_address_input_buffer
          ///   2. `[]` system_program
#[derive(Clone, Debug)]
pub struct PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpiBuilder<'a, 'b> {
  instruction: Box<PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpiBuilderInstruction {
      __program: program,
              fee_payer: None,
              stealth_pool_deposit_with_encrypted_address_input_buffer: None,
              system_program: None,
                                            offset: None,
                                rescue_encryption_public_key: None,
                                aes_encryption_public_key: None,
                                rescue_encryption_nonce: None,
                                rescue_encrypted_address_low: None,
                                rescue_encrypted_address_high: None,
                                rescue_encrypted_random_factor: None,
                                encrypted_address_source_pubkey: None,
                                encrypted_address_source_nonce: None,
                                encrypted_address_source_ciphertext_low: None,
                                encrypted_address_source_ciphertext_high: None,
                                encryption_validation_polynomial: None,
                                rescue_encryption_fiat_shamir_commitment: None,
                                groth16_proof_a: None,
                                groth16_proof_b: None,
                                groth16_proof_c: None,
                                aes_encrypted_data: None,
                                optional_data: None,
                                destination_program: None,
                                cpi_account1: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      /// The fee payer who pays rent on first allocation and binds the buffer's
/// PDA. The same `fee_payer` must consume / re-populate / close the buffer
/// in subsequent transactions (PDA seed match enforces this).
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_payer = Some(fee_payer);
                    self
    }
      /// The encrypted-address deposit input buffer. Allocated on first call,
/// overwritten on subsequent calls.
#[inline(always)]
    pub fn stealth_pool_deposit_with_encrypted_address_input_buffer(&mut self, stealth_pool_deposit_with_encrypted_address_input_buffer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.stealth_pool_deposit_with_encrypted_address_input_buffer = Some(stealth_pool_deposit_with_encrypted_address_input_buffer);
                    self
    }
      /// System program for account creation.
#[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn offset(&mut self, offset: AccountOffset) -> &mut Self {
        self.instruction.offset = Some(offset);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_public_key(&mut self, rescue_encryption_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.instruction.rescue_encryption_public_key = Some(rescue_encryption_public_key);
        self
      }
                #[inline(always)]
      pub fn aes_encryption_public_key(&mut self, aes_encryption_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.instruction.aes_encryption_public_key = Some(aes_encryption_public_key);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_nonce(&mut self, rescue_encryption_nonce: ArciumX25519Nonce) -> &mut Self {
        self.instruction.rescue_encryption_nonce = Some(rescue_encryption_nonce);
        self
      }
                #[inline(always)]
      pub fn rescue_encrypted_address_low(&mut self, rescue_encrypted_address_low: RescueCiphertext) -> &mut Self {
        self.instruction.rescue_encrypted_address_low = Some(rescue_encrypted_address_low);
        self
      }
                #[inline(always)]
      pub fn rescue_encrypted_address_high(&mut self, rescue_encrypted_address_high: RescueCiphertext) -> &mut Self {
        self.instruction.rescue_encrypted_address_high = Some(rescue_encrypted_address_high);
        self
      }
                #[inline(always)]
      pub fn rescue_encrypted_random_factor(&mut self, rescue_encrypted_random_factor: RescueCiphertext) -> &mut Self {
        self.instruction.rescue_encrypted_random_factor = Some(rescue_encrypted_random_factor);
        self
      }
                #[inline(always)]
      pub fn encrypted_address_source_pubkey(&mut self, encrypted_address_source_pubkey: ArciumX25519PublicKey) -> &mut Self {
        self.instruction.encrypted_address_source_pubkey = Some(encrypted_address_source_pubkey);
        self
      }
                #[inline(always)]
      pub fn encrypted_address_source_nonce(&mut self, encrypted_address_source_nonce: ArciumX25519Nonce) -> &mut Self {
        self.instruction.encrypted_address_source_nonce = Some(encrypted_address_source_nonce);
        self
      }
                #[inline(always)]
      pub fn encrypted_address_source_ciphertext_low(&mut self, encrypted_address_source_ciphertext_low: RescueCiphertext) -> &mut Self {
        self.instruction.encrypted_address_source_ciphertext_low = Some(encrypted_address_source_ciphertext_low);
        self
      }
                #[inline(always)]
      pub fn encrypted_address_source_ciphertext_high(&mut self, encrypted_address_source_ciphertext_high: RescueCiphertext) -> &mut Self {
        self.instruction.encrypted_address_source_ciphertext_high = Some(encrypted_address_source_ciphertext_high);
        self
      }
                #[inline(always)]
      pub fn encryption_validation_polynomial(&mut self, encryption_validation_polynomial: FieldElement25519) -> &mut Self {
        self.instruction.encryption_validation_polynomial = Some(encryption_validation_polynomial);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_fiat_shamir_commitment(&mut self, rescue_encryption_fiat_shamir_commitment: PoseidonHash) -> &mut Self {
        self.instruction.rescue_encryption_fiat_shamir_commitment = Some(rescue_encryption_fiat_shamir_commitment);
        self
      }
                #[inline(always)]
      pub fn groth16_proof_a(&mut self, groth16_proof_a: Groth16ProofA) -> &mut Self {
        self.instruction.groth16_proof_a = Some(groth16_proof_a);
        self
      }
                #[inline(always)]
      pub fn groth16_proof_b(&mut self, groth16_proof_b: Groth16ProofB) -> &mut Self {
        self.instruction.groth16_proof_b = Some(groth16_proof_b);
        self
      }
                #[inline(always)]
      pub fn groth16_proof_c(&mut self, groth16_proof_c: Groth16ProofC) -> &mut Self {
        self.instruction.groth16_proof_c = Some(groth16_proof_c);
        self
      }
                #[inline(always)]
      pub fn aes_encrypted_data(&mut self, aes_encrypted_data: AesEncryptedUnspentTransactionOutputData) -> &mut Self {
        self.instruction.aes_encrypted_data = Some(aes_encrypted_data);
        self
      }
                #[inline(always)]
      pub fn optional_data(&mut self, optional_data: OptionalData) -> &mut Self {
        self.instruction.optional_data = Some(optional_data);
        self
      }
                #[inline(always)]
      pub fn destination_program(&mut self, destination_program: Pubkey) -> &mut Self {
        self.instruction.destination_program = Some(destination_program);
        self
      }
                #[inline(always)]
      pub fn cpi_account1(&mut self, cpi_account1: Pubkey) -> &mut Self {
        self.instruction.cpi_account1 = Some(cpi_account1);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = PopulateStealthPoolDepositWithEncryptedAddressInputBufferInstructionArgs {
                                                              offset: self.instruction.offset.clone().expect("offset is not set"),
                                                                  rescue_encryption_public_key: self.instruction.rescue_encryption_public_key.clone().expect("rescue_encryption_public_key is not set"),
                                                                  aes_encryption_public_key: self.instruction.aes_encryption_public_key.clone().expect("aes_encryption_public_key is not set"),
                                                                  rescue_encryption_nonce: self.instruction.rescue_encryption_nonce.clone().expect("rescue_encryption_nonce is not set"),
                                                                  rescue_encrypted_address_low: self.instruction.rescue_encrypted_address_low.clone().expect("rescue_encrypted_address_low is not set"),
                                                                  rescue_encrypted_address_high: self.instruction.rescue_encrypted_address_high.clone().expect("rescue_encrypted_address_high is not set"),
                                                                  rescue_encrypted_random_factor: self.instruction.rescue_encrypted_random_factor.clone().expect("rescue_encrypted_random_factor is not set"),
                                                                  encrypted_address_source_pubkey: self.instruction.encrypted_address_source_pubkey.clone().expect("encrypted_address_source_pubkey is not set"),
                                                                  encrypted_address_source_nonce: self.instruction.encrypted_address_source_nonce.clone().expect("encrypted_address_source_nonce is not set"),
                                                                  encrypted_address_source_ciphertext_low: self.instruction.encrypted_address_source_ciphertext_low.clone().expect("encrypted_address_source_ciphertext_low is not set"),
                                                                  encrypted_address_source_ciphertext_high: self.instruction.encrypted_address_source_ciphertext_high.clone().expect("encrypted_address_source_ciphertext_high is not set"),
                                                                  encryption_validation_polynomial: self.instruction.encryption_validation_polynomial.clone().expect("encryption_validation_polynomial is not set"),
                                                                  rescue_encryption_fiat_shamir_commitment: self.instruction.rescue_encryption_fiat_shamir_commitment.clone().expect("rescue_encryption_fiat_shamir_commitment is not set"),
                                                                  groth16_proof_a: self.instruction.groth16_proof_a.clone().expect("groth16_proof_a is not set"),
                                                                  groth16_proof_b: self.instruction.groth16_proof_b.clone().expect("groth16_proof_b is not set"),
                                                                  groth16_proof_c: self.instruction.groth16_proof_c.clone().expect("groth16_proof_c is not set"),
                                                                  aes_encrypted_data: self.instruction.aes_encrypted_data.clone().expect("aes_encrypted_data is not set"),
                                                                  optional_data: self.instruction.optional_data.clone().expect("optional_data is not set"),
                                                                  destination_program: self.instruction.destination_program.clone().expect("destination_program is not set"),
                                                                  cpi_account1: self.instruction.cpi_account1.clone().expect("cpi_account1 is not set"),
                                    };
        let instruction = PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpi {
        __program: self.instruction.__program,
                  
          fee_payer: self.instruction.fee_payer.expect("fee_payer is not set"),
                  
          stealth_pool_deposit_with_encrypted_address_input_buffer: self.instruction.stealth_pool_deposit_with_encrypted_address_input_buffer.expect("stealth_pool_deposit_with_encrypted_address_input_buffer is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct PopulateStealthPoolDepositWithEncryptedAddressInputBufferCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            fee_payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                stealth_pool_deposit_with_encrypted_address_input_buffer: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        offset: Option<AccountOffset>,
                rescue_encryption_public_key: Option<ArciumX25519PublicKey>,
                aes_encryption_public_key: Option<ArciumX25519PublicKey>,
                rescue_encryption_nonce: Option<ArciumX25519Nonce>,
                rescue_encrypted_address_low: Option<RescueCiphertext>,
                rescue_encrypted_address_high: Option<RescueCiphertext>,
                rescue_encrypted_random_factor: Option<RescueCiphertext>,
                encrypted_address_source_pubkey: Option<ArciumX25519PublicKey>,
                encrypted_address_source_nonce: Option<ArciumX25519Nonce>,
                encrypted_address_source_ciphertext_low: Option<RescueCiphertext>,
                encrypted_address_source_ciphertext_high: Option<RescueCiphertext>,
                encryption_validation_polynomial: Option<FieldElement25519>,
                rescue_encryption_fiat_shamir_commitment: Option<PoseidonHash>,
                groth16_proof_a: Option<Groth16ProofA>,
                groth16_proof_b: Option<Groth16ProofB>,
                groth16_proof_c: Option<Groth16ProofC>,
                aes_encrypted_data: Option<AesEncryptedUnspentTransactionOutputData>,
                optional_data: Option<OptionalData>,
                destination_program: Option<Pubkey>,
                cpi_account1: Option<Pubkey>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

