//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::ComputationOffset;
use crate::types::AccountOffset;
use crate::types::ArciumX25519PublicKey;
use crate::types::ArciumX25519Nonce;
use crate::types::RescueCiphertext;
use crate::types::DispatchObserverCpi;
use crate::types::InstructionDiscriminator;
use crate::types::PriorityFees;
use crate::types::OptionalData;
use solana_pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const TRANSFER_FROM_NETWORK_BALANCE_TO_EXISTING_SHARED_BALANCE_V17_DISCRIMINATOR: [u8; 8] = [151, 193, 55, 222, 190, 222, 28, 254];

/// Accounts.
#[derive(Debug)]
pub struct TransferFromNetworkBalanceToExistingSharedBalanceV17 {
      
              
          pub sender: solana_pubkey::Pubkey,
                /// The fee payer who pays rent for account creation.

    
              
          pub fee_payer: solana_pubkey::Pubkey,
          
              
          pub sign_pda_account: solana_pubkey::Pubkey,
          
              
          pub mxe_account: solana_pubkey::Pubkey,
          
              
          pub mempool_account: solana_pubkey::Pubkey,
          
              
          pub executing_pool: solana_pubkey::Pubkey,
          
              
          pub computation_account: solana_pubkey::Pubkey,
          
              
          pub comp_def_account: solana_pubkey::Pubkey,
          
              
          pub cluster_account: solana_pubkey::Pubkey,
          
              
          pub pool_account: solana_pubkey::Pubkey,
          
              
          pub clock_account: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
          
              
          pub arcium_program: solana_pubkey::Pubkey,
          
              
          pub sender_token_account: solana_pubkey::Pubkey,
          
              
          pub receiver_address: solana_pubkey::Pubkey,
          
              
          pub receiver_token_account: solana_pubkey::Pubkey,
          
              
          pub fee_schedule: solana_pubkey::Pubkey,
          
              
          pub fee_vault: solana_pubkey::Pubkey,
          
              
          pub token_pool: solana_pubkey::Pubkey,
          
              
          pub mint: solana_pubkey::Pubkey,
          
              
          pub protocol_config: solana_pubkey::Pubkey,
          
              
          pub computation_data: solana_pubkey::Pubkey,
                /// Independent initiator identity — signs the queue ix separately from the domain signer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."

    
              
          pub initiator: solana_pubkey::Pubkey,
      }

impl TransferFromNetworkBalanceToExistingSharedBalanceV17 {
  pub fn instruction(&self, args: TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(23+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.sender,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.sign_pda_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mxe_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.mempool_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.executing_pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.computation_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.comp_def_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.cluster_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.pool_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.clock_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.arcium_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.sender_token_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.receiver_address,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.receiver_token_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.fee_schedule,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_vault,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.protocol_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.computation_data,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.initiator,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionData {
            discriminator: [u8; 8],
                                                                                    }

impl TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [151, 193, 55, 222, 190, 222, 28, 254],
                                                                                                                                                                                                        }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionArgs {
                  pub computation_offset: ComputationOffset,
                pub fee_vault_offset: AccountOffset,
                pub mpc_callback_data_offset: AccountOffset,
                pub rescue_encryption_public_key: ArciumX25519PublicKey,
                pub rescue_encryption_nonce: ArciumX25519Nonce,
                pub rescue_encrypted_transfer_amount: RescueCiphertext,
                pub dispatch_observer_cpi: DispatchObserverCpi,
                pub observer_output_x25519_public_key: ArciumX25519PublicKey,
                pub destination_discriminator: InstructionDiscriminator,
                pub priority_fees: PriorityFees,
                pub optional_data: OptionalData,
                pub destination_program: Pubkey,
                pub cpi_account1: Pubkey,
      }

impl TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `TransferFromNetworkBalanceToExistingSharedBalanceV17`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` sender
                      ///   1. `[writable, signer]` fee_payer
                ///   2. `[writable]` sign_pda_account
          ///   3. `[]` mxe_account
                ///   4. `[writable]` mempool_account
                ///   5. `[writable]` executing_pool
                ///   6. `[writable]` computation_account
          ///   7. `[]` comp_def_account
                ///   8. `[writable]` cluster_account
                      ///   9. `[writable, optional]` pool_account (default to `G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC`)
                      ///   10. `[writable, optional]` clock_account (default to `7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot`)
                ///   11. `[optional]` system_program (default to `11111111111111111111111111111111`)
                ///   12. `[optional]` arcium_program (default to `Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ`)
                ///   13. `[writable]` sender_token_account
          ///   14. `[]` receiver_address
                ///   15. `[writable]` receiver_token_account
          ///   16. `[]` fee_schedule
                ///   17. `[writable]` fee_vault
          ///   18. `[]` token_pool
          ///   19. `[]` mint
          ///   20. `[]` protocol_config
                ///   21. `[writable]` computation_data
                ///   22. `[signer]` initiator
#[derive(Clone, Debug, Default)]
pub struct TransferFromNetworkBalanceToExistingSharedBalanceV17Builder {
            sender: Option<solana_pubkey::Pubkey>,
                fee_payer: Option<solana_pubkey::Pubkey>,
                sign_pda_account: Option<solana_pubkey::Pubkey>,
                mxe_account: Option<solana_pubkey::Pubkey>,
                mempool_account: Option<solana_pubkey::Pubkey>,
                executing_pool: Option<solana_pubkey::Pubkey>,
                computation_account: Option<solana_pubkey::Pubkey>,
                comp_def_account: Option<solana_pubkey::Pubkey>,
                cluster_account: Option<solana_pubkey::Pubkey>,
                pool_account: Option<solana_pubkey::Pubkey>,
                clock_account: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                arcium_program: Option<solana_pubkey::Pubkey>,
                sender_token_account: Option<solana_pubkey::Pubkey>,
                receiver_address: Option<solana_pubkey::Pubkey>,
                receiver_token_account: Option<solana_pubkey::Pubkey>,
                fee_schedule: Option<solana_pubkey::Pubkey>,
                fee_vault: Option<solana_pubkey::Pubkey>,
                token_pool: Option<solana_pubkey::Pubkey>,
                mint: Option<solana_pubkey::Pubkey>,
                protocol_config: Option<solana_pubkey::Pubkey>,
                computation_data: Option<solana_pubkey::Pubkey>,
                initiator: Option<solana_pubkey::Pubkey>,
                        computation_offset: Option<ComputationOffset>,
                fee_vault_offset: Option<AccountOffset>,
                mpc_callback_data_offset: Option<AccountOffset>,
                rescue_encryption_public_key: Option<ArciumX25519PublicKey>,
                rescue_encryption_nonce: Option<ArciumX25519Nonce>,
                rescue_encrypted_transfer_amount: Option<RescueCiphertext>,
                dispatch_observer_cpi: Option<DispatchObserverCpi>,
                observer_output_x25519_public_key: Option<ArciumX25519PublicKey>,
                destination_discriminator: Option<InstructionDiscriminator>,
                priority_fees: Option<PriorityFees>,
                optional_data: Option<OptionalData>,
                destination_program: Option<Pubkey>,
                cpi_account1: Option<Pubkey>,
        __program_id: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl TransferFromNetworkBalanceToExistingSharedBalanceV17Builder {
  pub fn new() -> Self {
    Self::default()
  }
    /// Set a custom program ID for the instruction (overrides the default).
    /// Use this when targeting a different deployment (e.g. devnet vs mainnet).
    #[inline(always)]
    pub fn program_id(&mut self, program_id: solana_pubkey::Pubkey) -> &mut Self {
        self.__program_id = Some(program_id);
        self
    }
            #[inline(always)]
    pub fn sender(&mut self, sender: solana_pubkey::Pubkey) -> &mut Self {
                        self.sender = Some(sender);
                    self
    }
            /// The fee payer who pays rent for account creation.
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_payer = Some(fee_payer);
                    self
    }
            #[inline(always)]
    pub fn sign_pda_account(&mut self, sign_pda_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.sign_pda_account = Some(sign_pda_account);
                    self
    }
            #[inline(always)]
    pub fn mxe_account(&mut self, mxe_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.mxe_account = Some(mxe_account);
                    self
    }
            #[inline(always)]
    pub fn mempool_account(&mut self, mempool_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.mempool_account = Some(mempool_account);
                    self
    }
            #[inline(always)]
    pub fn executing_pool(&mut self, executing_pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.executing_pool = Some(executing_pool);
                    self
    }
            #[inline(always)]
    pub fn computation_account(&mut self, computation_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.computation_account = Some(computation_account);
                    self
    }
            #[inline(always)]
    pub fn comp_def_account(&mut self, comp_def_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.comp_def_account = Some(comp_def_account);
                    self
    }
            #[inline(always)]
    pub fn cluster_account(&mut self, cluster_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.cluster_account = Some(cluster_account);
                    self
    }
            /// `[optional account, default to 'G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC']`
#[inline(always)]
    pub fn pool_account(&mut self, pool_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.pool_account = Some(pool_account);
                    self
    }
            /// `[optional account, default to '7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot']`
#[inline(always)]
    pub fn clock_account(&mut self, clock_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.clock_account = Some(clock_account);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// `[optional account, default to 'Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ']`
#[inline(always)]
    pub fn arcium_program(&mut self, arcium_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.arcium_program = Some(arcium_program);
                    self
    }
            #[inline(always)]
    pub fn sender_token_account(&mut self, sender_token_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.sender_token_account = Some(sender_token_account);
                    self
    }
            #[inline(always)]
    pub fn receiver_address(&mut self, receiver_address: solana_pubkey::Pubkey) -> &mut Self {
                        self.receiver_address = Some(receiver_address);
                    self
    }
            #[inline(always)]
    pub fn receiver_token_account(&mut self, receiver_token_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.receiver_token_account = Some(receiver_token_account);
                    self
    }
            #[inline(always)]
    pub fn fee_schedule(&mut self, fee_schedule: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_schedule = Some(fee_schedule);
                    self
    }
            #[inline(always)]
    pub fn fee_vault(&mut self, fee_vault: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_vault = Some(fee_vault);
                    self
    }
            #[inline(always)]
    pub fn token_pool(&mut self, token_pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_pool = Some(token_pool);
                    self
    }
            #[inline(always)]
    pub fn mint(&mut self, mint: solana_pubkey::Pubkey) -> &mut Self {
                        self.mint = Some(mint);
                    self
    }
            #[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.protocol_config = Some(protocol_config);
                    self
    }
            #[inline(always)]
    pub fn computation_data(&mut self, computation_data: solana_pubkey::Pubkey) -> &mut Self {
                        self.computation_data = Some(computation_data);
                    self
    }
            /// Independent initiator identity — signs the queue ix separately from the domain signer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."
#[inline(always)]
    pub fn initiator(&mut self, initiator: solana_pubkey::Pubkey) -> &mut Self {
                        self.initiator = Some(initiator);
                    self
    }
                    #[inline(always)]
      pub fn computation_offset(&mut self, computation_offset: ComputationOffset) -> &mut Self {
        self.computation_offset = Some(computation_offset);
        self
      }
                #[inline(always)]
      pub fn fee_vault_offset(&mut self, fee_vault_offset: AccountOffset) -> &mut Self {
        self.fee_vault_offset = Some(fee_vault_offset);
        self
      }
                #[inline(always)]
      pub fn mpc_callback_data_offset(&mut self, mpc_callback_data_offset: AccountOffset) -> &mut Self {
        self.mpc_callback_data_offset = Some(mpc_callback_data_offset);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_public_key(&mut self, rescue_encryption_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.rescue_encryption_public_key = Some(rescue_encryption_public_key);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_nonce(&mut self, rescue_encryption_nonce: ArciumX25519Nonce) -> &mut Self {
        self.rescue_encryption_nonce = Some(rescue_encryption_nonce);
        self
      }
                #[inline(always)]
      pub fn rescue_encrypted_transfer_amount(&mut self, rescue_encrypted_transfer_amount: RescueCiphertext) -> &mut Self {
        self.rescue_encrypted_transfer_amount = Some(rescue_encrypted_transfer_amount);
        self
      }
                #[inline(always)]
      pub fn dispatch_observer_cpi(&mut self, dispatch_observer_cpi: DispatchObserverCpi) -> &mut Self {
        self.dispatch_observer_cpi = Some(dispatch_observer_cpi);
        self
      }
                #[inline(always)]
      pub fn observer_output_x25519_public_key(&mut self, observer_output_x25519_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.observer_output_x25519_public_key = Some(observer_output_x25519_public_key);
        self
      }
                #[inline(always)]
      pub fn destination_discriminator(&mut self, destination_discriminator: InstructionDiscriminator) -> &mut Self {
        self.destination_discriminator = Some(destination_discriminator);
        self
      }
                #[inline(always)]
      pub fn priority_fees(&mut self, priority_fees: PriorityFees) -> &mut Self {
        self.priority_fees = Some(priority_fees);
        self
      }
                #[inline(always)]
      pub fn optional_data(&mut self, optional_data: OptionalData) -> &mut Self {
        self.optional_data = Some(optional_data);
        self
      }
                #[inline(always)]
      pub fn destination_program(&mut self, destination_program: Pubkey) -> &mut Self {
        self.destination_program = Some(destination_program);
        self
      }
                #[inline(always)]
      pub fn cpi_account1(&mut self, cpi_account1: Pubkey) -> &mut Self {
        self.cpi_account1 = Some(cpi_account1);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = TransferFromNetworkBalanceToExistingSharedBalanceV17 {
                              sender: self.sender.expect("sender is not set"),
                                        fee_payer: self.fee_payer.expect("fee_payer is not set"),
                                        sign_pda_account: self.sign_pda_account.expect("sign_pda_account is not set"),
                                        mxe_account: self.mxe_account.expect("mxe_account is not set"),
                                        mempool_account: self.mempool_account.expect("mempool_account is not set"),
                                        executing_pool: self.executing_pool.expect("executing_pool is not set"),
                                        computation_account: self.computation_account.expect("computation_account is not set"),
                                        comp_def_account: self.comp_def_account.expect("comp_def_account is not set"),
                                        cluster_account: self.cluster_account.expect("cluster_account is not set"),
                                        pool_account: self.pool_account.unwrap_or(solana_pubkey::pubkey!("G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC")),
                                        clock_account: self.clock_account.unwrap_or(solana_pubkey::pubkey!("7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot")),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                                        arcium_program: self.arcium_program.unwrap_or(solana_pubkey::pubkey!("Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ")),
                                        sender_token_account: self.sender_token_account.expect("sender_token_account is not set"),
                                        receiver_address: self.receiver_address.expect("receiver_address is not set"),
                                        receiver_token_account: self.receiver_token_account.expect("receiver_token_account is not set"),
                                        fee_schedule: self.fee_schedule.expect("fee_schedule is not set"),
                                        fee_vault: self.fee_vault.expect("fee_vault is not set"),
                                        token_pool: self.token_pool.expect("token_pool is not set"),
                                        mint: self.mint.expect("mint is not set"),
                                        protocol_config: self.protocol_config.expect("protocol_config is not set"),
                                        computation_data: self.computation_data.expect("computation_data is not set"),
                                        initiator: self.initiator.expect("initiator is not set"),
                      };
          let args = TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionArgs {
                                                              computation_offset: self.computation_offset.clone().expect("computation_offset is not set"),
                                                                  fee_vault_offset: self.fee_vault_offset.clone().expect("fee_vault_offset is not set"),
                                                                  mpc_callback_data_offset: self.mpc_callback_data_offset.clone().expect("mpc_callback_data_offset is not set"),
                                                                  rescue_encryption_public_key: self.rescue_encryption_public_key.clone().expect("rescue_encryption_public_key is not set"),
                                                                  rescue_encryption_nonce: self.rescue_encryption_nonce.clone().expect("rescue_encryption_nonce is not set"),
                                                                  rescue_encrypted_transfer_amount: self.rescue_encrypted_transfer_amount.clone().expect("rescue_encrypted_transfer_amount is not set"),
                                                                  dispatch_observer_cpi: self.dispatch_observer_cpi.clone().expect("dispatch_observer_cpi is not set"),
                                                                  observer_output_x25519_public_key: self.observer_output_x25519_public_key.clone().expect("observer_output_x25519_public_key is not set"),
                                                                  destination_discriminator: self.destination_discriminator.clone().expect("destination_discriminator is not set"),
                                                                  priority_fees: self.priority_fees.clone().expect("priority_fees is not set"),
                                                                  optional_data: self.optional_data.clone().expect("optional_data is not set"),
                                                                  destination_program: self.destination_program.clone().expect("destination_program is not set"),
                                                                  cpi_account1: self.cpi_account1.clone().expect("cpi_account1 is not set"),
                                    };
    
    {
            let mut ix = accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts);
            if let Some(program_id) = self.__program_id {
                ix.program_id = program_id;
            }
            ix
        }
  }
}

  /// `transfer_from_network_balance_to_existing_shared_balance_v17` CPI accounts.
  pub struct TransferFromNetworkBalanceToExistingSharedBalanceV17CpiAccounts<'a, 'b> {
          
                    
              pub sender: &'b solana_account_info::AccountInfo<'a>,
                        /// The fee payer who pays rent for account creation.

      
                    
              pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub sign_pda_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mxe_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mempool_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub executing_pool: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub computation_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub comp_def_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cluster_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub pool_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub clock_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub arcium_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub sender_token_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub receiver_address: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub receiver_token_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub fee_schedule: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub fee_vault: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_pool: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mint: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub computation_data: &'b solana_account_info::AccountInfo<'a>,
                        /// Independent initiator identity — signs the queue ix separately from the domain signer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."

      
                    
              pub initiator: &'b solana_account_info::AccountInfo<'a>,
            }

/// `transfer_from_network_balance_to_existing_shared_balance_v17` CPI instruction.
pub struct TransferFromNetworkBalanceToExistingSharedBalanceV17Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub sender: &'b solana_account_info::AccountInfo<'a>,
                /// The fee payer who pays rent for account creation.

    
              
          pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub sign_pda_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mxe_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mempool_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub executing_pool: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub computation_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub comp_def_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cluster_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub pool_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub clock_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub arcium_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub sender_token_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub receiver_address: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub receiver_token_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub fee_schedule: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub fee_vault: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_pool: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mint: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub protocol_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub computation_data: &'b solana_account_info::AccountInfo<'a>,
                /// Independent initiator identity — signs the queue ix separately from the domain signer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."

    
              
          pub initiator: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionArgs,
  }

impl<'a, 'b> TransferFromNetworkBalanceToExistingSharedBalanceV17Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: TransferFromNetworkBalanceToExistingSharedBalanceV17CpiAccounts<'a, 'b>,
              args: TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              sender: accounts.sender,
              fee_payer: accounts.fee_payer,
              sign_pda_account: accounts.sign_pda_account,
              mxe_account: accounts.mxe_account,
              mempool_account: accounts.mempool_account,
              executing_pool: accounts.executing_pool,
              computation_account: accounts.computation_account,
              comp_def_account: accounts.comp_def_account,
              cluster_account: accounts.cluster_account,
              pool_account: accounts.pool_account,
              clock_account: accounts.clock_account,
              system_program: accounts.system_program,
              arcium_program: accounts.arcium_program,
              sender_token_account: accounts.sender_token_account,
              receiver_address: accounts.receiver_address,
              receiver_token_account: accounts.receiver_token_account,
              fee_schedule: accounts.fee_schedule,
              fee_vault: accounts.fee_vault,
              token_pool: accounts.token_pool,
              mint: accounts.mint,
              protocol_config: accounts.protocol_config,
              computation_data: accounts.computation_data,
              initiator: accounts.initiator,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(23+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.sender.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.sign_pda_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mxe_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.mempool_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.executing_pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.computation_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.comp_def_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.cluster_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.clock_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.arcium_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.sender_token_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.receiver_address.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.receiver_token_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.fee_schedule.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_vault.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.protocol_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.computation_data.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.initiator.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::UMBRA_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(24 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.sender.clone());
                        account_infos.push(self.fee_payer.clone());
                        account_infos.push(self.sign_pda_account.clone());
                        account_infos.push(self.mxe_account.clone());
                        account_infos.push(self.mempool_account.clone());
                        account_infos.push(self.executing_pool.clone());
                        account_infos.push(self.computation_account.clone());
                        account_infos.push(self.comp_def_account.clone());
                        account_infos.push(self.cluster_account.clone());
                        account_infos.push(self.pool_account.clone());
                        account_infos.push(self.clock_account.clone());
                        account_infos.push(self.system_program.clone());
                        account_infos.push(self.arcium_program.clone());
                        account_infos.push(self.sender_token_account.clone());
                        account_infos.push(self.receiver_address.clone());
                        account_infos.push(self.receiver_token_account.clone());
                        account_infos.push(self.fee_schedule.clone());
                        account_infos.push(self.fee_vault.clone());
                        account_infos.push(self.token_pool.clone());
                        account_infos.push(self.mint.clone());
                        account_infos.push(self.protocol_config.clone());
                        account_infos.push(self.computation_data.clone());
                        account_infos.push(self.initiator.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `TransferFromNetworkBalanceToExistingSharedBalanceV17` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` sender
                      ///   1. `[writable, signer]` fee_payer
                ///   2. `[writable]` sign_pda_account
          ///   3. `[]` mxe_account
                ///   4. `[writable]` mempool_account
                ///   5. `[writable]` executing_pool
                ///   6. `[writable]` computation_account
          ///   7. `[]` comp_def_account
                ///   8. `[writable]` cluster_account
                ///   9. `[writable]` pool_account
                ///   10. `[writable]` clock_account
          ///   11. `[]` system_program
          ///   12. `[]` arcium_program
                ///   13. `[writable]` sender_token_account
          ///   14. `[]` receiver_address
                ///   15. `[writable]` receiver_token_account
          ///   16. `[]` fee_schedule
                ///   17. `[writable]` fee_vault
          ///   18. `[]` token_pool
          ///   19. `[]` mint
          ///   20. `[]` protocol_config
                ///   21. `[writable]` computation_data
                ///   22. `[signer]` initiator
#[derive(Clone, Debug)]
pub struct TransferFromNetworkBalanceToExistingSharedBalanceV17CpiBuilder<'a, 'b> {
  instruction: Box<TransferFromNetworkBalanceToExistingSharedBalanceV17CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> TransferFromNetworkBalanceToExistingSharedBalanceV17CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(TransferFromNetworkBalanceToExistingSharedBalanceV17CpiBuilderInstruction {
      __program: program,
              sender: None,
              fee_payer: None,
              sign_pda_account: None,
              mxe_account: None,
              mempool_account: None,
              executing_pool: None,
              computation_account: None,
              comp_def_account: None,
              cluster_account: None,
              pool_account: None,
              clock_account: None,
              system_program: None,
              arcium_program: None,
              sender_token_account: None,
              receiver_address: None,
              receiver_token_account: None,
              fee_schedule: None,
              fee_vault: None,
              token_pool: None,
              mint: None,
              protocol_config: None,
              computation_data: None,
              initiator: None,
                                            computation_offset: None,
                                fee_vault_offset: None,
                                mpc_callback_data_offset: None,
                                rescue_encryption_public_key: None,
                                rescue_encryption_nonce: None,
                                rescue_encrypted_transfer_amount: None,
                                dispatch_observer_cpi: None,
                                observer_output_x25519_public_key: None,
                                destination_discriminator: None,
                                priority_fees: None,
                                optional_data: None,
                                destination_program: None,
                                cpi_account1: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn sender(&mut self, sender: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.sender = Some(sender);
                    self
    }
      /// The fee payer who pays rent for account creation.
#[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_payer = Some(fee_payer);
                    self
    }
      #[inline(always)]
    pub fn sign_pda_account(&mut self, sign_pda_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.sign_pda_account = Some(sign_pda_account);
                    self
    }
      #[inline(always)]
    pub fn mxe_account(&mut self, mxe_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mxe_account = Some(mxe_account);
                    self
    }
      #[inline(always)]
    pub fn mempool_account(&mut self, mempool_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mempool_account = Some(mempool_account);
                    self
    }
      #[inline(always)]
    pub fn executing_pool(&mut self, executing_pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.executing_pool = Some(executing_pool);
                    self
    }
      #[inline(always)]
    pub fn computation_account(&mut self, computation_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.computation_account = Some(computation_account);
                    self
    }
      #[inline(always)]
    pub fn comp_def_account(&mut self, comp_def_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.comp_def_account = Some(comp_def_account);
                    self
    }
      #[inline(always)]
    pub fn cluster_account(&mut self, cluster_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cluster_account = Some(cluster_account);
                    self
    }
      #[inline(always)]
    pub fn pool_account(&mut self, pool_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.pool_account = Some(pool_account);
                    self
    }
      #[inline(always)]
    pub fn clock_account(&mut self, clock_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.clock_account = Some(clock_account);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      #[inline(always)]
    pub fn arcium_program(&mut self, arcium_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.arcium_program = Some(arcium_program);
                    self
    }
      #[inline(always)]
    pub fn sender_token_account(&mut self, sender_token_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.sender_token_account = Some(sender_token_account);
                    self
    }
      #[inline(always)]
    pub fn receiver_address(&mut self, receiver_address: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.receiver_address = Some(receiver_address);
                    self
    }
      #[inline(always)]
    pub fn receiver_token_account(&mut self, receiver_token_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.receiver_token_account = Some(receiver_token_account);
                    self
    }
      #[inline(always)]
    pub fn fee_schedule(&mut self, fee_schedule: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_schedule = Some(fee_schedule);
                    self
    }
      #[inline(always)]
    pub fn fee_vault(&mut self, fee_vault: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_vault = Some(fee_vault);
                    self
    }
      #[inline(always)]
    pub fn token_pool(&mut self, token_pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_pool = Some(token_pool);
                    self
    }
      #[inline(always)]
    pub fn mint(&mut self, mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mint = Some(mint);
                    self
    }
      #[inline(always)]
    pub fn protocol_config(&mut self, protocol_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.protocol_config = Some(protocol_config);
                    self
    }
      #[inline(always)]
    pub fn computation_data(&mut self, computation_data: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.computation_data = Some(computation_data);
                    self
    }
      /// Independent initiator identity — signs the queue ix separately from the domain signer.
/// Its pubkey is persisted on ComputationData and forwarded to the destination program
/// in the observer CPI so destinations can validate "this request was initiated by my PDA."
#[inline(always)]
    pub fn initiator(&mut self, initiator: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.initiator = Some(initiator);
                    self
    }
                    #[inline(always)]
      pub fn computation_offset(&mut self, computation_offset: ComputationOffset) -> &mut Self {
        self.instruction.computation_offset = Some(computation_offset);
        self
      }
                #[inline(always)]
      pub fn fee_vault_offset(&mut self, fee_vault_offset: AccountOffset) -> &mut Self {
        self.instruction.fee_vault_offset = Some(fee_vault_offset);
        self
      }
                #[inline(always)]
      pub fn mpc_callback_data_offset(&mut self, mpc_callback_data_offset: AccountOffset) -> &mut Self {
        self.instruction.mpc_callback_data_offset = Some(mpc_callback_data_offset);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_public_key(&mut self, rescue_encryption_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.instruction.rescue_encryption_public_key = Some(rescue_encryption_public_key);
        self
      }
                #[inline(always)]
      pub fn rescue_encryption_nonce(&mut self, rescue_encryption_nonce: ArciumX25519Nonce) -> &mut Self {
        self.instruction.rescue_encryption_nonce = Some(rescue_encryption_nonce);
        self
      }
                #[inline(always)]
      pub fn rescue_encrypted_transfer_amount(&mut self, rescue_encrypted_transfer_amount: RescueCiphertext) -> &mut Self {
        self.instruction.rescue_encrypted_transfer_amount = Some(rescue_encrypted_transfer_amount);
        self
      }
                #[inline(always)]
      pub fn dispatch_observer_cpi(&mut self, dispatch_observer_cpi: DispatchObserverCpi) -> &mut Self {
        self.instruction.dispatch_observer_cpi = Some(dispatch_observer_cpi);
        self
      }
                #[inline(always)]
      pub fn observer_output_x25519_public_key(&mut self, observer_output_x25519_public_key: ArciumX25519PublicKey) -> &mut Self {
        self.instruction.observer_output_x25519_public_key = Some(observer_output_x25519_public_key);
        self
      }
                #[inline(always)]
      pub fn destination_discriminator(&mut self, destination_discriminator: InstructionDiscriminator) -> &mut Self {
        self.instruction.destination_discriminator = Some(destination_discriminator);
        self
      }
                #[inline(always)]
      pub fn priority_fees(&mut self, priority_fees: PriorityFees) -> &mut Self {
        self.instruction.priority_fees = Some(priority_fees);
        self
      }
                #[inline(always)]
      pub fn optional_data(&mut self, optional_data: OptionalData) -> &mut Self {
        self.instruction.optional_data = Some(optional_data);
        self
      }
                #[inline(always)]
      pub fn destination_program(&mut self, destination_program: Pubkey) -> &mut Self {
        self.instruction.destination_program = Some(destination_program);
        self
      }
                #[inline(always)]
      pub fn cpi_account1(&mut self, cpi_account1: Pubkey) -> &mut Self {
        self.instruction.cpi_account1 = Some(cpi_account1);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = TransferFromNetworkBalanceToExistingSharedBalanceV17InstructionArgs {
                                                              computation_offset: self.instruction.computation_offset.clone().expect("computation_offset is not set"),
                                                                  fee_vault_offset: self.instruction.fee_vault_offset.clone().expect("fee_vault_offset is not set"),
                                                                  mpc_callback_data_offset: self.instruction.mpc_callback_data_offset.clone().expect("mpc_callback_data_offset is not set"),
                                                                  rescue_encryption_public_key: self.instruction.rescue_encryption_public_key.clone().expect("rescue_encryption_public_key is not set"),
                                                                  rescue_encryption_nonce: self.instruction.rescue_encryption_nonce.clone().expect("rescue_encryption_nonce is not set"),
                                                                  rescue_encrypted_transfer_amount: self.instruction.rescue_encrypted_transfer_amount.clone().expect("rescue_encrypted_transfer_amount is not set"),
                                                                  dispatch_observer_cpi: self.instruction.dispatch_observer_cpi.clone().expect("dispatch_observer_cpi is not set"),
                                                                  observer_output_x25519_public_key: self.instruction.observer_output_x25519_public_key.clone().expect("observer_output_x25519_public_key is not set"),
                                                                  destination_discriminator: self.instruction.destination_discriminator.clone().expect("destination_discriminator is not set"),
                                                                  priority_fees: self.instruction.priority_fees.clone().expect("priority_fees is not set"),
                                                                  optional_data: self.instruction.optional_data.clone().expect("optional_data is not set"),
                                                                  destination_program: self.instruction.destination_program.clone().expect("destination_program is not set"),
                                                                  cpi_account1: self.instruction.cpi_account1.clone().expect("cpi_account1 is not set"),
                                    };
        let instruction = TransferFromNetworkBalanceToExistingSharedBalanceV17Cpi {
        __program: self.instruction.__program,
                  
          sender: self.instruction.sender.expect("sender is not set"),
                  
          fee_payer: self.instruction.fee_payer.expect("fee_payer is not set"),
                  
          sign_pda_account: self.instruction.sign_pda_account.expect("sign_pda_account is not set"),
                  
          mxe_account: self.instruction.mxe_account.expect("mxe_account is not set"),
                  
          mempool_account: self.instruction.mempool_account.expect("mempool_account is not set"),
                  
          executing_pool: self.instruction.executing_pool.expect("executing_pool is not set"),
                  
          computation_account: self.instruction.computation_account.expect("computation_account is not set"),
                  
          comp_def_account: self.instruction.comp_def_account.expect("comp_def_account is not set"),
                  
          cluster_account: self.instruction.cluster_account.expect("cluster_account is not set"),
                  
          pool_account: self.instruction.pool_account.expect("pool_account is not set"),
                  
          clock_account: self.instruction.clock_account.expect("clock_account is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          arcium_program: self.instruction.arcium_program.expect("arcium_program is not set"),
                  
          sender_token_account: self.instruction.sender_token_account.expect("sender_token_account is not set"),
                  
          receiver_address: self.instruction.receiver_address.expect("receiver_address is not set"),
                  
          receiver_token_account: self.instruction.receiver_token_account.expect("receiver_token_account is not set"),
                  
          fee_schedule: self.instruction.fee_schedule.expect("fee_schedule is not set"),
                  
          fee_vault: self.instruction.fee_vault.expect("fee_vault is not set"),
                  
          token_pool: self.instruction.token_pool.expect("token_pool is not set"),
                  
          mint: self.instruction.mint.expect("mint is not set"),
                  
          protocol_config: self.instruction.protocol_config.expect("protocol_config is not set"),
                  
          computation_data: self.instruction.computation_data.expect("computation_data is not set"),
                  
          initiator: self.instruction.initiator.expect("initiator is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct TransferFromNetworkBalanceToExistingSharedBalanceV17CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            sender: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                sign_pda_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                mxe_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                mempool_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                executing_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                computation_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                comp_def_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                cluster_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                pool_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                clock_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                arcium_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                sender_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                receiver_address: Option<&'b solana_account_info::AccountInfo<'a>>,
                receiver_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_schedule: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                mint: Option<&'b solana_account_info::AccountInfo<'a>>,
                protocol_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                computation_data: Option<&'b solana_account_info::AccountInfo<'a>>,
                initiator: Option<&'b solana_account_info::AccountInfo<'a>>,
                        computation_offset: Option<ComputationOffset>,
                fee_vault_offset: Option<AccountOffset>,
                mpc_callback_data_offset: Option<AccountOffset>,
                rescue_encryption_public_key: Option<ArciumX25519PublicKey>,
                rescue_encryption_nonce: Option<ArciumX25519Nonce>,
                rescue_encrypted_transfer_amount: Option<RescueCiphertext>,
                dispatch_observer_cpi: Option<DispatchObserverCpi>,
                observer_output_x25519_public_key: Option<ArciumX25519PublicKey>,
                destination_discriminator: Option<InstructionDiscriminator>,
                priority_fees: Option<PriorityFees>,
                optional_data: Option<OptionalData>,
                destination_program: Option<Pubkey>,
                cpi_account1: Option<Pubkey>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

