//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::VersionByte;
use crate::types::CanonicalBump;
use crate::types::SlotNumber;
use crate::types::ArciumX25519Nonce;
use crate::types::OptionalData;
use crate::types::ReservedByte;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitialisePointsForNetworkBalanceV17ComputationData {
pub discriminator: [u8; 8],
pub version_byte: VersionByte,
pub canonical_bump: CanonicalBump,
/// Slot at which this MPC computation was queued. Set by the
/// queue handler from `Clock::get()?.slot`. Read by
/// `close_computation_data` for the cleanup TTL gate. Field
/// position (FIRST user field) is canonical across all
/// ComputationData structs so cleanup can read at a fixed offset.
pub queued_at_slot: SlotNumber,
/// Output nonce supplied to Arcium for the tuple-encrypted output
/// covering balance + both points fields. The callback writes
/// `next_ciphertext_nonce(account_output_nonce)` to the live
/// `EncryptedTokenAccount.nonce` field.
pub account_output_nonce: ArciumX25519Nonce,
pub optional_data: OptionalData,
pub reserved_byte: [ReservedByte; 0],
}


pub const INITIALISE_POINTS_FOR_NETWORK_BALANCE_V17_COMPUTATION_DATA_DISCRIMINATOR: [u8; 8] = [54, 199, 109, 212, 31, 91, 155, 238];

impl InitialisePointsForNetworkBalanceV17ComputationData {
      pub const LEN: usize = 67;
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for InitialisePointsForNetworkBalanceV17ComputationData {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_initialise_points_for_network_balance_v17_computation_data(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::DecodedAccount<InitialisePointsForNetworkBalanceV17ComputationData>, std::io::Error> {
  let accounts = fetch_all_initialise_points_for_network_balance_v17_computation_data(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_initialise_points_for_network_balance_v17_computation_data(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::DecodedAccount<InitialisePointsForNetworkBalanceV17ComputationData>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<InitialisePointsForNetworkBalanceV17ComputationData>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::new(std::io::ErrorKind::Other, format!("Account not found: {}", address)))?;
      let data = InitialisePointsForNetworkBalanceV17ComputationData::from_bytes(&account.data)?;
      decoded_accounts.push(crate::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_initialise_points_for_network_balance_v17_computation_data(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::MaybeAccount<InitialisePointsForNetworkBalanceV17ComputationData>, std::io::Error> {
    let accounts = fetch_all_maybe_initialise_points_for_network_balance_v17_computation_data(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_initialise_points_for_network_balance_v17_computation_data(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::MaybeAccount<InitialisePointsForNetworkBalanceV17ComputationData>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<InitialisePointsForNetworkBalanceV17ComputationData>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = InitialisePointsForNetworkBalanceV17ComputationData::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::MaybeAccount::Exists(crate::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for InitialisePointsForNetworkBalanceV17ComputationData {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for InitialisePointsForNetworkBalanceV17ComputationData {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for InitialisePointsForNetworkBalanceV17ComputationData {
      fn owner() -> Pubkey {
        crate::UMBRA_ID
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for InitialisePointsForNetworkBalanceV17ComputationData {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for InitialisePointsForNetworkBalanceV17ComputationData {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

