//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::VersionByte;
use crate::types::CanonicalBump;
use crate::types::ReservedByte;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct OnchainRescueCipherDecryptionHelper {
pub discriminator: [u8; 8],
pub version_byte: VersionByte,
pub canonical_bump: CanonicalBump,
#[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
pub reserved_byte: [ReservedByte; 128],
}


pub const ONCHAIN_RESCUE_CIPHER_DECRYPTION_HELPER_DISCRIMINATOR: [u8; 8] = [152, 216, 198, 204, 102, 102, 149, 154];

impl OnchainRescueCipherDecryptionHelper {
      pub const LEN: usize = 139;
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for OnchainRescueCipherDecryptionHelper {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_onchain_rescue_cipher_decryption_helper(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::DecodedAccount<OnchainRescueCipherDecryptionHelper>, std::io::Error> {
  let accounts = fetch_all_onchain_rescue_cipher_decryption_helper(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_onchain_rescue_cipher_decryption_helper(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::DecodedAccount<OnchainRescueCipherDecryptionHelper>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<OnchainRescueCipherDecryptionHelper>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::new(std::io::ErrorKind::Other, format!("Account not found: {}", address)))?;
      let data = OnchainRescueCipherDecryptionHelper::from_bytes(&account.data)?;
      decoded_accounts.push(crate::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_onchain_rescue_cipher_decryption_helper(
  rpc: &solana_client::rpc_client::RpcClient,
  address: &solana_pubkey::Pubkey,
) -> Result<crate::shared::MaybeAccount<OnchainRescueCipherDecryptionHelper>, std::io::Error> {
    let accounts = fetch_all_maybe_onchain_rescue_cipher_decryption_helper(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_onchain_rescue_cipher_decryption_helper(
  rpc: &solana_client::rpc_client::RpcClient,
  addresses: &[solana_pubkey::Pubkey],
) -> Result<Vec<crate::shared::MaybeAccount<OnchainRescueCipherDecryptionHelper>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<OnchainRescueCipherDecryptionHelper>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = OnchainRescueCipherDecryptionHelper::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::MaybeAccount::Exists(crate::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for OnchainRescueCipherDecryptionHelper {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for OnchainRescueCipherDecryptionHelper {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for OnchainRescueCipherDecryptionHelper {
      fn owner() -> Pubkey {
        crate::UMBRA_ID
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for OnchainRescueCipherDecryptionHelper {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for OnchainRescueCipherDecryptionHelper {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

